### ISSUE TITLE
Can't read duration for webm

### ISSUE THREAD

**Issue by SimonSimCity** [PHP-FFMpeg/PHP-FFMpeg#103]
Currently, it's impossible for me to get the duration of an webm video-file.

I am using the module in version 0.4.4 and I just get a list of streams back, where I have the stat-time, but not the end-time and neither a duration.

By calling `ffprobe` by hand, without any extra, adding `-print_format json`, I don't get the duration in the JSON as well.

Can you please add an option to read the duration - even so it's not provided in the JSON output?

I do get the duration, when adding the parameter `-show_format` .... haven't tried this for other formats ...

**Comment by codeAshu** [comment]
Run the command

`ffprobe -v quiet -print_format json -show_format  -show_streams input.webm`

If you are looking for duration of each stream in webm container, the field name and location is different in the `ffprobe` output. In each stream you would see a field `tags`
```
"tags": {
                "language": "eng",
                "HANDLER_NAME": "ISO Media file produced by Google Inc. Created on: 12/09/2019.",
                "VENDOR_ID": "[0][0][0][0]",
                "ENCODER": "Lavc59.4.101 libvorbis",
                "DURATION": "00:03:14.703000000"
            }
```

You would have to convert this human readable time format into seconds. You can easily do with following utility python function. Or you can write one in your fav language.

```python
def convert_secs(text):
    if isinstance(text, float):
        num = str(text)
        nums = num.split('.')
    else:
        nums = text.split(':')
    if len(nums) == 2:
        st_sn = int(nums[0]) * 60 + float(nums[1])
        return st_sn
    elif len(nums) == 3:
        st_sn = int(nums[0]) * 3600 + int(nums[1]) * 60 + float(nums[2])
        return st_sn
    else:
        raise ValueError("Not correct time")
```
