### ISSUE TITLE
Set profile for H264

### ISSUE THREAD

**Issue by zang** [PHP-FFMpeg/PHP-FFMpeg#105]
I am trying to convert mov to mp4. Is there a way to specify profile? I.e. I'd like to use Main profile. Thanks in advance.

**Comment by done** [comment]
Ran into the same problem, did you happen to find a solution for this you'd like to share?

**Comment by donelpasso** [comment]
Same here! wth is wrong with the developers not answering to this damn issue!

**Comment by iljalukin** [comment]
According to the manual there should be a possibility to set the profile with setAdditionalParameters-Method. Have you tried it already?

$format = new FFMpeg\Format\Video\X264();
$format->setAdditionalParameters(array('-profile:v', 'main'));
$video->save($format, 'video.avi');

**Comment by donelpasso** [comment]
Your code specifically didn't work but you gave me the idea, it works now thanks!

**Comment by kotso** [comment]
@donelpasso if you could share how you managed implement it would be grate, struggling with same issue now.
