### ISSUE TITLE
Big avi files

### ISSUE THREAD

**Issue by pollyrobin** [PHP-FFMpeg/PHP-FFMpeg#111]
When i do the following

video = $ffmpeg->open("test.avi");
I get the message that the command can't be executed
 Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffprobe failed to execute command '/usr/bin/avprobe' 'test.avi' '-show_streams' '-print_format' 'json''

when i  literally run /usr/bin/avprobe' 'test.avi' '-show_streams' '-print_format' 'json' on the command line i get the message 

max_analyze_duration 5000000 reached at 5000000 microseconds
I added the -analyzeduration 50000000 in my command line 

The file is 367MB. 

I mannualy tried editing the extra command in the FFProbe->probe method.
That did not work either.

What should be a solution for this?

**Comment by Romain** [comment]
I managed to open a 1Gb file.
I think this issue is no more relevant.
