### ISSUE TITLE
Unable to load FFProbe on Ubuntu 12.04 ?

### ISSUE THREAD

**Issue by hoandang** [PHP-FFMpeg/PHP-FFMpeg#121]
I know this is a very common issue but after trying the solutions from other issues, the ffprobe still is not found. 

I installed ffmpeg via this method <a href="http://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu"> http://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu</a>  and the ffmpeg and ffprobe are located in the user path ~/bin. so I export the path to global path in .zshrc by doing so

```
export PATH="$HOME/bin"
```

After exporting, the ffmpeg and ffprobe command works perfectly ok. but when I try in PHP code `$ffmpeg = FFMpeg\FFMpeg::create();`, it keeps throwing the error **_Unable to load FFProbe**_

**Comment by jayers** [comment]
$ffmpeg = \FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'fprobe.binaries' => '/usr/bin/ffprobe',
));

you miss a 'f'

it should be

$ffmpeg = \FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe',
));

**Comment by serialworm** [comment]
Good catch.
