### ISSUE TITLE
x264 encoding options are hard-coded for ALL video formats

### ISSUE THREAD

**Issue by curtisdf** [PHP-FFMpeg/PHP-FFMpeg#124]
In FFMpeg/Media/Video.php, it is evident by browsing the contents of this file that upon saving a video, there are about a dozen command-line flags that automatically get used no matter what type of video is being encoded. But those options all are normally associated with x264 encoding.  These options are hard-coded and cannot be overwritten or turned off without subclassing this class and rewriting the whole save() method.

Did I miss something?  Despite all the class infrastructure for the different video formats (e.g. Ogg, WebM, WMV), it seems that the underlying save() function really only supports x264, and only one certain set of encoding parameters at that.  The FFMpeg/Media/\* and FFMpeg/Format/\* class hierarchies need to be fixed so the command-line flags are specified in the Format file, and the Media file just aggregates this info and runs the appropriate ffmpeg command.

**Comment by NSBrianWard** [comment]
So right after the `-trellis 1` flag that's coded into the actual ffmpeg command that gets run (in **FFMpeg/Media/Video.php**), I want to insert `-pix_fmt yuv420p` to because without it there seem to be some issues dealing with quicktime rle files. Any thoughts on how to do this correctly? I tried popping it straight into the file, and that solved my problem. But in a production environment, I'm not sure how to implement this. Do I have to reimplement the whole save method? If so, what's the best way to do that as an override? I'm under the constraint that I can't change anything in my laravel vendor folder.

**Comment by seblavoie** [comment]
I actually have the exact same problem as @NSBrianWard. I would also like to add `-pix_fmt yuv420p` at the end of the command. As I understand from other issues, there is some refactoring planned. 

For now, what I could think about as a solution would be to add an optional arguent that would take an array of commands that would get merged into `$commands` somewhere around [this line](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Media/Video.php#L108).

It could then look like this:

```
$format = new \FFMpeg\Format\Video\X264('libvo_aacenc', 'libx264');
$video->save($format, storage_path() . '/renders/output.mp4', ['-pix_fmt', 'yuv420p']);
```

This might be a shortsighted solution so let me know if you have any other suggestions. As @NSBrianWard, I am a bit lost as where to go from here.

**Comment by NSBrianWard** [comment]
I never did get this solved. If I ever have resources to go back and address that in my project, I'd still like to. MOST of the files users upload to my app don't have this problem, but the sticking point is our 3D animators who export Quicktime RLE files out of 3ds Max (they don't have a bunch of video export options, unfortunately, and really hate having to spend a bunch of time running a bunch of file conversions). Their files ALWAYS break in the way the I described above. It would be really nice to see a fix for this.
