### ISSUE TITLE
merge two video files

### ISSUE THREAD

**Issue by sy2nyk** [PHP-FFMpeg/PHP-FFMpeg#133]
Hi! How i can merge two video (mp4) files with PHP-FFMpeg library?

**Comment by allan-simon** [comment]
https://github.com/we-bridge/PHP-FFMpeg/pull/1  you or the author of php-ffpmeg may want to rework that pull request to integrate the feature mainstream

**Comment by edianogama** [comment]
@allan-simon I can use this now ? I view the commits of @we-brige but the function is not avaiable for me in composer. "php-ffmpeg/php-ffmpeg": "~0.5"
How I can use this ?
Thanks;

**Comment by patkar** [comment]
See #188
