### ISSUE TITLE
Your FFProbe version is too old and does not support `-show_streams` option, please upgrade.

### ISSUE THREAD

**Issue by Sc3n3** [PHP-FFMpeg/PHP-FFMpeg#135]
Hi.

I've searched the problem a little bit. I see, OptionTester is seaching show_streams in FFmpeg's help. Not FFprobe's.

$output = $this->retrieveHelpOutput(); returns ffmpeg -help.

[root@snc845 ~]# ffprobe -help
ffprobe version 2.4.3 Copyright (c) 2007-2014 the FFmpeg developers
  built on Nov 30 2014 11:15:32 with gcc 4.1.2 (GCC) 20080704 (Red Hat 4.1.2-55)
  configuration: --disable-yasm
  libavutil      54.  7.100 / 54.  7.100
  libavcodec     56.  1.100 / 56.  1.100
  libavformat    56.  4.101 / 56.  4.101
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  1.100 /  5.  1.100
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] [INPUT_FILE]

Main options:
-L                  show license
-h topic            show help
-? topic            show help
-help topic         show help
--help topic        show help
-version            show version
-buildconf          show build configuration
-formats            show available formats
-devices            show available devices
-codecs             show available codecs
-decoders           show available decoders
-encoders           show available encoders
-bsfs               show available bit stream filters
-protocols          show available protocols
-filters            show available filters
-pix_fmts           show available pixel formats
-layouts            show standard channel layouts
-sample_fmts        show available audio sample formats
-colors             show available color names
-loglevel loglevel  set logging level
-v loglevel         set logging level
-report             generate a report
-max_alloc bytes    set maximum size of a single allocated block
-cpuflags flags     force specific cpu flags
-hide_banner hide_banner  do not show program banner
-f format           force format
-unit               show unit of the displayed values
-prefix             use SI prefixes for the displayed values
-byte_binary_prefix  use binary prefixes for byte units
-sexagesimal        use sexagesimal format HOURS:MM:SS.MICROSECONDS for time units
-pretty             prettify the format of displayed values, make it more human readable
-print_format format  set the output printing format (available formats are: default, compact, csv, flat, ini, json, xml)
-of format          alias for -print_format
-select_streams stream_specifier  select the specified streams
-sections           print sections structure and section information, and exit
-show_data          show packets data
-show_data_hash     show packets data hash
-show_error         show probing error
-show_format        show format/container info
-show_frames        show frames info
-show_format_entry entry  show a particular entry from the format/container info
-show_entries entry_list  show a set of specified entries
-show_packets       show packets info
-show_programs      show programs info
-show_streams       show streams info
-show_chapters      show chapters info
-count_frames       count the number of frames per stream
-count_packets      count the number of packets per stream
-show_program_version  show ffprobe version
-show_library_versions  show library versions
-show_versions      show program and library versions
-show_private_data  show private data
-private            same as show_private_data
-bitexact           force bitexact output
-read_intervals read_intervals  set read intervals
-default            generic catch all option
-i input_file       read specified file

**Comment by NerdGr8** [comment]
Did you end up resolving this issue?
Having the same issue on IIS

**Comment by JOOSTR** [comment]
I "fixed" it by making the application pool to run as administrator.
Previously I managed to fix it by giving IUSR and IIS_USRS full permissions to the executable, though that didn't work this time.

**Comment by NerdGr8** [comment]
@JOOSTR correct that works!

Thanks so much

**Comment by marwan2** [comment]
Change permissions doesn't solve this stupid bug, I think it's related to your package
and you should handle it better and be specific 

I hate this kind of stupid packages !!!
