### ISSUE TITLE
AAC library discrepancy

### ISSUE THREAD

**Issue by brokentone** [PHP-FFMpeg/PHP-FFMpeg#137]
The AAC Audio format relies on libfdk_aac, whereas the X264 Video format relies on libfaac.

It seems unlikely that anyone would have both installed, so it would seem that one or the other will always be failing. Is there perhaps a different way to specify which library is available, or should we update one or the other? My thought would be to update both to "libfdk_aac" for the moment as this is the library ffmpeg is currently recommending in its install process.

**Comment by romainneutron** [comment]
It's supported in the latest version.

**Comment by primedirective** [comment]
I think I'm running into the same problem here. My `FFMpeg\Format\Video\X264()` video save is failing out with FFMpeg not recognizing the audio format. It *does* seem to work in the command line if I force it to use `libfdk_aac`. The incoming file format is MP4/MP3.

Trying to update PHP-FFMpeg via Composer in my project isn't yielding much luck though. It's claiming that I already have the latest version. Is there something else I need to do here to make this happen? I do see that there is a 0.6 tag in the repo, but changing to `require-dev` isn't working either. Is that the latest version you're referring to? I originally grabbed PHP-FFMpeg in November through Composer with this exact same setup...

    {
        "require": {
            "php-ffmpeg/php-ffmpeg": "~0.5"
        }
    }

Thoughts?

**Comment by jankal** [comment]
@romainneutron Please reopen. Not fixed. #231 and #222
