### ISSUE TITLE
Frame from Half the video

### ISSUE THREAD

**Issue by mnek84** [PHP-FFMpeg/PHP-FFMpeg#143]
How can i get a frame picture from the half of the video?

**Comment by mnek84** [comment]
i found this alternative
	$video = $ffmpeg->open($filePath);	
	$streams = $video->getFFProbe()->streams($filePath);
	
	$duration = 0;
	foreach ($streams as $stream) {
		$codecT = $stream->get('codec_type');
		if ($codecT=="video"){
			$duration = $stream->get('duration');
		}		
	}


	$frame = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds($duration/2));

there is another way to do it?

**Comment by romainneutron** [comment]
It's the right way
