### ISSUE TITLE
Don't understand Format

### ISSUE THREAD

**Issue by CSI68** [PHP-FFMpeg/PHP-FFMpeg#144]
Hello,

I try to manipulate video file to test PHP-FFMpeg but when I try the demo script I obtain this error :

Fatal error: Class 'Format\Video\X264' not found in /var/www/clemweb/public_html/ffmpeg/index.php on line 19

My code:

require(dirname(__FILE__).'/vendor/autoload.php');

$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe',
));
//$video = $ffmpeg->open(dirname(__FILE__).'/tests/files/portrait.MOV');
$video = $ffmpeg->open(dirname(__FILE__).'/dexter.avi');
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(50, 40))
    ->synchronize();
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(250))
    ->save('frame.jpg');

$format = new Format\Video\X264();
$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage % transcoded";
});

$format
    -> setKiloBitrate(1000)
    -> setAudioChannels(2)
    -> setAudioKiloBitrate(256);

$video->save($format, 'video.avi');

Something seems to not be installed...

Thanks for your help

**Comment by nlegoff** [comment]
Hi, 

Try

```php
$format = new FFMPeg\Format\Video\X264();
```

**Comment by CSI68** [comment]
Hi,

Thanks for your response but same problem :
Fatal error: Class 'FFMPeg\Format\Video\X264' not found in /var/www/clemweb/public_html/ffmpeg/index.php on line 19

**Comment by nlegoff** [comment]
Yep sorry : 
```php
$format = new FFMpeg\Format\Video\X264();
```

**Comment by CSI68** [comment]
It's a bit better but :
Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-i' '/var/www/clemweb/public_html/ffmpeg/dexter.avi' '-async' '1' '-metadata:s:v:0' 'start_time=0' '-s' '50x40' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '256k' '-ac' '2' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes54ca312d7bcd63na03/pass-54ca312d7c0c1' 'video.avi'' in /var/www/clemweb/public_html/ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /var/www/clemweb/public_html/ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffmpe...') #1 /var/www/clemweb/public_html/ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.ph in /var/www/clemweb/public_html/ffmpeg/src/FFMpeg/Media/Video.php on line 168

Tx nlegoff

**Comment by nlegoff** [comment]
You will get more detail about the error that occurred in ffmpeg if you execute the generated command in your terminal! Maybe you dont have the proper codec installed on you system.

**Comment by ozzon91** [comment]
On Jan 29, 2015 3:11 PM, "Clément" <notifications@github.com> wrote:
>
> It's a bit better but :
> Fatal error: Uncaught exception
'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message
'ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-i'
'/var/www/clemweb/public_html/ffmpeg/dexter.avi' '-async' '1'
'-metadata:s0' 'start_time=0' '-s' '50x40' '-vcodec' 'libx264' '-acodec'
'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40'
'-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp'
'0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '256k' '-ac' '2' '-pass' '1'
'-passlogfile' '/tmp/ffmpeg-passes54ca312d7bcd63na03/pass-54ca312d7c0c1'
'video.avi'' in
/var/www/clemweb/public_html/ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100
Stack trace: #0
/var/www/clemweb/public_html/ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72
):
Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffmpe...')
#1
/var/www/clemweb/public_html/ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.ph
in /var/www/clemweb/public_html/ffmpeg/src/FFMpeg/Media/Video.php on line
168

**Comment by romainneutron** [comment]
try to run 

```
'/usr/bin/ffmpeg' '-y' '-i'
'/var/www/clemweb/public_html/ffmpeg/dexter.avi' '-async' '1'
'-metadata:s0' 'start_time=0' '-s' '50x40' '-vcodec' 'libx264' '-acodec'
'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40'
'-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp'
'0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '256k' '-ac' '2' '-pass' '1'
'-passlogfile' '/tmp/ffmpeg-passes54ca312d7bcd63na03/pass-54ca312d7c0c1'
'video.avi''
``` 

in your terminal

**Comment by CSI68** [comment]
Hi romainneutron,

I obtain this 

ffmpeg version 0.8.16-6:0.8.16-1, Copyright (c) 2000-2014 the Libav developers
  built on Sep 16 2014 23:10:48 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
[mpeg4 @ 0x1686e40] Invalid and inefficient vfw-avi packed B frames detected
Input #0, avi, from '/var/www/clemweb/public_html/ffmpeg/dexter.avi':
  Metadata:
    encoder         : MEncoder 1.0pre8-3.3.5
  Duration: 00:48:45.14, start: 0.000000, bitrate: 993 kb/s
    Stream #0.0: Video: mpeg4 (Advanced Simple Profile), yuv420p, 624x352 [PAR 1:1 DAR 39:22], 23.98 tbr, 25 tbn, 23.98 tbc
    Stream #0.1: Audio: mp3, 48000 Hz, stereo, s16, 128 kb/s
Unknown encoder 'libfaac'

It seems libfaac missing. How can I install it on my Debian ?

Thx

**Comment by romainneutron** [comment]
You should probably ask google
