### ISSUE TITLE
Is it possible to clip an audio

### ISSUE THREAD

**Issue by geofmureithi** [PHP-FFMpeg/PHP-FFMpeg#147]
To clip a video we do this;

```
 $video->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(0), FFMpeg\Coordinate\TimeCode::fromSeconds(30)); //0-30s
```

why can't we do it for an audio?

**Comment by patkar** [comment]
@acemureithi ffmpeg support exists?

**Comment by tvancleave** [comment]
Is there a way to clip audio? I know that you can clip audio files via ffmpeg through the command line, but I cannot seem to get it to work with the provided clip function.

**Comment by dubems** [comment]
@tvancleave please could u help with the command for audio cliping frm the command line. Thanks

**Comment by Romain** [comment]
If I'm right, the command to clip audio is `ffmpeg -ss 10 -t 6 -i input.mp3 output.mp3`.

You could try to use the video clip filter: 

```php
$video->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(30), FFMpeg\Coordinate\TimeCode::fromSeconds(15));
```

Let me know if it works for you.

**Comment by taylorvc** [comment]
@dubems You can clip audio via FFMpeg with the command @Romain stated:
`ffmpeg -ss 10 -t 6 -i input.mp3 output.mp3`
This will cut a 6 second file starting at 10 seconds in.

However, if you wish to trim the file without re-encoding it, use the command:
`ffmpeg -i input.mp3 -ss 10 -t 6 -acodec copy output.mp3`

I wasn't able to get the video clip filter to work with audio files, so I ended up creating a custom clip filter for audio. It looks very similar to the video clip filter, except it calls the audio class:

```
<?php

namespace FFMpeg\Filters\Audio;

use FFMpeg\Format\AudioInterface;
use FFMpeg\Media\Audio;
use FFMpeg\Coordinate\TimeCode;

class ClipFilter implements AudioFilterInterface
{
    /** @var TimeCode */
    private $start;
    /** @var TimeCode */
    private $duration;
    /** @var integer */
    private $priority;

    public function __construct(TimeCode $start, TimeCode $duration = null, $priority = 0)
    {
        $this->start = $start;
        $this->duration = $duration;
        $this->priority = $priority;
    }

    /**
     * {@inheritdoc}
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * @return TimeCode
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * @return TimeCode
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * {@inheritdoc}
     */
    public function apply(Audio $audio, AudioInterface $format)
    {
        $commands = array('-ss', (string) $this->start);

        if ($this->duration !== null) {
          $commands[] = '-t';
          $commands[] = (string) $this->duration;
        }

        $commands[] = '-acodec';
        $commands[] = 'copy';

        return $commands;
    }
}
```

**Comment by Romain** [comment]
Thanks for this work @taylorvc.
@swordsreversed pushed a PR #240 which does the same.
However your code adds 2 parameters which may be interesting.
