### ISSUE TITLE
Get duration with ffmpeg object

### ISSUE THREAD

**Issue by Metrakit** [PHP-FFMpeg/PHP-FFMpeg#149]
Hi!

It's possible to get directly the video duration after have created the object "ffmpeg" like that : "$ffmpeg->open('myVideoURL');" ?

I have tired "$ffmpeg->getDuration();" or "$ffmpeg->get('duration');" but it doesnt exist..

Thanks for your help.

**Comment by Ortix92** [comment]
It says how to do this **right** in the docs:
```php
$ffprobe = FFMpeg\FFProbe::create();
$ffprobe
    ->format('/path/to/video/mp4') // extracts file informations
    ->get('duration');             // returns the duration property
```
or a more fluent style:
```php
$ffmpeg = FFMpeg::create();
$ffmpeg->getFFProbe()
            ->format('yoururl')
            ->get('duration');
```

**Comment by Metrakit** [comment]
Yes thanks i found before
