### ISSUE TITLE
Save video clip as gif image

### ISSUE THREAD

**Issue by zang** [PHP-FFMpeg/PHP-FFMpeg#152]
what's the best way to save part of a video as gif? E.g. First 8 seconds

Thanks in advanced,
Lucy

**Comment by patkar** [comment]
@zang Is it supported in ffmpeg?

**Comment by kamov** [comment]
Seem that is supported in new version, see: http://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality

Does this library support?

Thanks!

**Comment by Romain** [comment]
This question has been duplicated in issue #217 with more details.
