### ISSUE TITLE
WAMP - "Unknown encoder libfaac" error

### ISSUE THREAD

**Issue by devendragohil** [PHP-FFMpeg/PHP-FFMpeg#156]
I have downloaded ffmpeg package from http://ffmpeg.zeranoe.com/builds for windows 64-bits and have set the ffmpeg.exe path in environment variables. Now, if I simply run the code to transcode the video : 
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open($video_path);
$format = new FFMpeg\Format\Video\X264();
$format->setKiloBitrate(1000)
        ->setAudioChannels(2)
        ->setAudioKiloBitrate(256);
$video->save($format, public_path().$path.$save_filename);

it gives error "Unknown encoder 'libfaac' " 
FFMpeg\\Exception\\RuntimeException
"Encoding failed"

Can you please let me know how to over come this?

**Comment by amontero** [comment]
May be you have the same problem as: https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/89

Anyway, have you tried this:
$format->setAudioCodec("libmp3lame");

**Comment by devendragohil** [comment]
I have the same problem but I cannot use libmp3lame as it is not producing audio in iOS devices. Please let me know how to solve this?

**Comment by samthomson** [comment]
Try any of the following: libvo_aacenc, libfaac, ~~libmp3lame~~, libfdk_aac

```php
$format ->setAudioCodec("libvo_aacenc");
```

**Comment by patkar** [comment]
Seems your version missing an encoder. Anyway, try the official ffmpeg version, not a fork or whatever Zeranoe is..

**Comment by jankal** [comment]
Related to: #222 #231 #137 #212 #165
