### ISSUE TITLE
Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffprobe failed to execute command '/usr/bin/ffprobe' '-help' '-loglevel' 'quiet''

### ISSUE THREAD

**Issue by mateusjatenee** [PHP-FFMpeg/PHP-FFMpeg#157]
Hi there,
I'm trying to run PHP-FFMpeg on a development server. Running it on my Mac is fine - I can't convert to mp4 files, but except that, everything works good. In the development server, I get the following error. FFMpeg and FFProbe are installed.

Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffprobe failed to execute command '/usr/bin/ffprobe' '-help' '-loglevel' 'quiet'' in /var/www/convertor/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /var/www/convertor/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffpro...') #1 /var/www/convertor/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #2 /var/www/convertor/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, NULL) #3 /var/www/convertor/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(61): Alchemy\BinaryDriver\AbstractBinary->command(Array) #4 in /var/www/convertor/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php on line 63 

I'm not sure what I should do - the server is running Ubuntu 10.04.4. PHP is running 5.3.2. Sorry for posting that here, but I've really tried fixing it...

Here's my file PHP file:

```php
<?php
$nome = $_POST['nome'];
$agora = date("dmY");
$video = $_FILES['file']['name'];
$uploaddir = "videos_nc/";
$c_dir = "videos_c/";
$jpg = ".jpg";
$tudo = $uploaddir . $agora . $video;
$tudo_c = $c_dir . $agora . $video;
$tudo_c_frame = $c_dir . $agora . $video.".jpg";

@move_uploaded_file($_FILES['file']['tmp_name'], $uploaddir. $agora. $_FILES['file']['name']);



include 'vendor/autoload.php';


$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe',
    'timeout'          => 0, // The timeout for the underlying process
    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
), @$logger);

$video = $ffmpeg->open("$tudo");
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
    ->save("$tudo_c_frame");
$video
    ->save(new FFMpeg\Format\Video\X264(), "$tudo_c.avi");
    echo 'sucesso';
    ?>
```

**Comment by mateusjatenee** [comment]
Found the problem running the commands on Terminal.
Thx

**Comment by xmoroccan** [comment]
@mateusjatenee can you give us solution please, because i run the command on terminal,  nothing wrong !

**Comment by luciddesignconcepts** [comment]
@mateusjatenee, What was the solution? I'm running it to the same issues.

**Comment by Vitassam** [comment]
It's "Unknown encoder 'libfaac'"

**Comment by xvrzhao** [comment]
Just closed issue with no solution , this is funny.

**Comment by jens1o** [comment]
@xvrzhao Most likely it is because of wrong permissions. :)

**Comment by joblesspoet** [comment]
> @xvrzhao Most likely it is because of wrong permissions. :)

can you please explain what kind of permission...?

**Comment by jens1o** [comment]
@joblesspoet Sorry for the late reply: The process executing the php-script needs to be able to (a) spawn new processes and (b) be able to read/write both the input and output directory.

In addition, please make sure that the output-file is not the same as the input-file. FFMpeg does not support overwriting the same file.
