### ISSUE TITLE
Frame capturing is not working

### ISSUE THREAD

**Issue by virendravyas** [PHP-FFMpeg/PHP-FFMpeg#161]
Hello Friends,

I have installed FFMpeg on /var/www location on my Centos 6 machine. I have also installed PHP-FFMpeg on the same location. 

Now I created a capture.php file in which I placed the code of capturing the frame from the video as described in the README.md.

I placed this capture.php and video.mp4 file in same /var/www/html folder and run the file but it's not generating any frame.

I have changed the binaries path in the file. I have also tried with placing this file on different location like put it in the folder of PHP-FFMpeg but it's not generating the frame.

It's also not displaying any error even my php error reporting is on.

Please help what should I do OR what I'm missing here?

Thanks in advance.

**Comment by patkar** [comment]
@virendravyas When reporting errors, always post your code and possible error messages please. The description of you is not reproducible.
