### ISSUE TITLE
ffmpeg failed to execute command

### ISSUE THREAD

**Issue by ivokun** [PHP-FFMpeg/PHP-FFMpeg#168]
Hi,

I got an error "ffmpeg failed to execute command" with

ffmpeg failed to execute command '/usr/share/nginx/html/converter/ffmpeg' '-y' '-i' '/usr/share/nginx/html/storage/app/phpjZyeuE.mp4' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '256k' '-ac' '2' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes55954b78452b05r9ah/pass-55954b7845449' '/usr/share/nginx/html/storage/app/phpjZyeuE.mp4'

How should i do ?

**Comment by samthomson** [comment]
run the command via the command line to get detailed error output on what the actual cause of the exception is, likely you are missing an encoding library (libfaac likely). Include your code next time ;)

**Comment by patkar** [comment]
@ivokun Still a problem?
