### ISSUE TITLE
FFProbe not working on Mac Although Installed

### ISSUE THREAD

**Issue by OElesin** [PHP-FFMpeg/PHP-FFMpeg#170]
Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutableNotFoundException' with message 'Executable not found, proposed : avprobe, ffprobe' in /Applications/XAMPP/xamppfiles/htdocs/video/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:160 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/video/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration)) #1 /Applications/XAMPP/xamppfiles/htdocs/video/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(207): FFMpeg\Driver\FFProbeDriver::create(Array, NULL) #2 /Applications/XAMPP/xamppfiles/htdocs/video/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(117): FFMpeg\FFProbe::create(Array, NULL, NULL) #3 /Applications/XAMPP/xamppfiles/htdocs/video/t.php(4): FFMpeg\FFMpeg::create() #4 {main} Next exception 'FFMpeg\Exception\ExecutableNotFoundException' with message 'Unable to load FFProbe' in /Applications/XAMPP/xamppfiles/ in /Applications/XAMPP/xamppfiles/htdocs/video/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php on line 50

**Comment by patkar** [comment]
"Duplicate" of #172 :)
