### ISSUE TITLE
Save metadata changes 

### ISSUE THREAD

**Issue by jerson** [PHP-FFMpeg/PHP-FFMpeg#175]
Hi, im new here, its posible update the metadata of an audio file, something like

``` php
    $ffmpeg = FFMpeg::create();
    $audio = $ffmpeg->open($file);
    $audio->getFormat()->set('title','my new title');
    $audio->save();

```

**Comment by robertkraig** [comment]
http://wiki.multimedia.cx/index.php?title=FFmpeg_Metadata might want to look up how it's done manually to do it via the library.
