### ISSUE TITLE
Unable to probe video

### ISSUE THREAD

**Issue by Lyberii** [PHP-FFMpeg/PHP-FFMpeg#176]
I'm using php-ffmpeg on windows with yii2, and encountered with a issue says “FFMpeg\Exception\RuntimeException

Unable to probe small.mp4
↵
Caused by: Alchemy\BinaryDriver\Exception\ExecutionFailureException

ffprobe failed to execute command "D:\Program Files\ffmpeg\bin\ffprobe.EXE" "small.mp4" "-show_streams" "-print_format" "json"

in E:\WebRoot\cloud\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php at line 100”

The code is identical with the demo in Readme, and i've tried different types of video. Yet no luck. 

Can anyone tell me what to do?

**Comment by warrickbayman** [comment]
I'm seeing this as well, but only with some videos. On Centos 7.

**Comment by Grimbode** [comment]
Having the same problem.

**Comment by patkar** [comment]
@Lyberii @warrickbayman @Grimbode Which error do you get on console, if you execute the command from the exception (without the quotes) directly on a command line?

**Comment by shyamsunderct** [comment]
Check the video file path. I too got the same error and problem is with the video file path.
