### ISSUE TITLE
ffmpeg and fpm 5.4 and nginx

### ISSUE THREAD

**Issue by anasri** [PHP-FFMpeg/PHP-FFMpeg#179]
Hi 
I got this error while compile ffmpeg 
[root@server ffmpeg-php]# make
/bin/sh /usr/src/ffmpeg-php/libtool --mode=compile cc  -I. -I/usr/src/ffmpeg-php -DPHP_ATOM_INC -I/usr/src/ffmpeg-php/include -I/usr/src/ffmpeg-php/main -I/usr/src/ffmpeg-php -I/usr/local/php54/include/php -I/usr/local/php54/include/php/main -I/usr/local/php54/include/php/TSRM -I/usr/local/php54/include/php/Zend -I/usr/local/php54/include/php/ext -I/usr/local/php54/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/src/ffmpeg-php/ffmpeg_movie.c -o ffmpeg_movie.lo
 cc -I. -I/usr/src/ffmpeg-php -DPHP_ATOM_INC -I/usr/src/ffmpeg-php/include -I/usr/src/ffmpeg-php/main -I/usr/src/ffmpeg-php -I/usr/local/php54/include/php -I/usr/local/php54/include/php/main -I/usr/local/php54/include/php/TSRM -I/usr/local/php54/include/php/Zend -I/usr/local/php54/include/php/ext -I/usr/local/php54/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/src/ffmpeg-php/ffmpeg_movie.c  -fPIC -DPIC -o .libs/ffmpeg_movie.o
/usr/src/ffmpeg-php/ffmpeg_movie.c:42:32: error: libavcodec/version.h: No such file or directory
/usr/src/ffmpeg-php/ffmpeg_movie.c:76:1: warning: "MAX_STREAMS" redefined
In file included from /usr/src/ffmpeg-php/ffmpeg_movie.c:43:
/usr/include/libavformat/avformat.h:569:1: warning: this is the location of the previous definition
/usr/src/ffmpeg-php/ffmpeg_movie.c: In function ‘php_get_dict_value’:
/usr/src/ffmpeg-php/ffmpeg_movie.c:509: error: ‘AVDictionaryEntry’ undeclared (first use in this function)
/usr/src/ffmpeg-php/ffmpeg_movie.c:509: error: (Each undeclared identifier is reported only once
/usr/src/ffmpeg-php/ffmpeg_movie.c:509: error: for each function it appears in.)
/usr/src/ffmpeg-php/ffmpeg_movie.c:509: error: ‘m_entry’ undeclared (first use in this function)
/usr/src/ffmpeg-php/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getPixelFormat’:
/usr/src/ffmpeg-php/ffmpeg_movie.c:828: warning: assignment makes pointer from integer without a cast
make: *** [ffmpeg_movie.lo] Error 1
[root@server ffmpeg-php]#

i also did the following instructure :-1: 

http://stackoverflow.com/questions/20055252/make-ffmpeg-movie-lo-error-1-when-compiling-ffmpeg-php/32717880#32717880

**Comment by anasri** [comment]
[root@server ffmpeg-php]# make
/bin/sh /usr/src/ffmpeg-php/libtool --mode=compile cc  -I. -I/usr/src/ffmpeg-php -DPHP_ATOM_INC -I/usr/src/ffmpeg-php/include -I/usr/src/ffmpeg-php/main -I/usr/src/ffmpeg-php -I/usr/local/php54/include/php -I/usr/local/php54/include/php/main -I/usr/local/php54/include/php/TSRM -I/usr/local/php54/include/php/Zend -I/usr/local/php54/include/php/ext -I/usr/local/php54/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/src/ffmpeg-php/ffmpeg_movie.c -o ffmpeg_movie.lo
 cc -I. -I/usr/src/ffmpeg-php -DPHP_ATOM_INC -I/usr/src/ffmpeg-php/include -I/usr/src/ffmpeg-php/main -I/usr/src/ffmpeg-php -I/usr/local/php54/include/php -I/usr/local/php54/include/php/main -I/usr/local/php54/include/php/TSRM -I/usr/local/php54/include/php/Zend -I/usr/local/php54/include/php/ext -I/usr/local/php54/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/src/ffmpeg-php/ffmpeg_movie.c  -fPIC -DPIC -o .libs/ffmpeg_movie.o
/usr/src/ffmpeg-php/ffmpeg_movie.c:42:32: error: libavcodec/version.h: No such file or directory
/usr/src/ffmpeg-php/ffmpeg_movie.c:76:1: warning: "MAX_STREAMS" redefined
In file included from /usr/src/ffmpeg-php/ffmpeg_movie.c:43:
/usr/include/libavformat/avformat.h:569:1: warning: this is the location of the previous definition
/usr/src/ffmpeg-php/ffmpeg_movie.c: In function ‘php_get_dict_value’:
/usr/src/ffmpeg-php/ffmpeg_movie.c:509: error: ‘AVDictionaryEntry’ undeclared (first use in this function)
/usr/src/ffmpeg-php/ffmpeg_movie.c:509: error: (Each undeclared identifier is reported only once
/usr/src/ffmpeg-php/ffmpeg_movie.c:509: error: for each function it appears in.)
/usr/src/ffmpeg-php/ffmpeg_movie.c:509: error: ‘m_entry’ undeclared (first use in this function)
/usr/src/ffmpeg-php/ffmpeg_movie.c: In function ‘zim_ffmpeg_movie_getPixelFormat’:
/usr/src/ffmpeg-php/ffmpeg_movie.c:828: warning: assignment makes pointer from integer without a cast
make: *** [ffmpeg_movie.lo] Error 1

**Comment by patkar** [comment]
The ffmpeg-php extension has nothing to do with this library and the extension seems btw EOL
