### ISSUE TITLE
progressbar sample

### ISSUE THREAD

**Issue by tuxado** [PHP-FFMpeg/PHP-FFMpeg#180]
Hi'

I need plz a sample of transcoding video items stored on database with progressbar and store the proegressiion on database for every items because the docs of the api thas not clear... 

Tkx

**Comment by ivan0013** [comment]
Same here. I would need some tips to get the conversion percentage via $ajax.

Thank you very much!

**Comment by tuxado** [comment]
Hi 
I Test this lib the progress fonction it is not verry great precision 

$dbmanager // variable of tout database
$item // item stores un tour data base

$format = new Format\Video\X264();
$format->on('progress', function ($video, $format, $percentage) use ($dbmanager, $item) {
    $dbmanager->update(($item->setprorgress($progress)));
});

$format
    -> setKiloBitrate(1000)
    -> setAudioChannels(2)
    -> setAudioKiloBitrate(256);

$video->save($format, 'video.avi');

And you use Ajax to retrieve the item by id and return thé progress value 

note that thé lib is not asynch and thé progress value at many time stop at 50%

**Comment by ivan0013** [comment]
Thanks. This is a very useful info. I haven't thought about the possibility of storing the % on the DB and then read it.

**Comment by tuxado** [comment]
I forget you need to force the progress at 100 % like this change the last line like this :p

If  ($video->save($format, 'video.avi'))
{
$dbmanager->update(($item->setprorgress(100)));
}

**Comment by patkar** [comment]
If you have generel questions about the usage which is not a bug, please ask them on http://stackoverflow.com/questions/tagged/php-ffmpeg
