### ISSUE TITLE
Working offline but not on server.

### ISSUE THREAD

**Issue by hitswa** [PHP-FFMpeg/PHP-FFMpeg#181]
Its working offline very smoothly. But when i tried to do this on my server its showing an alert saying "Request failed!". In chrome console I am getting following response.

"jquery-latest.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/."
at jquery-latest.min.js:4

Autoloaded parameters it is taking are as following:

-acodec libvo_aacenc -ac 2 -ab 128 -ar 22050 -s 1024x768 -vcodec libx264 -fpre "/home/cinqdfl8/public_html/ffmpeg/ffmpeg\presets\libx264-ipod640.ffpreset" -b 1200k -f mp4 -threads 0

**Comment by patkar** [comment]
@hitswa The chrome console has nothing to do with a php error. Please be specific about your error. Do you get any messages in the web servers error log?
