### ISSUE TITLE
Is it possible to create m3u8 playlists?

### ISSUE THREAD

**Issue by citosid** [PHP-FFMpeg/PHP-FFMpeg#183]
I need to create an m3u8 playlist, is possible do it with this?

**Comment by patkar** [comment]
@citosid Is it possible with ffmpeg? If yes, tell us how please? If not, no. But IMHO a m3u playlist is a simple text file, thus I don't understand why you would need a library or ffmpeg?

**Comment by citosid** [comment]
@patkar with ffmpeg is possible by doing something like:

```
ffmpeg -i file.mp4 output.m3u8
```

I don't remember why I wanted to create the M3U8 with PHP and this library... the question was 4 months ago... but either way, we decided to go with Python instead of PHP (for the specific things in ffmpeg).

Thank you for your reply.
