### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by sheikhasadmuneer** [PHP-FFMpeg/PHP-FFMpeg#185]
i'm getting below error .

Fatal error: Class 'FFMpeg\FFMpeg' not found in C:\xampp\htdocs\last\index.php on line 5

Here's the code i'm trying to run

<?php
 

 
  $FFMpeg = FFMpeg\FFMpeg::create( [
            'ffmpeg.binaries'  => 'C:/xampp/htdocs/last/FFMpeg/bin/ffmpeg.exe',
    	    'ffprobe.binaries' => 'C:/xampp/htdocs/last/FFMpeg/bin/ffplay.exe',
            'timeout'          => 3600, // the timeout for the underlying process
            'ffmpeg.threads'   => 12,   // the number of threads that FFMpeg should use
        ]);
 
?>

Can someone help resolving this , Thanks :)

**Comment by sheikhasadmuneer** [comment]
figured out the probem !! lol

**Comment by Vjack7** [comment]
Could you tell me how to solve it,thanks
