### ISSUE TITLE
FFMpeg install on laravel

### ISSUE THREAD

**Issue by chyupa** [PHP-FFMpeg/PHP-FFMpeg#187]
Hi,

I tried installing ffmpeg on laravel and I have an error:
Call to undefined method FFMpeg\FFMpegServiceProvider::isDeferred()

The package was installed through composer.

Kindly advise.
Thanks!

**Comment by chyupa** [comment]
Hi,

I fixed this.
The error comes when you try and autoload the service provider, but if you use as standalone it works.

Regards!

**Comment by David199719** [comment]
https://packagist.org/packages/php-ffmpeg/php-ffmpeg
