### ISSUE TITLE
Cut a video 

### ISSUE THREAD

**Issue by sheikhasadmuneer** [PHP-FFMpeg/PHP-FFMpeg#189]
what is the equivalent method of this ffmpeg cmd command ? 
it cuts input.mp4 from 0-5 seconds and gives an output video named (output.mp4)
ffmpeg -ss 0  -t  5  -i  'input.mp4' output.mp4

Thanks

**Comment by edianogama** [comment]
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('input.mp4');

$video->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(0), FFMpeg\Coordinate\TimeCode::fromSeconds(5));

$video->save(new FFMpeg\Format\Video\WebM(), 'output.mp4');

**Comment by patkar** [comment]
@sheikhasadmuneer Is it solved?

**Comment by sheikhasadmuneer** [comment]
@patkar  : Yes , but now i am not using FFMPEG via PHP CLASS , installed ffmpeg build on my ubuntu server . works perfect !

**Comment by patkar** [comment]
Btw, it's a whole library not only a class :wink:
