### ISSUE TITLE
Image Extraction from external file ? 

### ISSUE THREAD

**Issue by sheikhasadmuneer** [PHP-FFMpeg/PHP-FFMpeg#190]
i wan to know is it possible to extraction frames (per second ) of external video file ?

e.g:

https://www.havenondemand.com/sample-content/videos/hpnext.mp4

**Comment by patkar** [comment]
You should be able to pass all [supported protocols by ffmpeg](https://www.ffmpeg.org/ffmpeg-protocols.html) to the `open()` method.
