### ISSUE TITLE
Class 'FFMpeg\FFMpeg' not found

### ISSUE THREAD

**Issue by saulporras** [PHP-FFMpeg/PHP-FFMpeg#194]
So I am completly new to this composer thing I already installed the composer and installed ffmpeg using composer. 

What can I do to fix this problem:

"Fatal error: Class 'FFMpeg\FFMpeg' not found "

this is the only line I added so far to my code:

"$ffmpeg = FFMpeg\FFMpeg::create();"

Thanks.

**Comment by saulporras** [comment]
like I said, 

I am new to composer so all I had to do after installations was adding this line:

require __DIR__ . '/vendor/autoload.php';

**Comment by adnnor** [comment]
I am also facing this error. File is missing vendor/autoload.php

**Comment by TheLuckyOne** [comment]
And don't miss:
`use FFMpeg; `

**Comment by romainneutron** [comment]
Please check composer https://getcomposer.org/
