### ISSUE TITLE
API link is returning 404

### ISSUE THREAD

**Issue by vibhavsinha** [PHP-FFMpeg/PHP-FFMpeg#203]
The API link in README.md is returning 404 on the readthedocs website.

**Comment by romainneutron** [comment]
Please give me the link, I don't know what you're talking about

**Comment by vibhavsinha** [comment]
Line 410 of ./README.md 
Link is http://readthedocs.org/docs/ffmpeg-php/en/latest/_static/API/

Browse the [API](http://readthedocs.org/docs/ffmpeg-php/en/latest/_static/API/)

**Comment by vibhavsinha** [comment]
@romainneutron Please re-open this issue. Should I create a new issue?

**Comment by patkar** [comment]
@vibhavsinha Now covered within #208
