### ISSUE TITLE
Passing extra parameters not working.

### ISSUE THREAD

**Issue by thenutz** [PHP-FFMpeg/PHP-FFMpeg#211]
I'm trying to pass these two parameters to ffmpeg command: `-map_metadata -1`  and `-movflags faststart` .
I have added this function to x264 format
`public function getExtraParams()
    {
        return array('-map_metadata -1', '-movflags faststart');
    }`

When i tryed to execute i get the following error

`PHP Fatal error:  Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffmpeg failed to execute command '/var/www/clients/client1/domain.ro/web/ffmpeg/ffmpeg' '-y' '-i' '/var/www/clients/client1/domain.ro/web/tmp_files/5da52001ce905a93bd7ebfc6bb757df7.mp4' '-map_metadata -1' '-movflags faststart' '-threads' '8' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes56f1723276fc8pk7fh/pass-56f172327703c' '/var/www/clients/client1/domain.ro/web/uploads/video/Bp6b/Bp6b.mp4'' in /var/www/clients/client1/web2/web/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100
Stack trace:
#0 /var/www/clients/client1/web2/web/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/var/www/cl in /var/www/clients/client1/web2/web/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php on line 168
Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffmpeg failed to execute command '/var/www/clients/client1/domain.ro/web/ffmpeg/ffmpeg' '-y' '-i' '/var/www/clients/client1/domain.ro/web/tmp_files/5da52001ce905a93bd7ebfc6bb757df7.mp4' '-map_metadata -1' '-movflags faststart' '-threads' '8' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes56f1723276fc8pk7fh/pass-56f172327703c' '/var/www/clients/client1/domain.ro/web/uploads/video/Bp6b/Bp6b.mp4'' in /var/www/clients/client1/web2/web/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100
Stack trace:
#0 /var/www/clients/client1/web2/web/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/var/www/cl in /var/www/clients/client1/web2/web/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php on line 168`

So i have extracted the ffmpeg command from here and i run in manually without success. 
I have tryed to remove some parameter from that command. When o remove this `**-passlogfile /tmp/ffmpeg-passes56f16f34b815381cah/pass-56f16f34b81c3**` everything seems to work.
Could someone explain why this error ?
Whithout getExtraParams() everything works perfect but i need thsese two parameters

**Comment by patkar** [comment]
Please reformat/recreate your issue with our provided issue template and don't simple delete it and use proper code formatting (fenced code blocks for the error) and show more of your code changes.
