### ISSUE TITLE
Watermark filter documentation

### ISSUE THREAD

**Issue by seblavoie** [PHP-FFMpeg/PHP-FFMpeg#216]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.6.1
| FFmpeg Version | FFmpeg
| OS             | OS X 10.11.4

I just had a hard time getting to understand how the watermark filter worked. I did get it to work, but was wondering if there was a reason it wasn't in the documentation. I think it would make sense in the [filter section](https://github.com/PHP-FFMpeg/PHP-FFMpeg#filters) of the readme. I could throw in the PR if you want. What do you think?

**Comment by quentint** [comment]
Hi, I'm trying to use the watermark filter but can't make it work. Any help would be appreciated!

**Comment by seblavoie** [comment]
Hi, here’s basically the function I ended up using:

```
  public function compress() {
    $ffmpeg = \FFMpeg\FFMpeg::create([
      'ffmpeg.binaries' => '/usr/local/bin/ffmpeg',
      'ffprobe.binaries' => '/usr/local/bin/ffprobe',
    ]);

    $video = $ffmpeg->open("path/to/video.mov");

    $video
      ->filters()
      ->resize(new \FFMpeg\Coordinate\Dimension(640, 360))
      ->watermark('path/to/watermark.png', [
        'position' => 'relative',
        'bottom' => 50,
        'right' => 50,
      ])
      ->synchronize();
    $video
      ->save(new \FFMpeg\Format\Video\X264(), "path/to/watermarked-video.mp4");
  }
```

There are a couple of ways you can position the watermark. The `relative` allows you to position as you would with a `position: absolute` in CSS. 

You can find the method handling the watermark here https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Filters/Video/WatermarkFilter.php#L49. It’s not too daunting, but I still think the documentation should cover that without needing to point users to the code. I’ll try and draft some pull request when I’ll get a couple of minutes.

**Comment by quentint** [comment]
Hey, thanks very much!
I just realized my code was breaking because of the way Windows handles files paths.

I was using something like this: `D:/path/to/file.png`, where I had to use` /path/to/file.png`
All good now!

**Comment by seblavoie** [comment]
Glad it helped! I drafted a pull request for the maintainer to merge when he or she is ready:  https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/221

**Comment by huemane** [comment]
Thank You seblavoie!
Ive been pulling my hair out over " the way Windows handles files paths."
Finally got round it by simply removing the "C:"
Who would have known, no error messages gave any insight to this!
