### ISSUE TITLE
Advanced Filters

### ISSUE THREAD

**Issue by illmatic** [PHP-FFMpeg/PHP-FFMpeg#219]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Version Used | 0.6.1 |
| FFmpeg Version | 20160326-git-8ff0f6a |
| OS | Your OS and version |

I'm looking to convert this command using your library. Is it possible given the filters I'm using don't exist?
ffmpeg -i C:\Users\abc123\Desktop\after.mp4 -vf select='gt(scene\,0.25)',scale=225:150,tile=2x2:nb_frames=4 -frames:v 1 preview.png

**Comment by Romain** [comment]
Hi @illmatic,
Could you be more specific on what this command does?
Thanks
Romain

**Comment by illmatic** [comment]
This particular command takes a video then does the following actions

- starting after the .25 second mark
- scales the video down to width x heigh spec
- creates a 2x2 thumbnail preview
- stops after the 4th frame
- creates 1 files called preview.png

**Comment by Romain** [comment]
Hi @illmatic,

Have you tried breaking down the request into a succession of actions, like below?

```php
$ffmpeg = \FFMpeg\FFMpeg::create();

// Open your video
$video = $ffmpeg->open('/path/to/video');

// Resize it and crop it
$video
        ->filters()
        ->resize(new FFMpeg\Coordinate\Dimension(225, 150), 'inset')
        ->crop(new FFMpeg\Coordinate\Point(37, 0), new FFMpeg\Coordinate\Dimension(150, 150))
        ->synchronize();


// You need here to define which frame you want to get. 
// This strings is composed as follows: 'days:hours:minutes:seconds.frames'. 
// If I understand your request correctly, you want to add 4 frames to a quarter of second. Lets consider that a second contains 24 frames, this is worth 6 frames + 4 which makes 10 frames.
$frame = $video->frame(FFMpeg\Coordinate\TimeCode::fromString( '0:0:0:0.10' )); 
$frame->save( '/path/to/preview.png' );
```

Let me know if this works for you. I haven't tried it, but I think it may look like what you're looking for.

Romain

**Comment by Romain** [comment]
Hi @illmatic,
Have you managed to try the code I sent to you?
Is this issue still valid?

**Comment by illmatic** [comment]
Hi Romain,

Sorry, I haven't had a chance. Since my initial request I just run a shell
command directly to ffmpeg.

**Comment by Romain** [comment]
Ok, I'll just close this issue then.
If at some point you can try this code, and think it's not relevant, just reopen it.
