### ISSUE TITLE
Multiple Frame Creation

### ISSUE THREAD

**Issue by esuveyke** [PHP-FFMpeg/PHP-FFMpeg#220]
Whats the process of automating extracting multiple frames?

i only see this option through use of time code
$video->frame(\FFMpeg\Coordinate\TimeCode::fromSeconds(10))->save('frame-10.jpg');

**Comment by patkar** [comment]
What do you exactly mean with "automating extracting multiple frames"?

**Comment by abdullahtekin** [comment]
I mean every seconds extract frames
`exec('/usr/local/bin/ffmpeg -i "video.mp4" -vf fps=1/60 capture/img%03d.jpg');`
