### ISSUE TITLE
Unable to save frame

### ISSUE THREAD

**Issue by Edvardas-idea** [PHP-FFMpeg/PHP-FFMpeg#223]
I'm trying to save Frame as .png image, but have an error all the time 
[Error] Uncaught FFMpeg\Exception\RuntimeException: Unable to save frame.

Maybe server configurations are wrong ? i check everything i could be everything seems to work fine. btw, .jpg images saves fine.

**Comment by patkar** [comment]
Do you have a complete stack trace?

P.S.: Please don't delete the provided issue templat by GitHub. Please fill those fields out.

**Comment by Edvardas-idea** [comment]
no, i only have the line at which it brakes vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Frame.php:119

**Comment by patkar** [comment]
Please install the xdebug extension, so your error should print a complete stack trace

**Comment by lumilo8** [comment]
Hi, i have the same error, here is the trace:

![screenshot from 2016-06-15 14 47 58](https://cloud.githubusercontent.com/assets/3762301/16080317/7de687c8-3308-11e6-8c00-d457d33a8ae3.png)

Thanks!

**Comment by lumilo8** [comment]
I've found the problem, the destination folder had not permissions for www-data user

**Comment by Romain** [comment]
This issue should be closed, no?
