### ISSUE TITLE
 Pad filter for ffmpeg

### ISSUE THREAD

**Issue by jojotjebaby** [PHP-FFMpeg/PHP-FFMpeg#227]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Version Used | Specific tag or commit sha |
| FFmpeg Version | FFmpeg or AVConv and version |
| OS | Your OS and version |
#### Actual Behavior

How does PHP-FFMpeg behave at the moment?
#### Expected Behavior

First of all, thanx for this librarie ! Is it possible to implement the padding feature of ffmpeg? So that all the videos can have the same size( height and width) no matter what size they had in the beginning. I know it is possible to do it with ffmpeg but I did not find the feature in this library.

Any one that can help me out? Thanx !

**Comment by schmanat** [comment]
Could you post the ffmpeg command to do that? I think so its easier to realize your feature.

**Comment by jojotjebaby** [comment]
I use this little bit to scale down the size of my video. For exemple to downscale a video to 405:320 and add the black bars to the top and bottom or left and right.

`-vf "scale=iw*min(405/iw\,320/ih):ih*min(405/iw\,320/ih),pad=405:320:(405-iw)/2:(320-ih)/2"
`
### you defined the max width and max height in your original question
```
max_width     = 405
max_height    = 320
```

### first, scale the image to fit along one dimension
```
scale         = min(max_width/input_width, max_height/input_height)
scaled_width  = input_width  * scale
scaled_height = input_height * scale
```

### then, position the image on the padded background
```
padding_ofs_x = (max_width  - input_width) / 2
padding_ofs_y = (max_height - input_height) / 2
```

The target height and width are given by the user. I think this would be pretty helpful to implement it. I will look if I can make it work.

Source: [ffmpeg on Stackoverflow](http://stackoverflow.com/questions/8133242/ffmpeg-resize-down-larger-video-to-fit-desired-size-and-add-padding)

**Comment by schmanat** [comment]
+1
