### ISSUE TITLE
Using the package with Laravel 5.1

### ISSUE THREAD

**Issue by bkkrishna** [PHP-FFMpeg/PHP-FFMpeg#228]
Hello there, 

Can I get some help on using this package with Laravel 5.1 ? 

I **composer** **require**d the package but could not use it as I couldn't actually add it to config/app.php in the list of providers.

Any help would be much appreciated.

Thank you in advance.

**Comment by patkar** [comment]
This is a simple library and not a finished Laravel provider. Thus it's clear you can't add it to the `config/app.php` :smirk: 

Simply `FFMpeg` class directly in your code/controller/services as described in the readme.
