### ISSUE TITLE
Does this plugin support encoding output to hls files?

### ISSUE THREAD

**Issue by skajg** [PHP-FFMpeg/PHP-FFMpeg#230]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Version Used | Specific tag or commit sha |
| FFmpeg Version | FFmpeg or AVConv and version |
| OS | Your OS and version |

Does this plugin support encoding output to hls files?

**Comment by ceefour** [comment]
See also #367.

**Comment by jens1o** [comment]
closing as duplicate.
