### ISSUE TITLE
Question :  Audio waveform

### ISSUE THREAD

**Issue by sm2017** [PHP-FFMpeg/PHP-FFMpeg#238]
How can I create audio waveform by PHP-FFMpeg?
https://trac.ffmpeg.org/wiki/Waveform

**Comment by Romain** [comment]
As far as I know, you won't be able to do it using this library.
I think this should be a feature request.

**Comment by Romain** [comment]
@sm2017, I just created a pull request: #253

**Comment by jamesgraham** [comment]
@Romain did you find any interim solution? Are you trying to generate png or svg, or even json?

**Comment by Romain** [comment]
Hi @jamesgraham,
I'm waiting for the PR to be approved.
For now, I've got no answer from @romainneutron or @patkar.
The method generates a PNG.

**Comment by Romain** [comment]
This PR has been merged.
I close this issue.
