### ISSUE TITLE
Question :  Random frame

### ISSUE THREAD

**Issue by sm2017** [PHP-FFMpeg/PHP-FFMpeg#239]
How can I get random frame of Video? and resize only this frame and save as thumbnail?

**Comment by David-Crty** [comment]
Checking this part of documentation may help you ?
https://github.com/PHP-FFMpeg/PHP-FFMpeg#extracting-image

**Comment by Romain** [comment]
@sm2017, what I would do is:
- get the length of the video in seconds
- pick a random integer between 1 and the length of your video
- extract an image as pointed out by @David-Crty 
- resize the image using an image library.

**Comment by Romain** [comment]
Hi @sm2017 ,
Have you tried what I recommended to you?
Is this question still valid or could I close it?

**Comment by sm2017** [comment]
Ok , thanks
