### ISSUE TITLE
How to setPasses to One

### ISSUE THREAD

**Issue by xmon** [PHP-FFMpeg/PHP-FFMpeg#243]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Version Used | 0.6.1 |
| FFmpeg Version | 2.7.2 |
| OS | Debian 4.9.2-10 |
#### Actual Behavior

PHP-FFMpeg always set Pass 2, "-pass" "2" and some x264 videos break the conversion
#### Expected Behavior

I need set pass in One.

Any idea to solve it?

**Comment by xmon** [comment]
Thanks @Laurent3170 but the question is, how can I modify the passes using PHP-FFMpeg?

The 2 passes are hardcoded in [this library](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/a1e12ecf3300badc9337f2986ea5ab000a7db6e3/src/FFMpeg/Format/Video/X264.php#L68-L71 ).

**Comment by Laurent3170** [comment]
I don't have the ambition to try to answer to your question as I don't have this knowledge. I was just asking if the "-pass" is the reason why the file is written twice, as I've asked in issue #242, if you have this answer.

**Comment by matrunchyk** [comment]
@xmon It's always better to ask not on the Issue tracker, but somewhere like StackOverflow.
You can easily create your own class and specify as many passes as you want:

```
use FFMpeg\Format\Video\x264;

class myX264 extends x264 {
    public function getPasses()
    {
        return 1;
    }
}
```

**Comment by Romain** [comment]
Hi all,
I've created a pull request to allow users to do it programmatically: #251 
I think this answers the question.

**Comment by Romain** [comment]
This PR has been merged.
I close this issue.
