### ISSUE TITLE
How to use this library? I can't make it work

### ISSUE THREAD

**Issue by h3242749** [PHP-FFMpeg/PHP-FFMpeg#246]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Centos 6.8

Sorry, I'm newbie. I don't know how to use this class, I can't make it works. Please help me at initial state!

Folder Structure:
+ FFMpeg (folder in src with sub folders and classes)
+ testTranscode.php

<?
namespace FFMpeg; 
require_once("FFMpeg/FFMpeg.php");
require_once("FFMpeg/FFProbe.php");
use FFMpeg\Coordinate\Dimension;
use FFMpeg\Filters\Video\ResizeFilter;
use FFMpeg\Filters\Video\RotateFilter;
use FFMpeg\Format\Video\X264;
use FFMpeg\Media\Video;
	
		$ffmpeg = FFMpeg::create();
		$video = $ffmpeg->open('bunny.mp4');
		$video
			->filters()
			->resize(new FFMpeg\Coordinate\Dimension(320, 240))
			->synchronize();
		$video
			->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
			->save('frame.jpg');
		$video
			->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4')
			->save(new FFMpeg\Format\Video\WebM(), 'export-webm.webm');
?>

It throw error:
Fatal error: Class 'Doctrine\Common\Cache\ArrayCache' not found in /myPath/FFMpeg/FFProbe.php on line 204

If I try wrap initial code in extends class and call it in another PHP file, it throw the error:
Catchable fatal error: Argument 1 passed to FFMpeg\FFProbe::__construct() must be an instance of FFMpeg\Driver\FFProbeDriver, none given, called in /myPath/transcode_test.php on line 8 and defined in /myPath/FFMpeg/FFProbe.php on line 47

 How to solve it? Can you please give me a clean instruction?

**Comment by Mika2413** [comment]
Did you install it using composer?
If no, you should install it with composer to get all dependencies. I think it will solve the problem

**Comment by h3242749** [comment]
Thank you. I tried with your suggestion and no longer receive error about Doctrine anymore. However, I still can not make it work.

When I use: "use FFMpeg;" it always throw class not found. So I back to require_once("FFMpeg/FFMpeg.php"); and then it keep throwing a lot of not found class: FFProbeDriver then OptionsTester'  .... is there any sample or anyway to quick connect and test?

If I try with class and extends, it throw the same as above: Catchable fatal error: Argument 1 passed to FFMpeg\FFMpeg .....

**Comment by patkar** [comment]
Please simply read the readme: https://github.com/PHP-FFMpeg/PHP-FFMpeg#basic-usage
