### ISSUE TITLE
Extract Audio from a video and save it seperatly.

### ISSUE THREAD

**Issue by jens1o** [PHP-FFMpeg/PHP-FFMpeg#252]
Just a question: Is it possible through your driver to extract the audio from a video? I didn't found anything. But other drivers support this(i.e. the driver for nodejs).

Or did I overseen anything?

**Comment by Romain** [comment]
Hi @jens1o,
Have you tried something like this?

```
$ffmpeg = FFMpeg\FFMpeg::create([
        'ffmpeg.binaries'  => '/path/to/binaries', // the path to the FFMpeg binary
        'ffprobe.binaries' => '/path/to/ffprobe/binaries', // the path to the FFProbe binary
        'timeout' => 3600, // the timeout for the underlying process
        'ffmpeg.threads'   => 1,   // the number of threads that FFMpeg should use
], $logger);

// Open the video
$video = $ffmpeg->open( $full_video_path );

// Set the formats
$output_format = new FFMpeg\Format\Audio\Mp3(); // Here you choose your output format
$output_format->setAudioCodec("libmp3lame");

$video->save($output_format, '/path/to/output/file');
```

I haven't tried it, but my guess is that it may be a solution.
Let me know.

**Comment by jens1o** [comment]
Oh. I'd overseen it. I'll try when I have some time. But thanks! ;)

**Comment by Romain** [comment]
You're welcome.
Let me know if it works for you.

**Comment by jens1o** [comment]
Great! It works! Thanks! :smile:

**Comment by Romain** [comment]
You're welcome, glad it works. ;)

**Comment by nvtiencom** [comment]
Hello,

Can we extract video (no sound) from original video (has sound) files? and how?
Please help, thanks

**Comment by Romain** [comment]
Hi @nvtiencom,
If I'm right, FFMPEG allows you to encode a video with no sound, using the -an option (see [this post](http://superuser.com/questions/268985/remove-audio-from-video-file-with-ffmpeg)).
However, this bundle has no feature implemented which would let you add this to the request.
I think this should be a feature request.
If I have any chance to work on this anytime soon, I'll let you know.
