### ISSUE TITLE
Can't convert gif to webm, but mp4 works fine

### ISSUE THREAD

**Issue by travoliti** [PHP-FFMpeg/PHP-FFMpeg#254]
| Q              | A
| -------------- | ---
| Bug?           | No
| New Feature?   | No
| Version Used   | 0.6.1
| FFmpeg Version | FFmpeg 3.2
| OS             | ubuntu 14.04

So I'm trying to convert a `.gif` to both a `.mp4` and `.webm`. It converts the gif to mp4 fine, but I get an `"Encoding failed"` error when it converts to webm.

Here is the command I used:

> ffmpeg -y -i /tmp/giphy.gif -f webm -vcodec libvpx -acodec libvorbis -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k /tmp/webm.webm

Here is the output I got:

> ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvidstab --enable-libwavpack --enable-nvenc
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, gif, from '/tmp/giphy.gif':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: gif, bgra, 400x400, 10 fps, 10 tbr, 100 tbn, 100 tbc
[libvpx @ 0x257b1e0] v1.5.0
**[libvpx @ 0x257b1e0] Transparency encoding with auto_alt_ref does not work**
Stream mapping:
  Stream #0:0 -> #0:0 (gif (native) -> vp8 (libvpx))
**Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height**

The two errors being:

> [libvpx @ 0x257b1e0] Transparency encoding with auto_alt_ref does not work

And:

> Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`

So what am I doing wrong that's causing it to fail when converting it to webm?

**Comment by Romain** [comment]
Hi @travoliti,
Have you tried to use the MP4 created to generate the webm?
This could be a workaround...
Romain

**Comment by travoliti** [comment]
@Romain 

That worked, but it still seems odd to have to load the mp4 just to save as webm, as I do like this:

```
$ffmpeg = \FFMpeg\FFMpeg::create();

$video = $ffmpeg->open('/tmp/giphy.gif');
$video
    ->save(new \FFMpeg\Format\Video\X264(), '/tmp/mp4.mp4');

$video = $ffmpeg->open('/tmp/mp4.mp4');
$video
    ->save(new \FFMpeg\Format\Video\WebM(), '/tmp/webm.webm');
```

**Comment by Romain** [comment]
@travoliti, I agree.
As I said, this is a workaround.
I've no clue why this doesn't work this way, we will have to work on this.
We will have to investigate on this.

**Comment by travoliti** [comment]
I found that using VP9 to convert a GIF to a WEBM works, however, VP9 doesn't seem to work with this library:

https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/269

**Comment by Romain** [comment]
Hi @travoliti,
Thanks for this follow-up.
We will investigate on the issue #269 and get back to you as soon as we have more information.
If you wanna help improve the VP9 support in this library, feel free to submit a PR.
R

**Comment by AyrA** [comment]
If not yet fixed, this is an ffmpeg issue. add `-auto-alt-ref 0` to the command line and the error is gone.

**Comment by Romain** [comment]
Ok, thanks for this feedback.
You may want to use the setAdditionalParameters function of the DefaultVideo format to do this.
