### ISSUE TITLE
The process has been signaled with signal "5" FFmpeg php 

### ISSUE THREAD

**Issue by huyvh19** [PHP-FFMpeg/PHP-FFMpeg#256]
i set up ffmpeg and ffprobe on macos, after i create file test.php have require "boostrap.php" of libary php-ffmpeg but i have a bug, i run code 

$logger = new Monolog\Logger('test');
$logger->pushHandler(new Monolog\Handler\StreamHandler('php://stdout'));

$config = array(
    'ffmpeg.binaries' => '/usr/local/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/local/bin/ffprobe',
    'timeout' => 0,

);

$ffprobe = FFMpeg\FFMpeg::create($config, $logger);

$test = $ffprobe->open('/Sites/Demo/php-ffmpeg/tests/files/test.mp4');

i have a bug and i dont know handle it.

Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The process has been signaled with signal "5".' in /Sites/Demo/php-ffmpeg/vendor/symfony/process/Process.php:371 Stack trace: #0 /Sites/Demo/php-ffmpeg/vendor/symfony/process/Process.php(203): Symfony\Component\Process\Process->wait() #1 /Sites/Demo/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(64): Symfony\Component\Process\Process->run(Object(Closure)) #2 /Sites/Demo/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #3 /Sites/Demo/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, NULL) #4 /Sites/Demo/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(61): Alchemy\BinaryDriver\AbstractBinary->command(Array) in /Sites/Demo/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php on line 63

**Comment by Romain** [comment]
Hi @huyvh19,

Why don't you include your library like below in your Controller, instead of requiring bootstrap.php?

`use FFMpeg;`

Could you provide more of you code in order for us to figure out what's wrong in it?

Thanks
Romain

**Comment by huyvh19** [comment]
this is my code, if i run in command line, it ok but i run it in browser chorme, it not ok.

require "bootstrap.php";

set_time_limit(0);


$logger = new Monolog\Logger('test');
$logger->pushHandler(new Monolog\Handler\StreamHandler('php://stdout'));



$config = array(
    'ffmpeg.binaries' => '/usr/local/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/local/bin/ffprobe',
    'timeout' => 3600,
    'ffmpeg.threads' => 12,
);

$ffprobe = FFMpeg\FFProbe::create($config, $logger);

$file_path = '/Sites/Demo/php-ffmpeg/tests/files/test.mp4';
$file_info = $ffprobe
    ->streams($file_path)
    ->videos()
    ->first()
    ->keys();

var_dump($file_info);die;

**Comment by Romain** [comment]
Hi @huyvh19,

One more time, why don't you include your library like below in your Controller, instead of requiring bootstrap.php?

`use FFMpeg;`

**Comment by huyvh19** [comment]
hi @Romain 
i use FFmpeg; it show error 
Warning: The use statement with non-compound name 'FFMpeg' has no effect in /Sites/Demo/php-ffmpeg/tests/test.php 
i attack my test project.
Please help me this issue.
Thanks!
[FFMpeg.zip](https://github.com/PHP-FFMpeg/PHP-FFMpeg/files/611529/FFMpeg.zip)

**Comment by Romain** [comment]
Are you using Symfony for your project?
Or, at least, Composer to deal with this library?

**Comment by huyvh19** [comment]
Thanks @Romain  i use framework laravel and it run success

**Comment by Romain** [comment]
I've never used Laravel, but my guess is that this library should be used the same way than with Symfony.
Could you try using this snippet instead of your code:

```php
use FFMpeg;

$logger = new Monolog\Logger('test');
$logger->pushHandler(new Monolog\Handler\StreamHandler('php://stdout'));

$config = array(
'ffmpeg.binaries' => '/usr/local/bin/ffmpeg',
'ffprobe.binaries' => '/usr/local/bin/ffprobe',
'timeout' => 3600,
'ffmpeg.threads' => 12,
);

$ffprobe = FFMpeg\FFProbe::create($config, $logger);

$file_path = '/Sites/Demo/php-ffmpeg/tests/files/test.mp4';
$file_info = $ffprobe
->streams($file_path)
->videos()
->first()
->keys();

var_dump($file_info);die;
```

**Comment by Romain** [comment]
@huyvh19 Have you solved your problem?
Have you tried what I suggest?

**Comment by huyvh19** [comment]
thank you @Romain  i use laravel framework and i run success full your code.

**Comment by Romain** [comment]
Thanks @huyvh19 !
Therefore, I close this issue.
