### ISSUE TITLE
Your FFProbe version is too old and does not support `-help` option, please upgrade.

### ISSUE THREAD

**Issue by joyebright** [PHP-FFMpeg/PHP-FFMpeg#259]
@SimonSimCity @romainneutron @MrHash @pulse00 
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 2.8.8
| FFmpeg Version | 2.8.8
| OS             | Ubuntu 16.04

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?
I've following PHP code : 
```
$ffmpeg = FFMpeg\FFMpeg::create(array(
                                         'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
                                         'ffprobe.binaries' => '/usr/bin/ffprobe'
                                       ));
                                        $video = $ffmpeg->open(ADDR.'uploadVideo/'.$name.$extension[1]);
                                        $frame = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(42));
                                        $frame->save(ADDR.'uploadVideo/'.$name.'jpg');

```
First I have tried to use Create Singleton Method without inserting array then I got this error : 

> Your FFProbe version is too old and does not support `-help` option, please upgrade.

then I set the directories which are terms of ffmpeg and ffprobe , now I got the same error

#### Expected Behavior

What is the behavior you expect?

If my PHP code considered , I am going to get the snapshot of the exact time of the video which is uploaded on the server but it would be corrupted , unfortunately!

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

I download PHP-FFMpeg dependencies by the following JSON file :
```
{
    "require": {
        "php-ffmpeg/php-ffmpeg": "~0.5"
    }
}
```

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

I think if there are any ways for upgrading my version from 2.8.8 to upper version , the problem would be solved but I have tried whole of the solutions but they didn't work.

**Comment by SimonSimCity** [comment]
Ok, what I can tell you is, that this error is thrown in https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/e9f87eee94288b7aadd909b217925fb101cb3e7b/src/FFMpeg/FFProbe/OptionsTester.php#L63 - a method that is used in the `has()` method call right above, that confirms that `ffprobe` also has the parameter you want to call it with.

For some reason now the library distinguished that the parameter `-help` is not part of your library.

Are you sure you have `ffmpeg` installed, or is it eventually just `libav`? If not, I have a story to tell 😜 http://stackoverflow.com/questions/9477115/what-are-the-differences-and-similarities-between-ffmpeg-libav-and-avconv Have you upgraded your Ubuntu or have you installed it from a fresh image?

That's all I can tell here ... I've also just been using this library a while ago and am not one of the maintainers ...

**Comment by Romain** [comment]
Hi @joyebright,
Have you found a solution for this issue?
Should we close it?

**Comment by joyebright** [comment]
@Romain Actually no,
I couldn't find any solutions !

**Comment by Romain** [comment]
@joyebright can you tell us how you installed FFMPEG? Was is using apt-get?
If yes, could you try to install it using the [compilation guide](https://trac.ffmpeg.org/wiki/CompilationGuide)?

**Comment by joyebright** [comment]
@Romain yes I used apt-get.

**Comment by Romain** [comment]
@joyebright, can you try to reinstall it using the compilation guide?
It frequently solves problems.
If you also have any trace or log to provide, it would be helpful.

**Comment by joyebright** [comment]
@Romain tnq for ur kind reply, but actually now I am on another project which is completely far from FFMpeg, So if I could find enough time, I would follow ur instruction soon.

**Comment by marwan2** [comment]
This stupid issue still appears and now one from authors have a fix, so poor
