### ISSUE TITLE
can we set size of image frame in save function ?

### ISSUE THREAD

**Issue by pbaheti** [PHP-FFMpeg/PHP-FFMpeg#263]
| Q              | A
| -------------- | ---
| Bug?           | no

| New Feature?   | yes

| OS             |  windows 7

#### Actual Behavior

Unable to set the size of image frame so I am unable to use thumbnail size.

#### Steps to Reproduce
$ffmpeg = FFMpeg\FFMpeg::create(array(
                'ffmpeg.binaries'  => 'C:\\ffmpeg\\bin\\ffmpeg.exe',
                'ffprobe.binaries' => 'C:\\ffmpeg\\bin\\ffprobe.exe'));

            $video = $ffmpeg->open($videoFile);
            $frame = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(1));
            $frame->save('C:\wamp64\www\woc\image_bucket\thumbnail\\'.$thumbnailFileName);

**Comment by Romain** [comment]
Hi @pbaheti,

Could you try this and let me know if it solves your problem?

```php
$video = $ffmpeg->open($videoFile);
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();
$frame = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(1));
$frame->save('C:\wamp64\www\woc\image_bucket\thumbnail\\'.$thumbnailFileName);
```

Replace the dimensions with those you want.
R

**Comment by bizilliam** [comment]
Romain,

I've tried this and kept getting videofilter resize errors.  Now, I quit getting errors, but it's not resizing at all.  It's creating a native 720x480 frame.  I'll go back to drawing board tomorrow and try from command line.

> 	    $video = $ffmpeg->open('/var/www/FTP_TBGS/MasterVideoLibrary2/TEST0009.mpg');
	    $video
		->filters()
		->resize(new FFMpeg\Coordinate\Dimension(320, 240))
		->synchronize();
	    $frame = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(1));
	    $frame->save('TEST0009.jpg');

**Comment by Romain** [comment]
Could you give us the errors you got?

**Comment by bizilliam** [comment]
I'm not getting errors anymore, but if I use 'use FFMpeg;' in my PHP header I'll get 'The use statement with non-compound name 'FFMpeg' has no effect'.  If i use 'use FFMpeg\Media;', the error goes away.

Regardless,  I still can't resize.  I can resize manually.  For example, from command line

ffmpeg -i /var/www/FTP_TBGS/MasterVideoLibrary2/TEST0009.mpg -ss 00:00:01 -s 320x240 -vframes 1 out.jpg

Creates a 320x240 jpg image.  How do I see the command that php-ffmpeg is generating?  I'm still using the same code.  I end up getting a full size frame in the save.

> $video = $ffmpeg->open('/var/www/FTP_TBGS/MasterVideoLibrary2/TEST0009.mpg');
>     $video
> 	->filters()
> 	->resize(new FFMpeg\Coordinate\Dimension(320, 240))
> 	->synchronize();
>     $frame = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(1));
>     $frame->save('TEST0009.jpg');

**Comment by Romain** [comment]
> How do I see the command that php-ffmpeg is generating?

You can find it in the logs.

> if I use 'use FFMpeg;' in my PHP header I'll get 'The use statement with non-compound name 'FFMpeg' has no effect'.

How have you installed FFMPEG? Using composer? If yes, is your autoload file properly required? What is the framework your using?
Could you provide us more details about your environment?
There's no reason for the use statement to not be properly interpreted, and there's no reason to use FFMpeg\Media instead...

**Comment by bizilliam** [comment]
I installed php-ffmpeg plugin via composer.
I installed FFMpeg software by downloading the ffmpeg/ffprobe pre-compiled binaries from the website in the readme and placed them in the proper directories (linux).  I didn't compile from source.

I'm using Yii2 on a Vagrant VM, so the 'use FFMPEG' I guess is a Yii2 generated error?

I just found that I am having the same problem as #267 .  The resize parameters are being ignored.
[](https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/267)

Maybe we have an FFMpeg version mis-match?  I'm using FFMpeg 3.2.2-64-bit static.
ffmpeg version 3.2.2-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-4) 20161202
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by Romain** [comment]
Hi @bizilliam,
Thanks for these details.
Could you look in your logs for the ffmpeg command that is being executed? Could you try to execute it manually, and copy-paste it here, with the error message you get, if you get one?
I don't know Yii nor Vagrant, so for the moment, the only thing I can do to help you is trying to figure out what is the reaction of FFMPEG.

**Comment by wskeee** [comment]
I have the same problem.
I'm using WAMP + YII2 + window ffmpeg

When I run  
![image](https://user-images.githubusercontent.com/12245375/37389747-74c03e80-27a0-11e8-9c48-c8c97d50e651.png)
![image](https://user-images.githubusercontent.com/12245375/37389764-83f75ef6-27a0-11e8-9107-ebfd3fd2d32d.png)
the result is
![image](https://user-images.githubusercontent.com/12245375/37389783-956328a0-27a0-11e8-8bcb-2108521e824c.png)

There is no change in size !

**Comment by jens1o** [comment]
The results are cached. You need to construct a new one.

**Comment by jens1o** [comment]
duplicate #336
