### ISSUE TITLE
How get metada video file (width, height, format, duration, audio, size)?

### ISSUE THREAD

**Issue by boomuo** [PHP-FFMpeg/PHP-FFMpeg#264]
Hello!
How i can get this info in array from video file?

**Comment by Romain** [comment]
Hi @boomuo,
Here is the way to get this information:

```php
$ffprobe = FFMpeg\FFProbe::create();
$video_dimensions = $ffprobe
    ->streams( $full_video_path )   // extracts streams informations
    ->videos()                      // filters video streams
    ->first()                       // returns the first video stream
    ->getDimensions();              // returns a FFMpeg\Coordinate\Dimension object
$width = $video_dimensions->getWidth();
$height = $video_dimensions->getHeight();

$duration = $ffprobe->format( $full_video_path )->get('duration');

// This is in the main doc...
$ffprobe
    ->streams($full_video_path) // extracts streams informations
    ->videos()                      // filters video streams
    ->first()                       // returns the first video stream
    ->get('codec_name');            // returns the codec_name property
```

Thanks to let me know if this solves your question.

**Comment by boomuo** [comment]
Thank you, but very low speed :( Maybe this all lib low speed?

This code high speed
`		$cmd = $this->ffmpegPath." -i ".$data['filePath']." -hide_banner 2>&1";
		$ffmpeg = shell_exec($cmd);

		$search = "/Duration: (.*?)\./";
		preg_match($search, $ffmpeg, $matches);
		$data['duration'] = $matches[1];
		$time_sec = explode(':', $data['duration']);
		$data['durationSecond'] = ($time_sec['0']*3600)+($time_sec['1']*60)+$time_sec['2'];

		$search = "|Video:.* (\d{3,4}+x\d{3,4})|";
		preg_match($search, $ffmpeg, $matches);
		$data['video'] = $matches[1];
		return $data;`

How i can create screenshots to video? Simple: rows-3, colls - 4, width every little screen - 200px. Will that posible?

**Comment by Romain** [comment]
If you think that there are differences between the library and the command line, the best way to test it is to mesure the time your script takes to run, to take the exact command line executed by the script from the logs, and to execute it measuring as well the duration.
If you still think this is an issue, please open a new ticket.

With regards to the screenshots, everything is explained in the doc here: 
https://github.com/PHP-FFMpeg/PHP-FFMpeg#extracting-image
including the resize options:
https://github.com/PHP-FFMpeg/PHP-FFMpeg#extracting-image

Please read the doc first.
Thanks

**Comment by AhmedK97** [comment]
Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in C:\laragon\www\video_platform\vendor\php-ffmpeg\php-ffmpeg\src\Alchemy\BinaryDriver\AbstractBinary.php:159
Stack trace:
#0 C:\laragon\www\video_platform\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration))
#1 C:\laragon\www\video_platform\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFProbe.php(220): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), NULL)
#2 C:\laragon\www\video_platform\app\Jobs\ConvertVideoForStreaming.php(103): FFMpeg\FFProbe::create()
#3 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Jobs\ConvertVideoForStreaming->handle()
#4 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#6 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#9 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#10 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#11 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ConvertVideoForStreaming), false)
#13 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#14 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#15 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(App\Jobs\ConvertVideoForStreaming))
#17 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#18 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#19 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(375): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#20 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(173): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#21 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(146): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#22 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(130): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#23 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#24 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#26 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Console\Command.php(178): Illuminate\Container\Container->call(Array)
#29 C:\laragon\www\video_platform\vendor\symfony\console\Command\Command.php(291): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Console\Command.php(148): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 C:\laragon\www\video_platform\vendor\symfony\console\Application.php(1014): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 C:\laragon\www\video_platform\vendor\symfony\console\Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 C:\laragon\www\video_platform\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Console\Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(155): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 C:\laragon\www\video_platform\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}

Next FFMpeg\Exception\ExecutableNotFoundException: Unable to load FFProbe in C:\laragon\www\video_platform\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php:50
Stack trace:
#0 C:\laragon\www\video_platform\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFProbe.php(220): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), NULL)
#1 C:\laragon\www\video_platform\app\Jobs\ConvertVideoForStreaming.php(103): FFMpeg\FFProbe::create()
#2 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Jobs\ConvertVideoForStreaming->handle()
#3 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#5 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#6 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#7 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#8 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#9 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#10 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ConvertVideoForStreaming), false)
#12 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#13 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#14 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(App\Jobs\ConvertVideoForStreaming))
#16 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#17 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#18 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(375): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#19 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(173): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#20 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(146): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#21 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(130): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#22 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#23 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#25 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#26 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Container\Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#27 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Console\Command.php(178): Illuminate\Container\Container->call(Array)
#28 C:\laragon\www\video_platform\vendor\symfony\console\Command\Command.php(291): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Console\Command.php(148): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 C:\laragon\www\video_platform\vendor\symfony\console\Application.php(1014): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 C:\laragon\www\video_platform\vendor\symfony\console\Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 C:\laragon\www\video_platform\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Console\Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 C:\laragon\www\video_platform\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(155): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 C:\laragon\www\video_platform\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 {main}

How Can I Fix This .. Help :(

**Comment by AndersonNascimentoDosSantos** [comment]
@AhmedK97 you need to 

1. have it in your OS 
2. infoorm the path to the binary in this declaration  


```php
$ffmpeg = FFMpeg::create(array(
                'ffmpeg.binaries' => '/bin/ffmpeg', // path for the ffmpeg binary in your System
                'ffprobe.binaries' => '/bin/ffprobe', //path for the ffprobe binary in your System
                'timeout' => 3600, // The timeout for the underlying process
                'ffmpeg.threads' => 2,   // The number of threads that FFMpeg should use
            ), $logger);
```
