### ISSUE TITLE
Removing audio?

### ISSUE THREAD

**Issue by Barker91** [PHP-FFMpeg/PHP-FFMpeg#270]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.6.1
| FFmpeg Version | 3.2.2

What is the correct way of removing audio from a video? 

In command form, the flag to remove audio is `-an`. How would this be done through this library?

**Comment by Romain** [comment]
Hi @Barker91,
This question has already been raised in issue #262, and the PR #215 will fix this.
We're still in the process of writing tests for this PR. Once this has been done, we will merge it.
R
