### ISSUE TITLE
Unable to probe /ThinkPhpStudy/Uploads/Img/out.mpg

### ISSUE THREAD

**Issue by Tinywan** [PHP-FFMpeg/PHP-FFMpeg#276]
`$path = __ROOT__ . '/Uploads/';
        $ffmpeg =   FFMpeg::create();
        $ffmpeg->open("{$path}Img/out.mpg");`

**Comment by Tinywan** [comment]
This file path to use the absolute path, for example: `http://127.0.0.1/ThinkPhpStudy/Uploads/FFmpegVideo/out.mpg`

**Comment by Tinywan** [comment]
@Romain I think it is a relative path, the result is an absolute path, but the output file path can not specify the directory, this do not know how to do?

**Comment by Tinywan** [comment]
@Romain
Well, thank you very much, this problem has been solved

**Comment by Romain** [comment]
You're welcome.
