### ISSUE TITLE
I am not able to install PHP-FFMpeg is through Composer, please help

### ISSUE THREAD

**Issue by pickzy** [PHP-FFMpeg/PHP-FFMpeg#280]
Below is the error which I am getting while run this command  >> php composer require php-ffmpeg/php-ffmpeg
 
Ratheeshs-MacBook-Pro:PHP-FFMpeg-master ratheesh$ php composer require php-ffmpeg/php-ffmpeg
Please any anybody know why I am getting this error.
;
Using version ^0.6.1 for php-ffmpeg/php-ffmpeg
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  **Problem 1
    - The requested package php-ffmpeg/php-ffmpeg No version set (parsed as 1.0.0) is satisfiable by php-ffmpeg/php-ffmpeg[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.**

Installation failed, reverting ./composer.json to its original content.

**Comment by Romain** [comment]
Hi @pickzy,
Could you show us your composer.json?
There seems to be a conflict between your requirements and those of PHP-FFMPEG.
Thanks
Romain

**Comment by pickzy** [comment]
{
    "name": "php-ffmpeg/php-ffmpeg",
    "type": "library",
    "description": "FFMpeg PHP, an Object Oriented library to communicate with AVconv / ffmpeg",
    "keywords": ["video processing", "video", "audio processing", "audio", "avconv", "ffmpeg", "avprobe", "ffprobe"],
    "license": "MIT",
    "authors": [],
    "require": {
        "php": "^5.6.24 || ^7.0",
        "alchemy/binary-driver": "^1.5",
        "doctrine/cache": "^1.0",
        "evenement/evenement": "^2.0 || ^1.0",
        "neutron/temporary-filesystem": "^2.1.1"
    },
    "suggest": {
        "php-ffmpeg/extras": "A compilation of common audio & video drivers for PHP-FFMpeg"
    },
    "require-dev": {
        "sami/sami": "~1.0",
        "silex/silex": "~1.0",
        "phpunit/phpunit": "^4.8"
    },
    "autoload": {
        "psr-0": {
            "FFMpeg": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\FFMpeg\\": "tests"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "0.7-dev"
        }
    }
}

**Comment by Romain** [comment]
This is the composer.json of PHP-FFMPEG, I was talking about your composer.json, more particularly the require part. I'd like to see if there may be any conflict between these 2 files.

I just tried to run `composer require php-ffmpeg/php-ffmpeg` on my side, and it worked well.

**Comment by pickzy** [comment]
<img width="695" alt="screen shot 2017-01-06 at 3 27 55 am" src="https://cloud.githubusercontent.com/assets/5693243/21699104/281d59b2-d3c0-11e6-9bb9-c23f5825b2cb.png">
Please see this attached screen shot. Please suggest me the right command.

**Comment by Romain** [comment]
Ok @pickzy, you're not answering my comment. I asked you for the composer.json file of your app. Could you provide it to me so I can see what are the requirements of your app?
Could you also tell us what is your version of PHP by running the command `php -v` ?

**Comment by pickzy** [comment]
My Php version: PHP 5.6.24 (cli) (built: Aug  8 2016 16:58:37)
Attached my composer.json file
[composer.json.zip](https://github.com/PHP-FFMpeg/PHP-FFMpeg/files/690284/composer.json.zip)

**Comment by Romain** [comment]
Your PHP version should'nt be a problem.
The file you sent me is PHP-FFMPEG composer.json file. So my guess is that you're trying to install it as a standalone bundle in a project, not as a depency of Symfony or any other framework, is that correct?
Could you try to run the command in a new folder, out of your current project and see if you get any error?

**Comment by Romain** [comment]
Hi @pickzy,
Have you been able to solve this issue?

**Comment by pickzy** [comment]
no

--

Thanks and have a great day.

Regards
Ratheesh | Director
* <http://www.pickzyinteractive.com/>*
| JVL Plaza Building | 6th Floor | Anna Salai |
| Teynampet | Chennai 600 018 | India |
| India Phone : (044) - 45014466 | US Direct : (213)(261)-0683 |
| Skype : macratheesh |
| Email  : ratheesh@pickzy.com |
| URL    : www.pickzyinteractive.com |

*Disclaimer Statement:*
Information contained and transmitted by this E-MAIL is proprietary to
pickZy.com and is intended for use only by the individual/entity to
whom/which it is addressed, and may contain information that is privileged,
confidential or exempt from disclosure under applicable law. If this is a
forwarded message, the content of this E-MAIL may not have been sent with
the authority of the Company. If you are not the intended recipient, an
agent of the intended recipient or a person responsible for delivering the
information to the named recipient, you are notified that any use,
distribution, transmission, printing, copying or dissemination of this
information in any way or in any manner is strictly prohibited. If you have
received this communication in error, please delete this mail.

**Comment by Romain** [comment]
Could you answer my questions then?
Or should I close this issue?

**Comment by pickzy** [comment]
The file you sent me is PHP-FFMPEG composer.json file. So my guess is that you're trying to install it as a standalone bundle in a project, not as a depency of Symfony or any other framework, is that correct? YES
Could you try to run the command in a new folder, out of your current project and see if you get any error? I tried still getting same issue.
Tomorrow again let me try with different pc and let your know.

**Comment by dana321** [comment]
I thought i would post here since i had the same issue.

You need to run composer update first, then you will be able to install php-ffmpeg
