### ISSUE TITLE
I am not able to convert ogg file to mp3

### ISSUE THREAD

**Issue by gabrielschuck** [PHP-FFMpeg/PHP-FFMpeg#300]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

_How does PHP-FFMpeg behave at the moment?_

#### Expected Behavior

_What is the behavior you expect?_

#### Steps to Reproduce

_What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem._

#### Possible Solutions

_If you have already ideas how to solve the issue, add them here.
Otherwise remove this section._

I'm trying to convert ogg file to mp3 with this little code:

```php
include ('vendor/autoload.php');
$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  =>'/usr/bin/ffmpeg',
    'ffprobe.binaries' =>'/usr/bin/ffprobe

    'timeout'          => 3600, // The timeout for the underlying process
    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
), $logger);

$audio = $ffmpeg->open( 'example.flac');

// Set an audio format
$audio_format = new FFMpeg\Format\Audio\Mp3();

// Extract the audio into a new file
$video->save('audio.mp3');
```

Return a fatal error:

```
Fatal error :  Uncaught exception 'Alchemy\BinaryDriver\Exception\Execut
ionFailureException' with message 'ffmpeg failed to execute command
'/usr/bin/ffmpeg' '-y' '-i' '/var/www/html/teste/transcript.ogg'
'-acodec' 'libmp3lame' '-b:a' '128k' '/var/www/html/teste/audio.mp3'' in
/var/www/html/teste/vendor/alchemy/binary-driver/src/Alchemy/BinaryDrive
r/ProcessRunner.php:100 Stack trace: #0 /var/www/html/teste/vendor/alche
my/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72):
Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffmpe.
..') #1 /var/www/html/teste/vendor/alchemy/binary-driver/src/Alchemy/Bin
aryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->r
un(Object(Symfony\Component\Process\Process), Object(SplObjectStorage),
false) #2 /var/www/html/teste/vendor/alchemy/binary-driver/src/Alchemy/B
inaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary
->run(Object(Symfony\Component\Process\Process), false, Array) #3
/var/www/html/teste/src/FFMpeg/Media/Audio.php(97): Al in
/var/www/html/teste/src/FFMpeg/Media/Audio.php on line 100
```

The code is running on a server with centos 6.8 installed. Both ffmpeg and ffprobe are also installed. File conversion usually works straight from SSH.
What's going on?

**Comment by Romain** [comment]
Hi @gabrielschuck,
Could you try this:

```php
$video->save($audio_format, 'audio.mp3');
```

and tell me if it works?

**Comment by jens1o** [comment]
Anyway, we should validate wether it's a valid audio format submitted. I'm creating a pr.

**Comment by jens1o** [comment]
Huhh? It seems that @gabrielschuck's php binaries are broken. Actually, there is a type hint already included...

**Comment by Romain** [comment]
Yeah, normally the core features of the bundle have been really nicely developed by @romainneutron.
When we face an issue with sound encoding it's mainly due to a lack of codecs on the server of the user, or to the way FFMPEG has been installed.
The best way to install FFMPEG is to compile it following [this documentation](https://trac.ffmpeg.org/wiki/CompilationGuide).
In this case, it would be great if @gabrielschuck could manually execute the commande generated by the bundle and give us the result, so we could get the exact error message.

**Comment by gabrielschuck** [comment]
Thanks guys, I got the hang of it. I had to give permissions on the files and folders. The script works very well, I even did the installation of ffmpeg in Centos following this tutorial:
Https://trac.ffmpeg.org/wiki/CompilationGuide/Centos
greetings
