### ISSUE TITLE
getFormat -> empty

### ISSUE THREAD

**Issue by andrekat** [PHP-FFMpeg/PHP-FFMpeg#303]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | latest composer
| FFmpeg Version | latest from distributor
| OS             | Windows

I am using PHP-FFMpeg to convert any audio file to mp3 (192 KBIT, 44.100 HZ).
My problem: getting the format of an mp3 (e.g. 128 KBIT, 24.100 HZ)

Code I am using:

`$ffmpeg = FFMpeg::create();
        $audio = $ffmpeg->open($path);

        $currentFormat = $audio->getFormat();

        debug($currentFormat);`

Generated output:

`object(FFMpeg\FFProbe\DataMapping\Format) {
	
}`

Please help! 👍

**Comment by Romain** [comment]
Hi @andrekat, could you be more specific on what you wanna get exactly?
Have you tried this?

```php
var_dump( $currentFormat->getAudioCodec() );
```

**Comment by andrekat** [comment]
Hello @Romain, I followed your suggestion and this is the result:
`
Call to undefined method FFMpeg\\FFProbe\\DataMapping\\Format::getAudioCodec()`

Any idea?

**Comment by Romain** [comment]
What about 

```php
var_dump( $audio->getAudioCodec() );
```

?

What type of information to you expect?

**Comment by andrekat** [comment]
Accessing the properties via "get" method is working now.

e.g.:
$currentFormat->get("format_name") == "mp3"
$currentFormat->get("bit_rate") == 192852

**Comment by Romain** [comment]
Ok, thanks for this follow-up.
