### ISSUE TITLE
the default method save cause excepition!

### ISSUE THREAD

**Issue by weituotian** [PHP-FFMpeg/PHP-FFMpeg#305]
| Q              | A
| -------------- | ---
| Bug?           | Yes
| New Feature?   | no
| Version Used   |  
| FFmpeg Version | 3.2
| OS             | win10
#### Actual Behavior

```
require_once "vendor/autoload.php";

$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries' => 'bin/ffmpeg.exe',
    'ffprobe.binaries' => 'bin/ffprobe.exe',
    'timeout' => 3600, // The timeout for the underlying process
    'ffmpeg.threads' => 12,   // The number of threads that FFMpeg should use
));

$video = $ffmpeg->open('10916529-1.flv');

$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();

$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
    ->save('upload/frame.jpg');

$video->save(new FFMpeg\Format\Video\X264(), 'upload/export-x264.mp4');
```

![image](https://cloud.githubusercontent.com/assets/7270968/23012519/9f347104-f461-11e6-918b-117562c5e735.png)

i can get the image but can not encode the video!
![image](https://cloud.githubusercontent.com/assets/7270968/23012627/0d21de72-f462-11e6-8511-48a8e76730e5.png)

**Comment by weituotian** [comment]
![image](https://cloud.githubusercontent.com/assets/7270968/23012815/f1eafa20-f462-11e6-8777-f2703bd9e6ba.png)

**Comment by Romain** [comment]
Hi @weituotian,
The error is quite explicit. A quick search in the issues would have given you the solution.
The problem is that you don't have the required codec installed on your machine.
You need to select another audio codec:

```php
$format = new FFMpeg\Format\Video\X264();
$format->setAudioCodec("libmp3lame");
$save = $video->save($format, $video_export_path);
```

More details with issue #295 or #288

**Comment by Romain** [comment]
Hi @weituotian, any news on this issue?

**Comment by weituotian** [comment]
@Romain thanks for your replies !
