### ISSUE TITLE
How to run this ffmpeg command through PHP-FFMpeg

### ISSUE THREAD

**Issue by sullyfischer** [PHP-FFMpeg/PHP-FFMpeg#307]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.9.0
| FFmpeg Version | FFmpeg 3.2.4
| OS             | macOS 10.12

I've been trying to convert .gif to .mp4 and it works with below code:

```
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('animated.gif');
$video->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4');
```

But the converted file doesn't play in browsers. I've found this ffmpeg ssh command that works great (the converted file does work in browsers) but I have no idea how to do it with package. Here is command:

```
ffmpeg -i animated.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" video.mp4
```

Thank you for your great package BTW.

**Comment by jens1o** [comment]
Hi!
`$format->setAdditionalParameters(array('foo', 'bar'));` may help you.

**Comment by sullyfischer** [comment]
Thanks man, that did the trick
