### ISSUE TITLE
Replace libfaac by libmp3lame as the default codec

### ISSUE THREAD

**Issue by Romain** [PHP-FFMpeg/PHP-FFMpeg#322]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.9.2

#### Actual Behavior

The default codec for the audio is libfaac which is source of errors for a lot of people who don't have this codec installed by default and don't think to set up the codec they want to use in their code.

#### Expected Behavior

We should change this and make libmp3lame the default codec, and also check if the codec is available before setting it.

**Comment by jens1o** [comment]
I think I could get into it, if you want to.

**Comment by Romain** [comment]
@jens1o If you can, please do, I have a lot on my plate these weeks.
Thanks for your help.

**Comment by jens1o** [comment]
Okey, I'll do it. I think the PR will be available in the evening(UTC+1)

**Comment by Romain** [comment]
Thanks @jens1o

**Comment by jens1o** [comment]
Well, if you could help me out with the tests, we could close this issue 😉 

I don't know how to fix it :/

**Comment by Romain** [comment]
Ok, I'll try to have a look ASAP, I really have very few time these days.

**Comment by Marchrius** [comment]
IMHO the best choose is to change flaac with aac. In this way you use a counter-part very close to flaac.

**Comment by php2020** [comment]
$format = new FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage % transcoded";
});

$video->save($format, 'video.avi');

**Comment by php2020** [comment]
`$format = new FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage % transcoded";
});

$video->save($format, 'video.avi');`

**Comment by jens1o** [comment]
Extracted the `codec testing` thing in a seperate issue.
