### ISSUE TITLE
i have installed PHP-FFMpeg,But when i executed  phpinfo() function.it has no php-fmpeg moudle ，why？Please tell me，Thanks

### ISSUE THREAD

**Issue by cjw0202** [PHP-FFMpeg/PHP-FFMpeg#324]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by jens1o** [comment]
First of all, please fill out the template. Second of all, this project doesn't provide an php extension, but only a library(which can be pulled by composer), so this won't be shown in `phpinfo` output.

**Comment by cjw0202** [comment]
thanks for your responses,but how to use ffmpeg in php programs?

发自我的 iPhone

在 2017年3月14日，01:59，Jens Hausdorf <notifications@github.com<mailto:notifications@github.com>> 写道：


First of all, please fill out the template. Second of all, this project doesn't provide an php extension, but only a library(which can be pulled by composer), so this won't be shown in phpinfo output.

**Comment by jens1o** [comment]
Here you go: https://github.com/PHP-FFMpeg/PHP-FFMpeg#basic-usage

**Comment by cjw0202** [comment]
[cid:_Foxmail.1@84f74c3a-4d62-07d9-d5a1-ee7ebb6a09bd]
[cid:_Foxmail.1@283ae7ce-843a-6b2c-bf4d-e29e11f9a6ff]

I don't know why

________________________________
weijia0202@outlook.com

发件人： Jens Hausdorf<mailto:notifications@github.com>
发送时间： 2017-03-14 13:15
收件人： PHP-FFMpeg/PHP-FFMpeg<mailto:PHP-FFMpeg@noreply.github.com>
抄送： cjw0202<mailto:weijia0202@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [PHP-FFMpeg/PHP-FFMpeg] i have installed PHP-FFMpeg,But when i executed phpinfo() function.it has no php-fmpeg moudle ，why？Please tell me，Thanks (#324)

Here you go: https://github.com/PHP-FFMpeg/PHP-FFMpeg#basic-usage

**Comment by cjw0202** [comment]
hello:

[cid:_Foxmail.1@fefc4e0c-75c4-8efa-ce6c-d65b7d06bcfb]
what means

________________________________
weijia0202@outlook.com

发件人： Jens Hausdorf<mailto:notifications@github.com>
发送时间： 2017-03-14 13:15
收件人： PHP-FFMpeg/PHP-FFMpeg<mailto:PHP-FFMpeg@noreply.github.com>
抄送： cjw0202<mailto:weijia0202@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [PHP-FFMpeg/PHP-FFMpeg] i have installed PHP-FFMpeg,But when i executed phpinfo() function.it has no php-fmpeg moudle ，why？Please tell me，Thanks (#324)

Here you go: https://github.com/PHP-FFMpeg/PHP-FFMpeg#basic-usage

**Comment by Romain** [comment]
@cjw0202, the README file is pretty explicit on how to use this bundle in a PHP project.
If you don't know what a bundle is or how to use it, please begin by asking google, and then if you have a specific question we may help.
