### ISSUE TITLE
ErrorException - Undefined variable: duration

### ISSUE THREAD

**Issue by djekl** [PHP-FFMpeg/PHP-FFMpeg#333]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | 7cff2ecb23d48f927981ad8cee0583d41eb8d620
| FFmpeg Version | FFmpeg
| OS             | Ubuntu

The issue is here https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/7cff2ecb23d48f927981ad8cee0583d41eb8d620/src/FFMpeg/Filters/Video/ExtractMultipleFramesFilter.php#L84L107

On line 107, you expect to have a variable `$duration`, however this is only set within an if statement.

To fix this, a sane default needs to be set in order to calculate the number of images that are produced.

I have experienced this by uploading a `.webm` file that is 3 seconds long, and trying to capture a frame a second to produce an animated gif later.

**Comment by jens1o** [comment]
I do not understand how you want to fix it. You need that thing, and I don't think that you are allowed to set the value to something "default", since there are many different standards.

**Comment by djekl** [comment]
I didn't say just a default, I said a sane default. You are using a variable without a check that is conditionally set. By a sane default, I mean to instantiate `$duration` with (for example) a value of `0` before line 83 https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/7cff2ecb23d48f927981ad8cee0583d41eb8d620/src/FFMpeg/Filters/Video/ExtractMultipleFramesFilter.php#L83

This way you have a value defined, and can either quit early, throw an exception to be caught, or continue on with the default value.

**Comment by jens1o** [comment]
Ah, now I do understand what you mean. I'll do a pr.

**Comment by Romain** [comment]
@jens1o, just after `$commands = array();`, we should add `$duration = 0;`.
I will create a PR.
