### ISSUE TITLE
Unrecognized option 'metadata:s:v:0' error with latest stable build of ffmpeg.

### ISSUE THREAD

**Issue by mcfriend99** [PHP-FFMpeg/PHP-FFMpeg#337]
| Q              | A
| -------------- | ---
| Bug?           | don't know
| New Feature?   | no
| Version Used   | latest
| FFmpeg Version | SVN-r26402, Copyright (c) 2000-2011 the FFmpeg developers and it's built on Jun 3 2016 16:16:37
| OS             | Linux
#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

I got this error:

PHP Fatal error:  Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/home/user/public_html/contents/videos/1490790518_MP4_360p_Short_video_clip_nature_mp4.mp4' '-async' '1' '-metadata:s:v:0' 'start_time=0' '-r' '16' '-b_strategy' '1' '-bf' '3' '-g' '9' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '128k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '8k' '-ac' '1' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes58dbac4e179ef5wap2/pass-58dbac4e17af6' '/home/user/public_html/contents/videos/1490790518_MP4_360p_Short_video_clip_nature_mp4_22995.mp4'' in /home/user/public_html/app/ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100
Stack trace:
#0 /home/user/public_html/app/ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alch in /home/user/public_html/app/ffmpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php on line 168

using this php code:

```
<?php

$ffmpeg = $ffmpeg = FFMpeg\FFMpeg::create(['timeout'=>3600, 'ffmpeg.thread'=>12, 'ffmpeg.binaries'  => '/usr/local/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/local/bin/ffprobe']);

            $ffprobe_prep = FFMpeg\FFProbe::create(['ffmpeg.binaries'  => '/usr/local/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/local/bin/ffprobe']);
            $ffprobe = $ffprobe_prep->format($video_file);

            $video = $ffmpeg->open($video_file);

            // Get video duration to ensure our videos are never longer than our video limit.
            $duration = $ffprobe->get('duration');

            // Use mp4 format and set the audio bitrate to 56Kbit and Mono channel.
            // TODO: Try stereo later...
            $format = new FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
            $format
                -> setKiloBitrate(128)
                -> setAudioChannels(1)
                -> setAudioKiloBitrate(8);

            $first = $ffprobe_prep
                        ->streams($video_file)
                        ->videos()
                        ->first();

            $width = $first->get('width');

            if($width > VIDEO_WIDTH){
                // Resize to 558 x 314 and resize to fit width.
                $video
                    ->filters()
                    ->resize(new FFMpeg\Coordinate\Dimension(VIDEO_WIDTH, ceil(VIDEO_WIDTH / 16 * 9)));
            }

            // Trim to videos longer than three minutes to 3 minutes.
            if($duration > MAX_VIDEO_PLAYTIME){

                $video
                    ->filters()
                    ->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(0), FFMpeg\Coordinate\TimeCode::fromSeconds(MAX_VIDEO_PLAYTIME));
            }

            // Change the framerate to 16fps and GOP as 9.
            $video
                ->filters()
                ->framerate(new FFMpeg\Coordinate\FrameRate(16), 9);

            // Synchronize audio and video
            $video->filters()->synchronize();

            $video->save($format, $video_file_new_2);
?>
```

#### Expected Behavior

Resample/Resize an mp4 file into another file.

**Comment by jens1o** [comment]
The build is too old(2014!) and doesn't support the option. Try out with the newest stable build.

**Comment by mcfriend99** [comment]
I am on a shared hosting account. And they have refused to upgrade in order to keep other users code compatible or so they say... Please what can I do?

**Comment by jens1o** [comment]
Do not use the synchronize feature. But then you probably have some new issues.

**Comment by mcfriend99** [comment]
Ya, I now get another error saying "Unrecognized option 'b:v'". I can't afford to ask my customer for another money to purchase another hosting. Please what can I do??

**Comment by mcfriend99** [comment]
Is it possible to get a version of PHP-FFMpeg compatible with this build??

**Comment by jens1o** [comment]
Well, there is. 0.4.1 was the latest release, where this should work without: https://github.com/PHP-FFMpeg/PHP-FFMpeg/releases/tag/0.4.1

But I wouldn't use this, it is unmaintained and old.

**Comment by mcfriend99** [comment]
Will the code be compatible with the one above or will I have to tweak my code to conform? My customer just needs it to run as we are now concerned with making it work while we source alternative hosting.

**Comment by jens1o** [comment]
To be honest, I don't know exactly. I will look. Stay tuned.

**Comment by mcfriend99** [comment]
Thanks, I glued!!

**Comment by jens1o** [comment]
Result: Anything should work.

**Comment by mcfriend99** [comment]
Thanks. 

For someone else who may wonder though, I just confirmed that setAudioChannel does not exist in that build.

**Comment by mcfriend99** [comment]
Will test it on the production server now to see if it will work!

**Comment by jens1o** [comment]
Ah, that's true. I'd overseen that.

**Comment by mcfriend99** [comment]
Still getting the "Unrecognized option 'b:v'" error. Any more help? Really appreciated!

**Comment by jens1o** [comment]
Ah, I thought you already searched about it. Let me look.

-- Later --

No. There's no way. Even the first version that implements the feature of encoding videos uses this for setting the kilo-bitrate. You could try modify `Video.php`. Remove the lines 88 and 89, then it might work.

**Comment by mcfriend99** [comment]
Now its "Unknown encoder 'libx264'". Any ideas? You really been helpful.

**Comment by jens1o** [comment]
lol. Try to use wmv. It should be available by it. Next, try ogg.

**Comment by mcfriend99** [comment]
I need a video that can play across all major platforms and not heavy on the file size. That's why am going for mp4.

**Comment by mcfriend99** [comment]
Is there a way to use static builds with this script?

**Comment by jens1o** [comment]
When your ffmpeg doesn't support mp4(which uses lib264), then I can't help you... Could you explain what "static builds" mean?

**Comment by mcfriend99** [comment]
I mean I could download static (compiled) builds of ffmpeg from their server and change the path of ffmpeg to it. I already tried it, my problem is that I am getting ExecutableNotFoundException.

**Comment by jens1o** [comment]
Hmm. I don't know. Maybe use https://ffmpeg.org/download.html and check wether they are init scripts?

**Comment by jens1o** [comment]
any news on this @mcfriend99 ?

**Comment by mcfriend99** [comment]
They are working builds and I am already using them on my website. Thanks a lot.

**Comment by jens1o** [comment]
@mcfriend99 Can you close this, please?
