### ISSUE TITLE
ExecutableNotFoundException using ffprobe.binaries

### ISSUE THREAD

**Issue by mcfriend99** [PHP-FFMpeg/PHP-FFMpeg#338]
When I set the ffprobe.binaries to /home/kwilistc/public_html/app/ffmpeg/bin/ffprobe, it gives me ExecutableNotFoundException, but the executable is very much available.

**Comment by jens1o** [comment]
and it's available, executable and writeable for the web server user?

**Comment by mcfriend99** [comment]
Yes. After fixing permissions.

The new error is now `This version of ffprobe is too old and does not support -show_format option`

**Comment by jens1o** [comment]
Then you may need to upgrade 😉

**Comment by mcfriend99** [comment]
I fixed that already.

Now I still get "Unknown encoder: libx264" error. Is there any other encoder I can use?

**Comment by jens1o** [comment]
I don't think so. libx264 is responsible for encoding mp4/mp3 files.

**Comment by Romain** [comment]
@mcfriend99 I think you're missing codecs.
Can you give us more details about your environment? There was a template when you submitted the bug. Thanks to clearly fulfill it when submitting any new issue, so we can help.

| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version
