### ISSUE TITLE
A non-numeric value encountered - Video Progress Listener

### ISSUE THREAD

**Issue by larzuk91** [PHP-FFMpeg/PHP-FFMpeg#339]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | latest
| FFmpeg Version | version 2.7.6-0ubuntu0.15.10.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.2.1 (Ubuntu 5.2.1-22ubuntu2) 20151010
| OS             | Ubuntu 14.04

How to reproduce it:
```
...
$this->FFMpeg = FFMpeg::create([
            'ffmpeg.binaries' => $ffmpegBinary,
            'ffprobe.binaries' => $ffprobeBinary,
            'timeout' => $timeout, // The timeout for the underlying process
            'ffmpeg.threads' => $threads,   // The number of threads that FFMpeg should use
]);
$video = $this->FFMpeg->open($videoUrl);
$video->save(new X264($this->audioCodec), $outputDir."/video.mp4");
```
The problem only occurs when running this library with **php7**

File: FFMpeg\Format\ProgressListener\AbstractProgressListener
Line 182: `$deltaSize = $currentSize - $this->currentSize;`

`$currentSize` variable is a string with value **"n/a"**

So when running in php7 it throws an error **"A non-numeric value encountered"** it just need to be casted to an **Int** before using it or any other way you find better for this case

Would be great to see this fixed in upcoming releases :)

Cheers!

**Comment by jens1o** [comment]
Do you want to create the pr? 😉

**Comment by Romain** [comment]
I just did.
