### ISSUE TITLE
How to merge video with audio file

### ISSUE THREAD

**Issue by testchik** [PHP-FFMpeg/PHP-FFMpeg#346]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Linux,  Godady shared server

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?
work well in my localhost server. but can't work on godaddy server.

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.
include 'vendor/autoload.php';
$ffmpeg = FFMpeg\FFMpeg::create();

$video = $ffmpeg->open('videos/localfile84201711432.mp4');
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
    ->save('frame.jpg');
$video
    ->save(new FFMpeg\Format\Video\WMV(), 'export-wmv.wmv')
    ->save(new FFMpeg\Format\Video\WebM(), 'export-webm.webm');
#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by jens1o** [comment]
First of all, please use the template,so we have a detailed feel on what you're talking about.

Currently, this feature isn't implemented(I'll implement it once my other PRs are merged). But here is a way to do so simply:
```php
<?php

require_once 'vendor\autoload.php';

$ffmpeg = FFMpeg\FFMpeg::create();

$video = $ffmpeg->open(__DIR__ . '\tests\files\lucky-day.mp4');

$video->addFilter(new \FFMpeg\Filters\Audio\SimpleFilter(array('-i ' . __DIR__ . '\tests\files\Audio.mp3', '-shortest')));

$video->save(new \FFMpeg\Format\Video\X264(), 'testoutput.mp4');
```

**Comment by testchik** [comment]
The merge is work on localhost. It is not work in shared server. I needs to work with shared server. How can add ffmpeg in shared server. is it possible to get binary file ffmpeg?

**Comment by jens1o** [comment]
I do not understand what you want. Could you post the exception you get?

**Comment by testchik** [comment]
I get error like:::::::

Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutableNotFoundException' with message 'Executable not found, proposed : avprobe, ffprobe' in /home/igeniusdev/public_html/Unity_Hex/SuperMarket Promotion-WebGL3/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:160 Stack trace: #0 /home/igeniusdev/public_html/Unity_Hex/SuperMarket Promotion-WebGL3/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration)) #1 /home/igeniusdev/public_html/Unity_Hex/SuperMarket Promotion-WebGL3/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(207): FFMpeg\Driver\FFProbeDriver::create(Array, NULL) #2 /home/igeniusdev/public_html/Unity_Hex/SuperMarket Promotion-WebGL3/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(117): FFMpeg\FFProbe::create(Array, NULL, NULL) #3 /home/igeniusdev/public_html/Unity_Hex/SuperMarket Promotion-WebGL3/merger.php(16): FFMpeg\FFMpeg::create() #4 {main} Next exc in /home/igeniusdev/public_html/Unity_Hex/SuperMarket Promotion-WebGL3/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php on line 50

**Comment by testchik** [comment]
you say that binaries can be located with system PATH to get the benefit of the binary detection, otherwise you should have to explicitly give the binaries path on load.

How to include binaries file. How can find binaries file.

**Comment by jens1o** [comment]
Did you install ffmpeg? How did you install it? This library is just a wrapper, but it depends on a installed binary.

**Comment by testchik** [comment]
I installed ffmpeg in localhost on windows system.so it is work well. My live server which is godaddy can't able to install it.  I needs to include binary file.

**Comment by jens1o** [comment]
Is your live server just a web server? Then it isn't possible to execute binaries. I would suggest you ask your support, we can't help with it.

**Comment by testchik** [comment]
yes live server just a web server...............
Are any other methods provides solution of merging video and audio file?

**Comment by jens1o** [comment]
I don't know any.

**Comment by testchik** [comment]
I used your code like:
<?php

include 'vendor/autoload.php';
$ffmpeg = FFMpeg\FFMpeg::create();

$video = $ffmpeg->open('videos/localfile84201711432.mp4');
  $video->addFilter(new \FFMpeg\Filters\Audio\SimpleFilter(array('-i ' . 'videos/Kalimba_Audio.mp3', '-shortest')));
  $video->save(new \FFMpeg\Format\Video\X264(), 'testoutput.mp4');

I got error message like that Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffmpeg failed to execute command "C:\ffmpeg\bin\ffmpeg.EXE" "-y" "-i" "videos/localfile84201711432.mp4" "-i videos/Kalimba_Audio.mp3" "-shortest" "-vcodec" "libx264" "-acodec" "libfaac" "-b:v" "1000k" "-refs" "6" "-coder" "1" "-sc_threshold" "40" "-flags" "+loop" "-me_range" "16" "-subq" "7" "-i_qfactor" "0.71" "-qcomp" "0.6" "-qdiff" "4" "-trellis" "1" "-b:a" "128k" "-pass" "1" "-passlogfile" "C:\Users\abcd\AppData\Local\Temp\ffmpeg-passes58faeeb204dd96w1zk/pass-58faeeb2055a9" "testoutput.mp4"' in C:\xampp\htdocs\Unity_Hex\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php:100 Stack trace: #0 C:\xampp\htdocs\Unity_Hex\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure('"C:\ffmpeg\bin\...') #1 C:\xampp\htdocs\Unity_Hex\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php(209): Alchemy\BinaryDriver\P in C:\xampp\htdocs\Unity_Hex\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\Video.php on line 178

**Comment by jens1o** [comment]
Then try to execute this command and send us the output:
`"C:\ffmpeg\bin\ffmpeg.EXE" "-y" "-i" "videos/localfile84201711432.mp4" "-i videos/Kalimba_Audio.mp3" "-shortest" "-vcodec" "libx264" "-acodec" "libfaac" "-b:v" "1000k" "-refs" "6" "-coder" "1" "-sc_threshold" "40" "-flags" "+loop" "-me_range" "16" "-subq" "7" "-i_qfactor" "0.71" "-qcomp" "0.6" "-qdiff" "4" "-trellis" "1" "-b:a" "128k"`

**Comment by testchik** [comment]
I execute this command message that at least one output file required

**Comment by jens1o** [comment]
That's weird.

**Comment by testchik** [comment]
I can't understand what to do?

**Comment by testchik** [comment]
Any other command for merge audio and video file without ffprobe?

**Comment by jens1o** [comment]
I don't understand what your ffmpeg is. There are two input files, one is required.

**Comment by testchik** [comment]
I execute below script:
`shell_exec("ffmpeg -y -i videos/localfile84201711432.mp4 -i videos/Kalimba_Audio.mp3 -shortest -vcodec libx264 -acodec libfaac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k -pass 1 -passlogfile export/localfile84201711432.mp4");`

It is work in localhost, but issue in host upon web server.

**Comment by Romain** [comment]
@testchik, what I understand is that you have a server which you wanna use to execute FFMPEG, but you haven't install FFMPEG on it. Just saying shows you that this is wrong. You cannot execute FFMPEG without installing it. You need to install it on your server first. I recommend that you compile it as described in [this guide](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu) (use the one corresponding to your distribution).
If you cannot install software on your server and don't have any SSH access, you're screwed, you will need to upgrade your server.

Second thing, we cannot include the binaries into this bundle.

Finally, as @jens1o, the feature to merge a video file with an audio file is not ready yet but will come soon.

Thanks.

**Comment by dernawy** [comment]
@testchik 
if on your shared server you don't have a FFmpeg plane, so the script can not work because it will trying to get the (FFmpeg.exe and FFprobe.exe) paths to work then while you don't have access to theses file due to your hosting plane this script will not work, there is a point, that you install the ffmpeg in your home dirctory and to change the paths in the script to this dirctive, NB: on local host (xampp on windows 7 primum) works very good.

**Comment by jens1o** [comment]
closed due to inactivity.
