### ISSUE TITLE
Unable to load FFMpeg : Driver autodetection doesn't work

### ISSUE THREAD

**Issue by adepolas** [PHP-FFMpeg/PHP-FFMpeg#352]
| Q              | A
| -------------- | ---
| Bug?           | maybe
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version |  3.2.4 (in local) / (2.8.11 (in production) 
| OS             | El Capitan (in local) / Ubuntu 16.04 (in production)

#### Actual Behavior

The error "Unable to load FFProbe" was caught.

#### Expected Behavior
Expect the line below should work alone as said in "Basic Usage" from your doc :
 $ffmpeg       = FFMpeg::create(); 

It did not auto-detect the binaries. Then I added the paths to binaries, there was no more error.

#### Steps to Reproduce
It is a Laravel project.

This is the class from the package where FFMpeg was used :
[Thumbnail.php](https://github.com/lakshmaji/Thumbnail/blob/master/src/Thumbnail.php)

The call to Thumbnail::getThumbnail static method launched the error for me.

#### Possible Solutions
I think, the driver's autodetection does not work.

**Comment by jens1o** [comment]
Well, that's not enough information. Where are the drivers located? (When on Windows:) Is it added to the PATH Variable?

**Comment by adepolas** [comment]
In Ubuntu : 
```
$whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz

$echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by jens1o** [comment]
That's strange. By default, it tries to execute ffmpeg and `avconv`, and when it's not there, it tries to find them in some path variables. This pathfinding is **not** handled in this lib, but here:
https://github.com/alchemy-fr/BinaryDriver/blob/master/src/Alchemy/BinaryDriver/AbstractBinary.php#L160-L162

**Comment by adepolas** [comment]
Oh I've opened an issue in the wrong repository ! Thank you @jens1o 👍

**Comment by jens1o** [comment]
Nah, the library is not maintained anymore, and we should look for a maintained lib. Good luck with getting a response!

**Comment by Romain** [comment]
[Here](https://github.com/PHP-FFMpeg/PHP-FFMpeg/#ffmpeg) is the complete way to create a FFMPEG instance:

```php
$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/opt/local/ffmpeg/bin/ffmpeg',
    'ffprobe.binaries' => '/opt/local/ffmpeg/bin/ffprobe',
    'timeout'          => 3600, // The timeout for the underlying process
    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
), $logger);
```
