### ISSUE TITLE
PHP-FFMpeg - How to add transcoding of video files to queue in Laravel 5.3/5.4

### ISSUE THREAD

**Issue by jamesfroud79** [PHP-FFMpeg/PHP-FFMpeg#354]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.9.3
| FFmpeg Version | ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
| OS             | Linux homestead 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Has anyone got any example of how to add the transcoding of video files in the background/queue for Laravel 5.3/5.4?

**Comment by Romain** [comment]
Hi @jamesfroud79,
I'm not exactly sure to understand what you mean by "adding the transcoding to the queue"...
Do you want them to be parallelized with your script?
If yes, I think you should consider externalizing the transcoding into another app that you would request through an API.

**Comment by dmanthing** [comment]
I did it on Laravel 5.2. Store a file after upload and create a model instance in the database that holds a filename. Pass that instance to a Laravel job and let the job do the encode.

**Comment by eberkund** [comment]
This should be closed, it has nothing to do with FFMpeg and more to do with Laravel. You should ask this question on Stackoverflow.

**Comment by jens1o** [comment]
Good point. I forgot that issue here.
