### ISSUE TITLE
Unable to load FFProbe only on Linux

### ISSUE THREAD

**Issue by Scarlicity** [PHP-FFMpeg/PHP-FFMpeg#356]
#### Actual Behavior

Hi! It's me again.
I wanted to get the duration of a video and I made it on Windows by doing this:
`$probe = FFProbe::create();`
`$data['duration'] = floor($probe->format($data['path'])->get('duration'));`
But when I put my project on Linux server, there is a bug: Unable to load FFProbe.
I have installed FFMpeg on my server, you can see:
`[root@weibo-server web]# ffprobe -version`
`ffprobe version 3.3 Copyright (c) 2007-2017 the FFmpeg developers built with gcc 4.8.2 (GCC)`
Then I try this:
`$probe = FFProbe::create([`
`'ffmpeg.binaries'  => '/opt/ffmpeg-3.3/bin/ffmpeg',`
`'ffprobe.binaries' => '/opt/ffmpeg-3.3/bin/ffprobe',`
`]);`
It still not work.
So I want to find a way to solve this problem.
Thank you!

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by Romain** [comment]
Hi @Scarlicity,

Can you give us some details about your environment?
Which version of Linux do you use? How did you install FFMPEG?
Can you try installing FFMPEG by compiling it as described [here](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu)?

**Comment by Tinywan** [comment]
Hi @Romain 
I also have the same problem in linux (Ubuntu 14.0), Windows is ok, do not know what the cause
## error code 
`Unable to load FFProbe`

**Comment by Scarlicity** [comment]
@Tinywan,
Hi, I find a way to solve it, but i do not know whether it can solve your problem.
I think it is an authority problem. You can try 'chmod 777 your-ffmpeg-root-path'.

**Comment by Tinywan** [comment]
@Scarlicity Thank you! It has been solved

**Comment by Scarlicity** [comment]
@Tinywan Are you chinese? Or?

**Comment by Tinywan** [comment]
@Scarlicity yes ,your too？

**Comment by Scarlicity** [comment]
@Tinywan yeal. Two Chinese use English to communicate. That's so funny~

**Comment by Tinywan** [comment]
@Scarlicity Haha, that is also#

**Comment by WhiteSnowGirl** [comment]
`https://ffmpeg.zeranoe.com/builds/` How to solved? just `chmod 777`?How to install in linux?

**Comment by Tinywan** [comment]
@WhiteSnowGirl  Only `Windows or Mac OS`

**Comment by jens1o** [comment]
On Linux, you can install it with your package manager(e.g. `apt`)

**Comment by WhiteSnowGirl** [comment]
thanks

**Comment by ShaoGongBra** [comment]
@Scarlicity @Tinywan 
你们就不能来句中文吗，我也遇到这个问题了，按照你们的方法都不行，要怎么办

**Comment by Tinywan** [comment]
@ShaoGongBra  具体什么问题，请你描写清楚一下

**Comment by ShaoGongBra** [comment]
@Tinywan 
Unable to load FFProbe only
就是这个，我发现了，是我的执行路径写错了
