### ISSUE TITLE
Fastest way to convert videos

### ISSUE THREAD

**Issue by adepolas** [PHP-FFMpeg/PHP-FFMpeg#357]
Actually my conversion script for videos is using your package this way :
```
    $ffmpeg   = FFMpeg::create(
                    [
                        'ffmpeg.binaries'  => getenv('FFMPEG_PATH').'/ffmpeg',
                        'ffprobe.binaries' => getenv('FFMPEG_PATH').'/ffprobe',
                        'timeout'          => 3600,
                        'ffmpeg.threads'   => 12,
                    ]
                );
                $video = $ffmpeg->open($original_path_here);
                $format = new X264();
                $format->setAudioCodec('libmp3lame');
                $video->save($format, $converted_path_here);
```

But the conversion is quite long for each (less than 1 minute) video. Is there any options to improve the conversion time ?

**Comment by Romain** [comment]
Hi @adepolas,
Your code seems good.
I don't think that you can optimize your code.
If you want to improve performances, you will have to increase the resources of your machine.
It also depends on the way your file is encoded.
I hope this helps.

**Comment by jens1o** [comment]
closed due to inactivity.
