### ISSUE TITLE
Trouble with firefox 53

### ISSUE THREAD

**Issue by Defunktt1** [PHP-FFMpeg/PHP-FFMpeg#358]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | last verison
| FFmpeg Version | ffmpeg 3.3
| OS             | Archlinux x64 4.10.11-1

When I convert video file to mp4 and change  resolution, in firefox 53 (f50 and opera v44 too) I have black screen instead of video. Audio works fine. 

`$video = $ffmpeg->open($videoPath);`
`$video->filters()`
            `->resize(new Dimension($width, $height))`
            `->synchronize();`
`$format = new X264();`
`$format->setAudioCodec('libmp3lame');`
`$video->save($format, $videoOutPath);`

On VLC and Google chrome all works fine.

**Comment by jens1o** [comment]
Cannot reproduce, can you give us the file itself so I can reproduce, too?

**Comment by Defunktt1** [comment]
It was a problem with ffmpeg. When I updated the package, everything began to work fine.
