### ISSUE TITLE
file_exists(): open_basedir restriction in effect. File(/usr/bin/ffprobe) 

### ISSUE THREAD

**Issue by dinhchuong7913** [PHP-FFMpeg/PHP-FFMpeg#361]
Hi ,
I get error 
file_exists(): open_basedir restriction in effect. File(/usr/bin/ffprobe) is not within the allowed path(s): (/home/project/public_html:/home/project/tmp)
how to fix it??

**Comment by jens1o** [comment]
Change the owner of the `tmp` directory, so it belongs to the user which is executing php. (Mostly `www-data`)

**Comment by dinhchuong7913** [comment]
I using nginx and run chown nginx:nginx already but still this issue

**Comment by jens1o** [comment]
Who's executing the php binary?

**Comment by dinhchuong7913** [comment]
I dont understand clearly?? exce right??

**Comment by jens1o** [comment]
Okay, another question: Do you use FPM?

**Comment by dinhchuong7913** [comment]
Not my server so I am not sure, I checked, it not use FPM

**Comment by jens1o** [comment]
Okay, I would ask the hosting company wether it could allow the path `/home/project/tmp` for php.

**Comment by dinhchuong7913** [comment]
sorry I am confused about this.
My local, I use wamp, install ffmpeg, ervery things is ok but on server have this issue when I want get thumbnail and connver video.
I searched but not find solution.
please teach me more detail, thanks

**Comment by jens1o** [comment]
Yeah, it is correct. Just try it out.

**Comment by dinhchuong7913** [comment]
I try already but still this issue

**Comment by asyncpjax** [comment]
My same problem has been resolved .
[http://www.iamle.com/archives/1609.html](url)

**php-fpm.conf :**

`env[TMP] = /tmp/
env[TMPDIR] = /tmp/
env[TEMP] = /tmp/
php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f webmaster@qq.com
php_admin_value[open_basedir] = /home/wwwroot/:/tmp/:/var/tmp:/proc/
php_admin_value[session.save_path] = /tmp/
php_admin_value[upload_tmp_dir] = /tmp/
slowlog = /usr/local/php/var/log/$pool.log
request_slowlog_timeout = 3s`

**在nginx 配置 fastcgi_param参数**
`fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/:/tmp/:/proc/";`

**Comment by jens1o** [comment]
closed due to inactivity.

**Comment by masoudline** [comment]
I have the same issue on nginx laravel centos 
I use ffmpeg command and its work fine but when I want to save my data from backend panel these errors show:
```
"file_exists(): open_basedir restriction in effect. File(/usr/bin/ffprobe) is not within the allowed path(s): (/home/roxo/:/tmp/:/var/tmp/:/usr/local/php72/lib/:/usr/local/php54/lib/:/usr/local/php55/lib/:/usr/local/php56/lib/:/usr/local/php70/lib/:/usr/local/php71/lib/:/usr/local/lib/php/)"
```

**Comment by jens1o** [comment]
@masoudline Turn off php's `safe_mode`.
