### ISSUE TITLE
Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutableNotFoundException' with message 'Executable not found, proposed : avprobe, ffprobe' in D:\xampp\htdocs\d\trunk\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php:160

### ISSUE THREAD

**Issue by ruhong65** [PHP-FFMpeg/PHP-FFMpeg#370]
Hi all

I just finished  composer install the FFmpeg ,、then i run the script just got the error ,below is the information:

Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutableNotFoundException' with message 'Executable not found, proposed : avprobe, ffprobe' in `D:\xampp\htdocs\d\trunk\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php:160`

my `code:`

	function testff(){

		$ffmpeg = FFMpeg\FFMpeg::create();

		var_dump($ffmpeg);
		exit;
		$audio = $ffmpeg->open('track.mp3');

		$format = new FFMpeg\Format\Audio\Flac();
		$format->on('progress', function ($audio, $format, $percentage) {
		    echo "$percentage % transcoded";
		});

		$format
		    ->setAudioChannels(2)
		    ->setAudioKiloBitrate(256);

		$audio->save($format, 'track.flac');
	}

can anyone help me this ? thanks

**Comment by ruhong65** [comment]
Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffprobe failed to execute command "./vendor/ffmpeg/bin/ffprobe.exe" 1.mp3 -show_streams -print_format json' in D:\xampp\htdocs\d\trunk\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php:100 Stack trace: #0 D:\xampp\htdocs\d\trunk\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure('"./vendor/ffmpe...') #1 D:\xampp\htdocs\d\trunk\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #2 

what's this problem?
i want change the mp3 to flac . 

	$audio = $ffmpeg->open('1.mp3');

		$format = new FFMpeg\Format\Audio\Flac();

		$format->on('progress', function ($audio, $format, $percentage) {
		    echo "$percentage % transcoded";
		});
		$format
		    ->setAudioChannels(2)
		    ->setAudioKiloBitrate(256);

		$audio->save($format, 'track.flac');

**Comment by ruhong65** [comment]
fixed ,please closed

**Comment by jens1o** [comment]
You can do that yourself. ;)

**Comment by sahadatfci** [comment]
How you fixed this. Can you please explain. I am also having the same problem.

**Comment by ruhong65** [comment]
you should write the 

$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/opt/local/ffmpeg/bin/ffmpeg',
    'ffprobe.binaries' => '/opt/local/ffmpeg/bin/ffprobe',
    'timeout'          => 3600, // The timeout for the underlying process
    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
), $logger);

give write path

**Comment by jens1o** [comment]
@sahadatfci Also, check whether ffmpeg is installed at all, since this project is just a wrapper around it.

**Comment by anaouda** [comment]
please help 
i'm working on windows 10 
i provided the path 
$ffmpeg = FFMpeg\FFMpeg::create(array(
        'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe',
        'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprope.exe',
        'timeout'          => 3600, // The timeout for the underlying process
        'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
    ), @$logger);
but still got this error 


Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutableNotFoundException' with message 'Executable not found, proposed : C:/FFmpeg/bin/ffprope.exe' in C:\xampp\htdocs\videoConvert\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php:160 Stack trace: #0 C:\xampp\htdocs\videoConvert\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load('C:/FFmpeg/bin/f...', NULL, Object(Alchemy\BinaryDriver\Configuration)) #1 C:\xampp\htdocs\videoConvert\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFProbe.php(226): FFMpeg\Driver\FFProbeDriver::create(Array, NULL) #2 C:\xampp\htdocs\videoConvert\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFMpeg.php(117): FFMpeg\FFProbe::create(Array, NULL, NULL) #3 C:\xampp\htdocs\videoConvert\index.php(18): FFMpeg\FFMpeg::create(Array, NULL) #4 {main} Next exception 'FFMpeg\Exception\ExecutableNotFoundException' with message 'Unable to load FFProbe' in C:\xampp\htdocs\videoConvert\vendor\php-ffmpeg\php-ffmpeg\src\FFMp in C:\xampp\htdocs\videoConvert\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php on line 50

**Comment by jens1o** [comment]
Is ffmpeg/ffprobe installed?

**Comment by anaouda** [comment]
### working fine bro
i put 
ffmpeg in folder C:/FFmpeg/bin/ffmpeg.exe and 
ffprope in C:/FFmpeg/bin/ffprope.exe 
and added the path C:/FFmpeg/bin/ to environment variables
after refresh and cleaning cache it's working fine now

thanks for replay

**Comment by jens1o** [comment]
closed due to inactivity.

**Comment by mariohandsome** [comment]
> Is ffmpeg/ffprobe installed?

How to install that?

**Comment by jens1o** [comment]
@mariohandsome This varies from the operating system you're using, you can ask your favorite search engine for that (mine is DuckDuckGo).

**Comment by mayurkidi** [comment]
i have this same error almost try all of above solutions but not working. 

 C:\xampp\htdocs\test-project\test\vendor\php-ffmpeg\php-ffmpeg\src\Alchemy\BinaryDriver\AbstractBinary.php:159
      Alchemy\BinaryDriver\Exception\ExecutableNotFoundException::("Executable not found, proposed : C:\FFmpeg\bin")

  C:\xampp\htdocs\test-project\test\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFMpegDriver.php:53
      Alchemy\BinaryDriver\AbstractBinary::load(Object(Illuminate\Log\LogManager), Object(Alchemy\BinaryDriver\Configuration))
