### ISSUE TITLE
Keep original video's bitrate?

### ISSUE THREAD

**Issue by user23145** [PHP-FFMpeg/PHP-FFMpeg#374]
How can I keep the original video's bitrate?

**Comment by jens1o** [comment]
Use ffprobe to get the values and set it to the format.

**Comment by hub20xx** [comment]
@jens1o Could you give an example please? 

Or maybe @user23145 solved it and could help?

I'm trying to keep the audio and video settings unchanged (modified other things in the video but don't want to transcode).

I cannot find a way to extract the format from `ffprobe` and to use it so that I could do something like `$video->save($format, 'newVideo.mp4');` (I tried `$ffprobe->format($videoPath)->get('format')` but it does not seem to be the way...)

**Comment by jens1o** [comment]
@hub20xx Sure, here to help:
```php
<?php
require_once './vendor/autoload.php';

$probe = FFMpeg\FFProbe::create();

$bitRate = $probe
    ->streams('video.mp4')
    ->videos()
    ->first()
    ->get('bit_rate') / 1024;
    
// open actual video
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('video.mp4');

$format = new FFMpeg\Format\Video\X264;
$format->setKiloBitrate($bitRate);

$video->save($format, 'myFancyVideo.mp4');
```

Does it work for you? Maybe we should explore into keeping everything in default when it hasn't been changed...

**Comment by hub20xx** [comment]
@jens1o Thank you for your help!

I tried your solution like this (with the watermark):

```
<?php
require_once './vendor/autoload.php';

$probe = FFMpeg\FFProbe::create();

$videoPath = __DIR__ . '/input.mp4';
$imagePath = __DIR__ . '/watermark.png';
$newVideoPath = __DIR__ . '/output.mp4';

$bitRate = $probe
    ->streams($videoPath)
    ->videos()
    ->first()
    ->get('bit_rate') / 1024;
    
// open actual video
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open($videoPath);

// add watermark
$video->filters()->watermark($imagePath, [
    'position' => 'relative',
    'bottom' => 20,
    'right' => 50
]);

// set format
$format = new FFMpeg\Format\Video\X264;
$format->setKiloBitrate($bitRate);

$video->save($format, $newVideoPath);
```
and I got the error:
```
PHP Fatal error:  Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-i' '/home/myuser/code/input.mp4' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '499k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' 'movie=/home/myuser/code/watermark.png [watermark];[in][watermark] overlay=main_w - 50 - overlay_w:main_h - 20 - overlay_h [out]' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes598bfcf4209326coz2/pass-598bfcf4209b9' '/home/myuser/code/output.mp4' in /home/myuser/code/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100
Stack trace:
#0 /home/myuser/code/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffmpe.. in /home/myuser/code/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php on line 228

shell returned 255
```
My video and watermark files seem ok, I tried to do something similar from the command line and it works:
```
ffmpeg -i input.mp4 -i watermark.png -filter_complex "overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -codec:a copy output.mp4
```

**Comment by jens1o** [comment]
It's working for me. Could you try the following command to explore what's wrong?
`/usr/bin/ffmpeg -y -i /home/myuser/code/input.mp4 -vcodec libx264 -acodec libfaac -b:v 499k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k -vf movie=/home/myuser/code/watermark.png [watermark];[in][watermark] overlay=main_w - 50 - overlay_w:main_h - 20 - overlay_h [out] -pass 1/home/myuser/code/output.mp4`.

**Comment by jens1o** [comment]
Closed due to inactivity.
