### ISSUE TITLE
Unable to save frame as image

### ISSUE THREAD

**Issue by Mehrdad-Dadkhah** [PHP-FFMpeg/PHP-FFMpeg#378]
Hi.

I want save one frame of video as image. I use this code:

```
$ffmpeg = FFMpeg::create(array(
            'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/bin/ffprobe',
            'timeout'          => 360000, // The timeout for the underlying process
            'ffmpeg.threads'   => 16, // The number of threads that FFMpeg should use
        ));

        $video = $ffmpeg->open($url);
        return $video->frame(TimeCode::fromSeconds($time))->save(public_path() . '/videos/res_thumbs/' . $filename . '.jpg');
```

but it throw a exception:

> RuntimeException in Frame.php line 132:
> Unable to save frame

I trace code and dump generated command at Frame.php line 119. it generate this command:

`-y -ss 00:00:26.67 -i /var/www/html/public/videos/2017/07/04/15-28-14-595b74c6f3746.mp4 -vframes 1 -f image2 /var/www/html/public/videos/res_thumbs/15-28-14-595b74c6f3746G.jpg`

when I run it manually in command line it generate image successfully!

what's wrong?

my FFmpeg version:

> ffmpeg version N-86695-g0a24d7c Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 4.9.2 (Debian 4.9.2-10)

**Comment by jens1o** [comment]
Does only this feature does not work or do you have a general problem?

**Comment by Mehrdad-Dadkhah** [comment]
@jens1o 
thanks for follow up

Yes, I have problem only with this feature. I use duration feature with this code and it's work good:

```
$ffprobe = FFProbe::create(array(
            'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/bin/ffprobe',
            'timeout'          => 360000, // The timeout for the underlying process
            'ffmpeg.threads'   => 16,   // The number of threads that FFMpeg should use
        ));


        return round($ffprobe->format($url)->get('duration'));
```

**Comment by Mehrdad-Dadkhah** [comment]
I update my package (PHP-FFmpeg) from 0.9.3 to 0.9.5 and problem resolved!

**Comment by Nehadigi** [comment]
HI,
Please help me to resolve the error:-
 ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffprobe' '-y' '-ss' '00:00:05.00' '-i' '/home/dmlabs-5/iasp/IASP_platform/web/uploads/media/default/0001/01/529d9972c548e552271728e915cbbf98c9514f13.mp4' '-vframes' '1' '-f' 'image2' '/home/dmlabs-5/iasp/IASP_platform/web/uploads/media/default/0001/01/529d9972c548e552271728e915cbbf98c9514f13.jpg'

**Comment by Nehadigi** [comment]
HI,
Please help me to resolve the error:-
 ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffprobe' '-y' '-ss' '00:00:05.00' '-i' '/home/dmlabs-5/iasp/IASP_platform/web/uploads/media/default/0001/01/529d9972c548e552271728e915cbbf98c9514f13.mp4' '-vframes' '1' '-f' 'image2' '/home/dmlabs-5/iasp/IASP_platform/web/uploads/media/default/0001/01/529d9972c548e552271728e915cbbf98c9514f13.jpg'

**Comment by jens1o** [comment]
@Nehadigi Please create a new issue. Thanks :)
