### ISSUE TITLE
Failed to Encode X264

### ISSUE THREAD

**Issue by chantrea** [PHP-FFMpeg/PHP-FFMpeg#379]
Encoding failed
--
in Video.php (line 228)
at Video->save(object(X264), '/path/to/storage/uploads/users/videos/20170706122719.mp4')
fmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/tmp/phpKagNEA' '-async' '1' '-metadata:s:v:0' 'start_time=0' '-threads' '1' '-vcodec' 'libx264' '-acodec' 'aac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' '[in]scale=640:320 [out]' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes595e2ca8292fa6xbbg/pass-595e2ca8295fd' '/path/to/storage/uploads/users/videos/20170706122719.mp4'

I also tried different available acodec but still no luck.

And here is my ffmpeg version
ffmpeg version N-86720-gf1baafa Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-9)
  configuration: 
  libavutil      55. 67.100 / 55. 67.100
  libavcodec     57.100.103 / 57.100.103
  libavformat    57. 75.100 / 57. 75.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 94.100 /  6. 94.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
Hyper fast Audio and Video encoder

Moreover is that possible for method save to save the video file direct to amazon S3?

**Comment by ferryvg** [comment]
Run this command in console:
`/usr/local/bin/ffmpeg '-y' '-i' '/tmp/phpKagNEA' '-async' '1' '-metadata:s✌️0' 'start_time=0' '-threads' '1' '-vcodec' 'libx264' '-acodec' 'aac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' '[in]scale=640:320 [out]' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes595e2ca8292fa6xbbg/pass-595e2ca8295fd'`

If error is "_Unknown encoder 'libfaac'_" you need manul compile ffmpeg with libfaac

**Comment by chantrea** [comment]
Can you please let me know what is the step to do that? Because I need to use that to convert video from users upload and the goal is to support for every browser and devices I already tried in different ffmpeg version but still no luck. And moreover is that possible in save method after video converted then auto upload to amazon s3.

Best Regards,
Chantrea

**Comment by ferryvg** [comment]
You need sign in to server over ssh and run command:
`/usr/local/bin/ffmpeg '-y' '-i' '/tmp/phpKagNEA' '-async' '1' '-metadata:s✌️0' 'start_time=0' '-threads' '1' '-vcodec' 'libx264' '-acodec' 'aac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' '[in]scale=640:320 [out]' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes595e2ca8292fa6xbbg/pass-595e2ca8295fd'`

**Comment by ferryvg** [comment]
> /path/to/storage/
This is default value for some config. You using Laravel? :)

**Comment by ferryvg** [comment]
If you using Laravel: upgrade php to 7.0/7.1 and use this package https://github.com/pascalbaljetmedia/laravel-ffmpeg

**Comment by chantrea** [comment]
Yeah I am using laravel 5.4

**Comment by jens1o** [comment]
@chantrea Does it work for you when you use that wrapper @ferryvg proposed?

**Comment by jens1o** [comment]
sorry, wrong button

**Comment by chantrea** [comment]
It is still an issue but it is different thing I also open the ticket at the wrapper @ferryvg proposed. Will be appreciated if you could answer this too

https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/21

**Comment by ferryvg** [comment]
libfaac is non-free package. Use another audio codec, ex. 
`new X264('libfdk_aac')`

**Comment by chantrea** [comment]
I already used the libfdk_aac but it is still the same issue.

**Comment by jens1o** [comment]
May you execute the command @ferryvg suggested, so we have something to work with? :)

**Comment by ferryvg** [comment]
@chantrea, you must change right path to source and destination files. Using help function like storage_path for it.

Please, give php code and laravel configs for more details.

**Comment by chantrea** [comment]
Here is my code in Laravel 5.4
$uploadedFile = $request->file('post_video_upload');
$timestamp = date('YmdHis');
FFMpeg::open($uploadedFile->getRealPath())
->addFilter(function ($filters) {
$filters->resize(new \FFMpeg\Coordinate\Dimension(640, 480));
})
->export()
->toDisk('s3')
->inFormat(new \FFMpeg\Format\Video\WMV)
->save('users/videos/'.$timestamp."wmv")
// export to Amazon S3, converted in X264
->export()
->inFormat(new \FFMpeg\Format\Video\X264)
->save('users/videos/'.$timestamp."mp4")
->export()
->inFormat(new \FFMpeg\Format\Video\WebM)
->save('users/videos/'.$timestamp."webm")
;

**Comment by chantrea** [comment]
the problem is the library cannot read from the source it defaults to storage path but I am getting the file from user upload, not the storage path.

**Comment by ferryvg** [comment]
@chantrea, what the error you have?

**Comment by chantrea** [comment]
Unable to probe /app/storage/....

But actually is wrong path like I mention because I am getting file from user upload so the path should be like that /tmp/phpa344x something like that. I checked the details of function fromDisk it has default to storage path. 

Best Regards,
Chantrea

**Comment by ferryvg** [comment]
/app/storage is strange path for laravel and is absolute path of server
Good path is [/path/to/laravel]/storage/app

Please give me composer.json file and config/filesystem.php (without S3 key and secret) for that can i help you

**Comment by chantrea** [comment]
But the problem is the file is located in /tmp folder that is Linux apache php default when users upload the file.

Best Regards,
Chantrea

**Comment by ferryvg** [comment]
Problem in your envirovment, not vendor packages. I don't help you without more details

**Comment by chantrea** [comment]
Is that possible that we can do screen share on skype?

My skype is wattanak2015

**Comment by jens1o** [comment]
Please come up with a problem where this wrapper is causing. Without more pieces of  information, we can't help. Closing for now.
