### ISSUE TITLE
Custom Filters

### ISSUE THREAD

**Issue by RatFou** [PHP-FFMpeg/PHP-FFMpeg#381]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | last
| FFmpeg Version | last
| OS             | linux wheezy (7.2)

Hi, I tried to add custom filters without success. For example, I tried to apply a blur an a scale2ref filter but I don't know where to put them. Anyone already succeded to apply custom filters?

**Comment by jens1o** [comment]
Can you show us your code?

**Comment by RatFou** [comment]
Sure :)

```
$video
    ->filters()
    ->custom('boxblur','5:1');
```

**Comment by jens1o** [comment]
That looks right. How do you save your video? We can only apply the filters when you save it somewhere.

> Hint: Do not use the same filename.

**Comment by RatFou** [comment]
`$video
    ->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4');`

**Comment by jens1o** [comment]
Ah, wait.
Your code is actually wrong, but it looks right...
You need to do it like this:
```
$video
    ->filters()
    ->custom('-boxblur 5:1');
```

**Comment by RatFou** [comment]
Thank you but I have this error in my logs with this code : Uncaught exception `'Alchemy\\BinaryDriver\\Exception\\ExecutionFailureException' with message 'ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' 'test-video.mp4' '-async' '1' '-metadata:s:v:0' 'start_time=0' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' 'movie=img/logo-white.png [watermark];[in]scale=1080:768 [p0];[p0]-boxblur 5:1[p1];[p1][watermark] overlay=main_w - 50 - overlay_w:main_h - 50 - overlay_h [out]' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes596249b343c13m3it8/pass-596249b343dac' 'export-x264.mp4'`

My full code:
```
require_once("lib/FFMpeg/vendor/autoload.php");
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('test-video.mp4');

/* Force 1080p */
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(1080, 768))
    ->synchronize();
/* Force 1080p */

/* Get Thumbnail */
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(5))
    ->save('frame.jpg');
/* Get Thumbnail */

/* Blur */
$video
    ->filters()
    ->custom('-boxblur 5:1');
/* Blur */

/* Add Watermark */
$video
    ->filters()
    ->watermark(URL_IMG."logo-white.png", array(
        'position' => 'relative',
        'bottom' => 50,
        'right' => 50,
		//'scale2ref' => '(110/43)iw/8:ih/8',
		//'boxblur' => '5:1',
    ));
/* Add Watermark */

/* Save video */
$video
    ->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4');
/* Save video */
```

**Comment by jens1o** [comment]
Can you execute this command on the shell and tell us the output?
`/usr/local/bin/ffmpeg -y -i test-video.mp4 -async 1 -metadata:s:v:0 start_time=0 -vcodec libx264 -acodec libfaac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -
flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k -vf movie=img/logo-white.png [watermark];[in]scale=1080:768 [p0];[p0]-box
blur 5:1[p1];[p1][watermark] overlay=main_w - 50 - overlay_w:main_h - 50 - overlay_h [out] -pass 1 -passlogfile /tmp/ffmpeg-passes596249b343c13m3it8/pass-596249b34
3dac export-x264.mp4`

**Comment by RatFou** [comment]
I have this error : ```[NULL @ 0x313bf80] Unable to find a suitable output format for 'pipe:'
pipe:: Invalid argument```

**Comment by RatFou** [comment]
The full output:
`ffmpeg version 1.0.10 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jul  8 2017 11:31:05 with gcc 4.7 (Debian 4.7.2-5)
  configuration: --enable-gpl --enable-nonfree --enable-libfaac --enable-libgsm --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-zlib --enable-postproc --enable-swscale --enable-pthreads --enable-x11grab --enable-libdc1394 --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb
  libavutil      51. 73.101 / 51. 73.101
  libavcodec     54. 59.100 / 54. 59.100
  libavformat    54. 29.104 / 54. 29.104
  libavdevice    54.  2.101 / 54.  2.101
  libavfilter     3. 17.100 /  3. 17.100
  libswscale      2.  1.101 /  2.  1.101
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/test-video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:00:08.80, start: 0.000000, bitrate: 310 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 272x480 [SAR 1:1 DAR 17:30], 209 kb/s, 30.11 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, s16, 93 kb/s
    Metadata:
      handler_name    : SoundHandler
[NULL @ 0x1a21440] Unable to find a suitable output format for 'pipe:'
pipe:: Invalid argument
-bash: [in]scale=1080:768: command not found
-bash: [p0]-box: command not found
-bash: [p1][watermark]: command not found`

**Comment by RatFou** [comment]
I replaced `- flag` by `-flag` and now I have this error: `5100] Unable to find a suitable output format for '[watermark]'
[watermark]: Invalid argument`

**Comment by jens1o** [comment]
Okay, then you need to get your hands dirty and remove all double spaces... Will do this tomorrow, I need to learn for my last freakin' class test. Then I'm done and I can spend all my time into this 😍

**Comment by RatFou** [comment]
There is no double space anymore ;)

**Comment by jens1o** [comment]
You see, I don't have enough time... Sorry. I'll look into this later. Maybe someone else has an idea... I'm afraid, but I have to do my work. :/

**Comment by RatFou** [comment]
Don't worry, I will find a solution and post it here as soon as possible ;)

**Comment by RatFou** [comment]
This filter works:
```
$video
			->filters()
			->custom(' boxblur=10:9 ');
```

**Comment by jens1o** [comment]
Thanks! Will take this into account once there is a related issue. :)
