### ISSUE TITLE
Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in 

### ISSUE THREAD

**Issue by karenshahmuradyan** [PHP-FFMpeg/PHP-FFMpeg#383]
Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in C:\xampp1\htdocs\ffmpeg-3.3.2\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php:160 Stack trace: #0 C:\xampp1\htdocs\ffmpeg-3.3.2\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration)) #1 C:\xampp1\htdocs\ffmpeg-3.3.2\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFProbe.php(207): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), NULL) #2 C:\xampp1\htdocs\ffmpeg-3.3.2\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFMpeg.php(117): FFMpeg\FFProbe::create(Array, NULL, Object(Doctrine\Common\Cache\ArrayCache)) #3 C:\xampp1\htdocs\ffmpeg-3.3.2\index.php(4): FFMpeg\FFMpeg::create() #4 {main} Next FFMpeg\Exception\ExecutableNotFoundException: Unable to load FFProbe in C:\xampp1\htdocs\ffmpeg-3.3.2\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver in C:\xampp1\htdocs\ffmpeg-3.3.2\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php on line 50

`<?php
require 'vendor/autoload.php;
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('test.mp4');
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();
`

**Comment by jens1o** [comment]
Please fill out the issue template, so we can help you properly... On what OS are you? Which version?

**Comment by karanshahmuradyan** [comment]
Is it possible that I sent you my teamviewer code and you installed it on my computer?

**Comment by jens1o** [comment]
I'm sorry, but I don't understand what you mean?

**Comment by karenshahmuradyan** [comment]
Can you connect to my computer and install it by yourself?

**Comment by jens1o** [comment]
I'm sorry, but we're an open-source project, which means that all communication is public as well, so we don't offer personal support, so we can avoid duplicates. Please provide a real-world example so I can reproduce, and I will reopen this issue.

**Comment by karenshahmuradyan** [comment]
ok, thank you
