### ISSUE TITLE
Can I create multiple custom filters on an image then overlay to the video

### ISSUE THREAD

**Issue by Jasonspd** [PHP-FFMpeg/PHP-FFMpeg#386]
Is it possible to add multiple custom filters on an image and overlay it to the video? In the command below it has to refer to the input. If it possible to add filters to the image first, then I still need to add all those filters to video eventually. Is there a solution for this?

Commands I will be using: rotate, scale, fade, drawbox, drawtext. Literally making things fly over a video D:

Command example:
ffmpeg -i video.mp4 -loop 1 -i image.jpg -filter_complex \ "[1]scale=-1:600[i0]; \ [i0]drawbox=color=white:t=15[i1]; \ [i1]format=yuva420p,fade=in:st=0.4:d=0.2:alpha=1,fade=t=out:st=4.1:d=0.2:alpha=1[i2]; \ [i2]rotate='0.1*sin(20*PI/50*t)':ow=rotw(iw):oh=roth(ih):c=black@0[i3]; \ [0][i3]overlay=x='if(lte(-w+(t-0.3)*2500,0),-w+(t-0.3)*2500,0)':y=-60:shortest=1" \ -c:v libx264 -vb 10M output.mp4

**Comment by jens1o** [comment]
Afaik, this handler does not provide that awesome way to accomplish this if you don't want to split up and/or use the simplefilters...
