### ISSUE TITLE
how to get bitrate from music?

### ISSUE THREAD

**Issue by ruhong65** [PHP-FFMpeg/PHP-FFMpeg#387]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | maybe
| Version Used   | least
| FFmpeg Version | 3.1.4 
| OS             | centos

I did not find how to get bitrate from music? anyone know?

**Comment by jens1o** [comment]
You need to play a little as soon as I got time.

`var_dump`ing https://github.com/PHP-FFMpeg/PHP-FFMpeg#ffprobe with your opened audio file should give you the key.

**Comment by jens1o** [comment]
closed due to inactivity.
