### ISSUE TITLE
the --threads 12 not work ,

### ISSUE THREAD

**Issue by ruhong65** [PHP-FFMpeg/PHP-FFMpeg#388]
| Q              | A
| -------------- | ---
| Bug?           | maybe
| New Feature?   | maybe
| Version Used   | latest
| FFmpeg Version | 3.1.4
| OS             | Your OS and version

Hey, everyone.

I just found when I use --threads 12 it's see not work?

top -H
Cpu0  :  2.0%us,  1.0%sy,  0.0%ni, 96.7%id,  0.3%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu1  :  1.0%us,  0.7%sy,  0.0%ni, 98.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu2  :100.0%us,  0.0%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu3  :  0.3%us,  0.0%sy,  0.0%ni, 99.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  16334284k total, 11951960k used,  4382324k free,   552792k buffers
Swap:        0k total,        0k used,        0k free, 10246436k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
31744 admin     20   0  942m  36m 4600 R 99.7  0.2   0:10.11 ffmpeg

ps -aux | grep ffmpeg

admin    32354 88.8  0.1 934660 17692 ?        Sl   18:11   0:10 /var/tmp/ffmpeg -y -i upload/song_url/2016/07/song_url_1_2016_07_01_12_19_36.mp3 -threads 12 -acodec libmp3lame -b:a 128k -ac 2 upload/song_url/2016/07/song_url_1_2016_07_01_12_19_36_128.mp3

It's very slow and take lots of CPU resource,  Can anyone help me on this?

**Comment by jens1o** [comment]
Adding more threads without having more cpu cores results in the negative effect. In ideal cases, each processor core should have one thread to handle. So, you may want to set you want to use 4 cores.
