### ISSUE TITLE
Question re: segment_time + Add Filter

### ISSUE THREAD

**Issue by frisch1** [PHP-FFMpeg/PHP-FFMpeg#389]
First, thank you for the excellent framework. SO much better than doing exec() to hit FFMPEG. Much appreciated.
 
Forgive two likely very basic questions. I’ve been through the docs and the issues, including searching online and off, but I can’t seem to find an answer to these two questions. Since I normally write procedural vs object, I’m likely missing something obvious:
 
1, I normally run my audio through a lowpass filter (--af “lowpass=f=3000”)… for the like of me, I can’t get the structure of the FFMpeg\Media\Audio::addFilter correct. I've tried aping the structure in the unit tests, but it keeps failing with "lowpass" being unknown, so probably structuring it incorrectly.

I can’t seem to find a reference to something like:
ffmpeg -i audio.wav -c copy -map 0 -segment_time 1 -f segment %03d.wav (breaks audio up into 1 second clips).

I’m looping through using clip right now, but that is significantly longer and the –segment time is very useful for analysis (we feed X seconds into different voice analysis algos).
 
My apologies to be a bother. Any pointers would be appreciated. To be clear, only posting after searching in git / googling. Appreciate the time. Thank you again!

**Comment by jens1o** [comment]
All your issues can be solved using the simple filters, but if you'd like to have something provided out-of-the-box, create a separate issue for each one and I'll label it as feature, so once I got more time, I'll fulfill the requests.

Example using simple filters(for the first question):
```
<?php

// load your audio
$mp3 = $ffmpeg->load('myFancyAudio.mp3');
$customFilter = '--af “lowpass=f=3000”';

$mp3->addFilter(new FFMpeg\Filters\Audio\SimpleFilter($customFilter));
// now save it somewhere
```

**Comment by frisch1** [comment]
Thank you. This is excellent. I went wrong both on the addfilter structure and by not using the simplefilter. This works like a charm.
