### ISSUE TITLE
FFMpeg parameter problem:about -threads

### ISSUE THREAD

**Issue by ruhong65** [PHP-FFMpeg/PHP-FFMpeg#391]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | 3.1.4
| OS             | centos6.5

Cpu0  :  2.0%us,  0.7%sy,  0.0%ni, 95.3%id,  2.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu1  : 94.4%us,  0.3%sy,  0.0%ni,  5.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu2  :  2.6%us,  0.3%sy,  0.0%ni, 97.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu3  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu4  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu5  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu6  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu7  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu8  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu9  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu10 :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu11 :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu12 :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu13 :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu14 :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu15 :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  33013432k total,   912268k used, 32101164k free,    25572k buffers
Swap:        0k total,        0k used,        0k free,   374528k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 3978 admin     20   0  933m  25m 4596 R 94.9  0.1   0:02.86 ffmpeg

admin     3978 51.0  0.0 936992 17880 ?        Sl   09:33   0:11 /var/tmp/ffmpeg -y -i upload/song_url/2016/10/song_url_3_2016_10_08_11_44_29.mp3 -threads 12 -acodec libmp3lame -b:a 320k -ac 2 upload/song_url/2016/10/song_url_3_2016_10_08_11_44_29_320.mp3

I think -threads not work?

**Comment by jens1o** [comment]
Well, that looks wrong, yes, but we don't handle these. We just wrap your php code into something that ffmpeg understands, so there's nothing we can do. Please file an issue at ffmpeg itself, not at our end.
