### ISSUE TITLE
Adding watermark and keep audio and video settings unchanged

### ISSUE THREAD

**Issue by hub20xx** [PHP-FFMpeg/PHP-FFMpeg#392]
I'm trying to keep the audio and video settings unchanged (I'm just adding a watermark to the video).

I'd like to leave the video format unchanged.

I cannot find a way to extract the format from the video, as to pass it to `save()`, which seems the only way to save my changes after adding the watermark.

I cannot find a way to extract the format from `ffprobe` and to use it so that I could do something like `$video->save($format, 'newVideo.mp4');`.

I tried `$ffprobe->format($video)->get('format')` but it does not seem to be the way...

Any idea?

Any help / suggestion / advice would be highly appreciated.

Thanks in advance!

**Comment by jens1o** [comment]
Can you show your existing code? Basically, you need to get the format(what is not working for you?) and then you can determine the right class to use as the format. Then you're basically finished.

**Comment by hub20xx** [comment]
@jens1o Thank you for your answer

Here is what I have so far:

```
<?php

require __DIR__ . '/vendor/autoload.php';

$videoPath = __DIR__ . '/input.mp4';
$imagePath = __DIR__ . '/watermark.png';
$newVideoPath = __DIR__ . '/output.mp4';

$ffmpeg = \FFMpeg\FFMpeg::create();
$video = $ffmpeg->open($videoPath);

$ffprobe = \FFMpeg\FFProbe::create();
// THIS IS NOT WORKING... HOW DO I GET THE FORMAT?...
$format = $ffprobe->format($videoPath)->get('format')));

$video->filters()->watermark($imagePath, [
    'position' => 'relative',
    'bottom' => 20,
    'right' => 50
]);

// ... SO THAT I CAN SAVE THE VIDEO?
$video->save($format, $newVideoPath);
```

**Comment by jens1o** [comment]
There is no method `format` on `FFProbe`.

You get the format like this:
```php
<?php
require_once './vendor/autoload.php';

$probe = FFMpeg\FFProbe::create();

$formatString = $probe
    ->streams('video.mp4')
    ->videos()
    ->first()
    ->get('codec_name');

$className = null;
switch($formatString) {
    case 'h264':
        $className = FFmpeg\Format\Video\X264::class;
    break;
    // add your format codecs here
    default:
        throw new \LogicException("Unknown video format {$formatString}");
}
    
// open actual video
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('video.mp4');

$format = new $className;
$format->setKiloBitrate($bitRate);

$video->save($format, 'myFancyVideo.mp4');

**Comment by hub20xx** [comment]
@jens1o Thank you very much!
