### ISSUE TITLE
validate video

### ISSUE THREAD

**Issue by huglester** [PHP-FFMpeg/PHP-FFMpeg#394]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | master

Hello
I am trying to 'fast' validate the image, so I know it passes validation and can be saved to the database.
In the CLI i do:
```bash
ffmpeg -v error -i video.mp4 -map 0:1 -f null - 2>/dev/null
echo $?
```

this command returns status code of 0 - if success.
1 - on error

What would be the 'alternative' in this LIBRARY way? 
I can't seem to find a way to run 'raw' command.

thanks

**Comment by huglester** [comment]
For now I came up with a solution:
```php
$ffprobe = FFProbe::create($config);

        $duration = (int) $ffprobe
            ->format($value->path())
            ->get('duration');

        return $duration > 0;
```

so if duration is more than 1 second -  it's ok

does it seem correct? If so maybe this issue van be close, or maybe some ->validate() method could be implemented?

**Comment by jens1o** [comment]
Yeah, that's a valid approach.... Will implement this as soon as I got more time and more fun implementing those. Somehow, I like writing comments, but I lack of implementing things...

**Comment by jens1o** [comment]
🎉

**Comment by huglester** [comment]
Thank you :)  works
but it would be better if you tag a new version sometime not too late
beeing on dev-master I don't feel good:)

**Comment by jens1o** [comment]
Yeah, that's actually true, but I will check whether I can implement other feature requests until I tag a new version. :)
