### ISSUE TITLE
I am Having problem in saving the converted video

### ISSUE THREAD

**Issue by rizwanayyaz** [PHP-FFMpeg/PHP-FFMpeg#397]
I am watermarking the video problem comes in save function otherwise the code compile alright.             

| Error
RuntimeExceptionEncoding failed
--
in Video.php (line 228)
at Video->save(object(X264), 'C:\\laragon\\www\\blog\\storage\\app\\avatars')in WaterMarkController.php (line 65)
| OS             | Windows 8.1/Laravel 5.4

#### I expect That it should save the video and I have already check many forums there are many having this problem I have tried everything in github and stackoverflow.
Here is my code

$ffmpeg = FFMpeg\FFMpeg::create(array(
            'ffmpeg.binaries'  => 'C:\FFmpeg\bin\ffmpeg.exe',
            'ffprobe.binaries' => 'C:\FFmpeg\bin\ffprobe.exe',
            'timeout'          => 9800, // The timeout for the underlying process
            'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
        ));
$video = $ffmpeg->open( 'C:\laragon\www\blog\storage\app\public\video.mp4' );
       $format = new FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
 $video
                ->filters()
                ->watermark('C:\laragon\www\blog\storage\app\public\pic.jpg', array(
                    'position' => 'relative',
                    'right' => 50,
                    'top' => 50,
                ));
// echo $video->getPathfile();
        $output='C:\laragon\www\blog\storage\app\public';
         $video->save($format,$output);

#### Possible Solutions
May be there is a format issue or another way to save the converted video other than save function.

**Comment by jens1o** [comment]
will have a look... I think something serious broke... don't have time...

**Comment by lgugliotta** [comment]
You need to especific a filename 
**$output='C:\laragon\www\blog\storage\app\public\video1234.mp4';**
$video->save($format,$output);
