### ISSUE TITLE
Class 'FFMpeg\FFMpeg' not found

### ISSUE THREAD

**Issue by Sir-hennihau** [PHP-FFMpeg/PHP-FFMpeg#399]
Hi, 
my PHP script always throws this error:

> Fatal error: Uncaught Error: Class 'FFMpeg\FFMpeg' not found in /var/www/hendrikhausen.com/public_html/hidden/next/upload_scripts/video_dimensions_test.php:3 Stack trace: #0 {main} thrown in /var/www/hendrikhausen.com/public_html/hidden/next/upload_scripts/video_dimensions_test.php on line 3

V1 video_dimensions_test.php
 `$ffmpeg = FFMpeg\FFMpeg::create();`

V2 video_dimensions_test.php

```
 $FFMpeg = FFMpeg\FFMpeg::create([

    'ffmpeg.binaries'  => '/usr/bin/ffmpeg', 

    'ffprobe.binaries' => '/usr/bin/ffprobe',

    'timeout'          => 3600,

    'ffmpeg.threads'   => 12,

]);

```
Both result in the same error.

I installed FFMPEG with 

> sudo apt-get install ffmpeg

Linux "which" is working, too.

> which ffmpeg
> /usr/bin/ffmpeg

> which ffprobe
> /usr/bin/ffprobe

I installed PHP-FFMpeg with

> composer require php-ffmpeg/php-ffmpeg

Anyone knows what I'm doing wrong?

**Comment by jens1o** [comment]
You need to include the composer's autoloader.
`require_once './vendor/autoload.php';`

**Comment by rnicholls** [comment]
Nm. Please ignore. Looks like some dependencies was blocking it. had to run composer install --ignore-platform-reqs
