### ISSUE TITLE
problem to get bit_rate

### ISSUE THREAD

**Issue by SGhazayi** [PHP-FFMpeg/PHP-FFMpeg#400]
hi
i want to convert a .vob video but ffmpeg can't detect bitrate i used this code but its return zero for me:

$details[];
$ffprobe = FFMpeg\FFProbe::create();
$video_properties = $ffprobe->streams('test.vob')->videos()->first();
$details['video']['bit_rate'] = $video_properties->get('bit_rate') / 1000;

**Comment by jens1o** [comment]
Can you share the file, please?

**Comment by SGhazayi** [comment]
how can i upload video here? is it posible? i'm Beginner :))

**Comment by jens1o** [comment]
Upload it to Dropbox, Google, or, when it's a quite small file, you can select it when you click here:
![image](https://user-images.githubusercontent.com/11234139/29807930-5c6f777e-8c96-11e7-8a77-d2e06d93c0e2.png)

**Comment by SGhazayi** [comment]
Thanks Bro ;)
https://drive.google.com/file/d/0BwACtx6W46MLRmppWGxhZ1BZczQ/view?usp=sharing

**Comment by SGhazayi** [comment]
Thanks Bro ;)
https://drive.google.com/file/d/0BwACtx6W46MLRmppWGxhZ1BZczQ/view?usp=sharing

**Comment by jens1o** [comment]
will look into this later this day. :)

Thanks for the file

**Comment by SGhazayi** [comment]
Your wellcome.

**Comment by jens1o** [comment]
It works for me, the bitrate is `3895951 / 1000` = `3895.951`

When it doesn't work for you, it is more likely a ffmpeg but... Are you sure you're on the latest version?
