### ISSUE TITLE
Get execute command(final)

### ISSUE THREAD

**Issue by Mahdi-Mohammadi** [PHP-FFMpeg/PHP-FFMpeg#403]
Hi
I want to get final command to execute on other server
how I can after set all parameter get the command?
thanks

**Comment by jens1o** [comment]
It's not possible, but it would be quite useful for debugging purposes... will have a look as soon as possible...

**Comment by Mahdi-Mohammadi** [comment]
thanks a lot

**Comment by adriangoris** [comment]
That would be a very useful feature - verbose or dry run. Currently my method is to set an additional parameter that I know will cause an error, and see the output in console. For example:
$format->setAdditionalParameters(array('stupidflag', 'iknowthiswontwork'));

**Comment by Mahdi-Mohammadi** [comment]
@adriangoris 
please share more about your solution?
