### ISSUE TITLE
Want reducing video size but it will increase size and decrease video result.

### ISSUE THREAD

**Issue by maheshvora** [PHP-FFMpeg/PHP-FFMpeg#408]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.9.5
| FFmpeg Version | 0.7.0
| OS             | linux Cent Os 6

#### Actual Behavior

I am converting mp4 video into mp4 to reducing the size of the video i want this video in teo diffent size for mobile view and desktop view but after converting it will increase size to double and quality also be decrease.

#### Expected Behavior

I want two different video and i will compromise with quality minimal as it size is define i have already pass all the parameter same as source video having then also size increase quality decrease  with all the same property so please help me to resolve how to convert video that will produce something quality is soft and size will be decrease. 

#### Steps to Reproduce

hear image is display to converting result.
![image](https://user-images.githubusercontent.com/9759713/30261216-1be20714-96e9-11e7-8251-464a5f80d926.png)

#### SOME OF CODE

$video_bit=formatSizeUnits($movie->getVideoBitRate());
$audio_bit=formatSizeUnits($movie->getAudioBitRate());
$audio_channels=$movie->getAudioChannels();
$framewidth =$movie->getFrameWidth();
$frameheight=$movie->getFrameHeight();
$framerate=round($movie->getFrameRate());

$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/sbin/ffmpeg',
    'ffprobe.binaries' => '/usr/sbin/ffprobe',
    'timeout'          => 3600, // The timeout for the underlying process
    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
));

$video = $ffmpeg->open($video_path.'test_video.mp4');

$format = new FFMpeg\Format\Video\X264('aac', 'libx264');
$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage % transcoded";
});

$format
    ->setKiloBitrate($video_bit)
    ->setAudioChannels($audio_channels)
    ->setAudioKiloBitrate($audio_bit);

$format->setAdditionalParameters(array('-profile:v', 'baseline', '-pix_fmt', 'yuv420p'));

$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension($framewidth, $frameheight),FFMpeg\Filters\Video\ResizeFilter::RESIZEMODE_INSET,true)
    ->framerate(new FFMpeg\Coordinate\FrameRate($framerate),1)
        
    ->synchronize();

$video->filters()->addMetadata(["title" => "Cigarsnearme", "track" => 1]);
//$video->filters()->rotate(FFMpeg\Filters\Video\RotateFilter::ROTATE_180); // to rotet the video
//$watermarkPath='FFMpeg\Filters\Video\WatermarkFilter';

$video
    ->filters()
    ->watermark($video_path.'cnm.png', array(
        'position' => 'relative',
        'top' => 5,
        'left' => 5,
    ));

$video->save($format, $video_path.'video.mp4');

#### ORIGINAL VIDEO

[input video.zip](https://github.com/PHP-FFMpeg/PHP-FFMpeg/files/1291581/input.video.zip)

#### OUTPUT VIDEO

[video.zip](https://github.com/PHP-FFMpeg/PHP-FFMpeg/files/1291577/video.zip)

**Comment by jens1o** [comment]
That's valid, because we didn't come to a point where we use the video defaults, but specific rates... I don't know the exact issue number in the moment, but there is one... :c
