### ISSUE TITLE
please give one example 

### ISSUE THREAD

**Issue by lolmore** [PHP-FFMpeg/PHP-FFMpeg#414]
x _x can u give me one example about this code ? 
```
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('video.mpg');
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
    ->save('frame.jpg');
$video
    ->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4')
    ->save(new FFMpeg\Format\Video\WMV(), 'export-wmv.wmv')
    ->save(new FFMpeg\Format\Video\WebM(), 'export-webm.webm');

```
how i can use the code ?
how if i build the code above on main page ?
example .
www.mywebsite.com/index.php < on index php is only the code  in above
and when i try to www.mywebsite.com/index.php , i got some error x _X

could you give the best example for this case ?

**Comment by jens1o** [comment]
Well, it would be quite helpful to see what the error is. Do you have FFMPEG installed?

**Comment by tammyruihuang** [comment]
@lolmore  Sorry to ask you, but how did you post your code in this post? I clicked on <> to insert code, but it didn't recognize my code as a code section. Thanks for your help!

**Comment by jens1o** [comment]
@tammyruihuang See here: https://guides.github.com/features/mastering-markdown/#examples

**Comment by jens1o** [comment]
Closed due to inactivity.
