### ISSUE TITLE
Get FPS/Framerate

### ISSUE THREAD

**Issue by JOOSTR** [PHP-FFMpeg/PHP-FFMpeg#415]
Hey, is there any way I get the FPS/Framerate of the video?

Thanks.

**Comment by jens1o** [comment]
https://github.com/PHP-FFMpeg/PHP-FFMpeg#ffprobe

Yes, and when you var dump an instance, you can see what it has been called or you're doing a dictionary attack and check how the property is called.

**Comment by mondidub** [comment]
> https://github.com/PHP-FFMpeg/PHP-FFMpeg#ffprobe
> 
> Yes, and when you var dump an instance, you can see what it has been called or you're doing a dictionary attack and check how the property is called.

How exactly? And where can I find all the variables ->get(???); that I want to output?
