### ISSUE TITLE
I tried your use your code in my project. I installed it using composer successfully. However When I use it, the class "FFMpeg" was not found. Do you have an autoload file to load all required php files and classes?

### ISSUE THREAD

**Issue by tammyhuang** [PHP-FFMpeg/PHP-FFMpeg#416]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by tammyruihuang** [comment]
I am reeeealy sorry that I left my descriptions in the title. I tried to change it, however I didn't find edit function to my issue.

**Comment by jens1o** [comment]
May you show your code please?

**Comment by tammyruihuang** [comment]
Sorry I didn't get back to you earlier. I was busy this weekend. Here's my code:

`<?php

# Includes the autoloader for libraries installed with composer
# This was added by Google Cloud API.
require __DIR__ . '/vendor/autoload.php';

use ffmpeg\src\FFMpeg\FFMpeg

# The name of the audio file to transcribe
$fileName = __DIR__ . '/audiofiles/trimmedClip.wav';

$ffmpeg = FFMpeg\FFMpeg::create();
$audio = $ffmpeg->open($filename);

$format = new FFMpeg\Format\Audio\Flac();
$format->on('progress', function($audio, $format, $percentage) {
   echo "$percentage % transcoded"; 
});

$format
    ->setAudioChannels(2)
    ->setAudioKiloBitrate(256);

$audio->save($format, 'trimmedClip.flac');

return true;

?>
`

**Comment by jens1o** [comment]
Please read the README file and please do not insert code as a screenshot.

HINT: The namespace is wrong.

**Comment by tammyruihuang** [comment]
I am pretty new to PHP. Sorry for some of my stupid questions/issues. I started a new project today, and I run composer again. I wrote an index.php as follows. I copied my sample wav file to the same directory as index.php. After all these, I run the index.php in my terminal: php index.php, and I did get the converted FLAC file successfully. 

```
<?php
require __DIR__ . '/vendor/autoload.php';

$ffmpeg = FFMpeg\FFMpeg::create();
$audio = $ffmpeg->open('trimmedClip.wav');

$format = new FFMpeg\Format\Audio\Flac();
$format->on('progress', function ($audio, $format, $percentage) {
    echo "$percentage % transcoded";
});

$format
    ->setAudioChannels(2)
    ->setAudioKiloBitrate(256);

$audio->save($format, 'trimmedClip.flac');

?>

```

However, when I run index.php in Chome at the address: localhost:8888/converterFLAC/index.php (I use MAMP), I received another fatal error:

> Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:160 Stack trace: #0 /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration)) #1 /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(207): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), NULL) #2 /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(117): FFMpeg\FFProbe::create(Array, NULL, Object(Doctrine\Common\Cache\ArrayCache)) #3 /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/index.php(4): FFMpeg\FFMpeg in /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php on line 50

> 

Did I do something wrong?

**Comment by jens1o** [comment]
Okay, that's something to work with. :)

Do you have ffmpeg installed?

**Comment by tammyruihuang** [comment]
Yes, I run "$ composer require php-ffmpeg/php-ffmpeg" succefully. Is there another way to install ffmpeg?

In my project, I do need to call a php file from Unity3D game in order to convert a wav file into FLAC. I have solved to issue of calling a php file from a Unity3D game. The only issue I have is - to make a php WWW call to do the audio format converting. This is why your lib is crucial to me.

I sincerely appreciate your kind help!

**Comment by jens1o** [comment]
I don't mean php-ffmpeg, but ffmpeg itself. You can download the binary files at https://ffmpeg.org/ This libary is a wrapper for it.

**Comment by tammyruihuang** [comment]
I just run `brew install ffmpeg` in Terminal, and I received the following message: 

> converterFLAC > brew install ffmpeg
Error: ffmpeg 3.2.3 is already installed
To upgrade to 3.3.4, run `brew upgrade ffmpeg`
converterFLAC >
> 

I then upgraded my ffmpeg to the newest version. After successfully upgraded ffmpeg, I run my index.php in browser again. The following error message showed (seems like the same as before):

> Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:160 Stack trace: #0 /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration)) #1 /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(207): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), NULL) #2 /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(117): FFMpeg\FFProbe::create(Array, NULL, Object(Doctrine\Common\Cache\ArrayCache)) #3 /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/index.php(4): FFMpeg\FFMpeg in /Users/TammyHuang/Documents/CodingStudy/php/htdocs/converterFLAC/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php on line 50

>

**Comment by jens1o** [comment]
Okay, s seems to be another duplicate of #172

**Comment by schmanat** [comment]
If you don't know where the binaries are located type the following in your terminal:

    which ffmpeg
    which ffprobe

this should show your the full path of your binaries.

**Comment by tammyruihuang** [comment]
Thank you both @schmanat and @jens1o, my problem is solved. I have posted my solution based on minor modifications to one of the suggestions others posted. It'll be a reference for later users.
