### ISSUE TITLE
Can PHP-FFMPEG encode with Rate Control Modes other than Constant bitrate?

### ISSUE THREAD

**Issue by dancor89** [PHP-FFMpeg/PHP-FFMpeg#418]
#### Actual Behavior

I've recently started using PHP-FFMpeg for a project. I didn't know much about video encoding but I found this online resource which walks you through the most common "Rate Control Modes": http://slhck.info/video/2017/03/01/rate-control.html. This resource states that Variable Bitrate Encodings are the most useful and used modes, but, as far as I could tell, PHP-FFMpeg seems to create a command that only does Constant Bitrate Encoding by default, by adding the parameter -b:v $bitrate.

#### Expected Behavior

Can PHP-FFMpeg perform variable bitrate encodings, such as by using the -crf (Constant Rate Factor) parameter and the vbv-maxrate and vbv-bufsize?

**Comment by jens1o** [comment]
Unfortunately no, it cannot at the moment. It looks like it would introduce major breaking changes. But yeah, it's interesting.
