### ISSUE TITLE
Run script by PHP-ffmpeg

### ISSUE THREAD

**Issue by zongdesign** [PHP-FFMpeg/PHP-FFMpeg#424]
Hello
I have some script, which create video.
exec('
ffmpeg -y -i white.mp4 -i love.png -i facebook.jpg -filter_complex "
[1:v]format=rgba, scale=380:-1[v1]; 
[2:v]format=rgba, scale=50:-1[v2]; 
[0][v1]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2:shortest=1[ov1]; 
[ov1][v2]overlay=(main_w-overlay_w)/2-40:(main_h-overlay_h)/2+15:shortest=1" -c:v libx264 love.mp4
');
How I can run this script by your bundle. Thanks for your help

**Comment by jens1o** [comment]
I'm sorry, but we won't write code for you. If you have a *specific* question, do not hesitate to ask, but we won't write code for you. (SimpleFilter is the key)
