### ISSUE TITLE
如何将'3gp','avi','wmv','rm','rmvb','flv','mkv'格式文件都转换为MP4格式，谢谢

### ISSUE THREAD

**Issue by muyunchun120** [PHP-FFMpeg/PHP-FFMpeg#429]
exec可以，用对象不可以
                
                $cmd = 'ffmpeg  -i  '.$info->getPathname().' -c:v libx264 -strict -2 test.mp4';
                exec($cmd, $status);
                /*$format = new FFMpeg\Format\Video\X264();
                $video->save($format, 'video.mp4');*/

**Comment by jens1o** [comment]
Please look into the readme file or write your injury in English.
