### ISSUE TITLE
Cannot Clip Video File on Ubuntu 16.04 (ratecontrol_init: can't open stats file)

### ISSUE THREAD

**Issue by HeroSony** [PHP-FFMpeg/PHP-FFMpeg#447]
Hello, I got a error output.
I've tried to run this command manually: 

**(First attempt) : Fail(ratecontrol_init: can't open stats file)**
`'/usr/bin/ffmpeg' '-y' '-i' 'path/to/video/test.mp4' '-ss' '00:00:01.00' '-t' '00:00:06.00' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'aac' '-b:v' '500k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' 'path/to/tmp/test/ffmpeg-passes5a0431f672e669m1pu/pass-5a0431f673076' 'path/to/clips/clip0.mp4'`

After googling found a solution. I tried to removed :
from `path/to/tmp/test/ffmpeg-passes5a0431f672e669m1pu/pass-5a0431f673076`
to `path/to/tmp/test/`

**(Second attempt) : Fail(The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.)**
`'/usr/bin/ffmpeg' '-y' '-i' 'path/to/video/test.mp4' '-ss' '00:00:01.00' '-t' '00:00:06.00' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'aac' '-b:v' '500k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' 'path/to/tmp/test/' 'path/to/clips/clip0.mp4'`

Finnaly, if I tried to add this options( -strict -2 ):

**(Third attempt) : Success**
`'/usr/bin/ffmpeg' '-y' '-i' 'path/to/video/test.mp4' '-ss' '00:00:01.00' '-t' '00:00:06.00' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'aac' '-b:v' '500k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-strict' '-2' '-passlogfile' 'path/to/tmp/test/' 'path/to/clips/clip0.mp4'`

I am working on:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
FFMPEG:
```
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

The problem as shown above:
1. temp folder
2. required (-strict -2)

So can you help me how to solved it?

**Comment by HeroSony** [comment]
Hello, again.
Now it's working after I have modified FFMpeg/Media/Video.php

Adding two options( '-strict' and '-2' )
```
if ($format instanceof VideoInterface) {
            $commands[] = '-b:v';
            $commands[] = $format->getKiloBitrate() . 'k';
            $commands[] = '-refs';
            $commands[] = '6';
            $commands[] = '-coder';
            $commands[] = '1';
            $commands[] = '-sc_threshold';
            $commands[] = '40';
            $commands[] = '-flags';
            $commands[] = '+loop';
            $commands[] = '-me_range';
            $commands[] = '16';
            $commands[] = '-subq';
            $commands[] = '7';
            $commands[] = '-i_qfactor';
            $commands[] = '0.71';
            $commands[] = '-qcomp';
            $commands[] = '0.6';
            $commands[] = '-qdiff';
            $commands[] = '4';
            $commands[] = '-trellis';
            $commands[] = '1';
            $commands[] = '-strict';
            $commands[] = '-2';
        }
```
I still do not know it will be affected to the others part or not, but this changed made this problem passed.

**Comment by jens1o** [comment]
You should use extra parameters instead to do this :)

**Comment by jaccborn** [comment]
> Hello, again.
> Now it's working after I have modified FFMpeg/Media/Video.php
> 
> Adding two options( '-strict' and '-2' )
> 
> ```
> if ($format instanceof VideoInterface) {
>             $commands[] = '-b:v';
>             $commands[] = $format->getKiloBitrate() . 'k';
>             $commands[] = '-refs';
>             $commands[] = '6';
>             $commands[] = '-coder';
>             $commands[] = '1';
>             $commands[] = '-sc_threshold';
>             $commands[] = '40';
>             $commands[] = '-flags';
>             $commands[] = '+loop';
>             $commands[] = '-me_range';
>             $commands[] = '16';
>             $commands[] = '-subq';
>             $commands[] = '7';
>             $commands[] = '-i_qfactor';
>             $commands[] = '0.71';
>             $commands[] = '-qcomp';
>             $commands[] = '0.6';
>             $commands[] = '-qdiff';
>             $commands[] = '4';
>             $commands[] = '-trellis';
>             $commands[] = '1';
>             $commands[] = '-strict';
>             $commands[] = '-2';
>         }
> ```
> 
> I still do not know it will be affected to the others part or not, but this changed made this problem passed.

thank u  guys,  i find the problem two days without a clue.
