### ISSUE TITLE
Unable to load FFProbe

### ISSUE THREAD

**Issue by ghost** [PHP-FFMpeg/PHP-FFMpeg#45]
I know this isn't exactly an issue with this package, but I have this error: "Unable to load FFProbe", and there does not seem to be any FFProbe binaries in the entire internet for PHP (5.4). FFMpeg is installed and working, but can't find anything on Probe. Running windows WAMP server for development and Linux server for production, if anyone has any ideas where to get these.

**Comment by tchalvak** [comment]
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#ffmpeg appears to be the linux/ubuntu guide, for anyone searching for that.

**Comment by 0x1ad2** [comment]
# How I did it
I'm using the following directory for the FFMpeg binaries: **C:\FFmpeg\bin**

* Download the binaries and place them into a **C:\** directory in my case.

* Set your [Windows PATH variable](http://superuser.com/a/284351) **be sure to set both the user and system variable**.

* Open up your CLI (command line interface) by running **cmd.exe** and check if **FFMpeg** could be executed.

* If the command could be executed run the following lines of PHP code to configure the FFMpeg wrapper and use it to create awesome video features for you application.

```php
        $FFMpeg = FFMpeg\FFMpeg::create([
            'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe', // the path to the FFMpeg binary
            'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprobe.exe', // the path to the FFProbe binary
            'timeout'          => 3600, // the timeout for the underlying process
            'ffmpeg.threads'   => 12,   // the number of threads that FFMpeg should use
        ]);
```
*I'm using the PHP 5.4 short array syntax*

**Comment by bentinata** [comment]
I also thought just put `ffmpeg` and `ffprobe` at `PATH` would solve this problem. Maybe, I do wrong somewhere?

**Comment by 0x1ad2** [comment]
@bentinata just use the path's to the binaries in you unix machine mostly something like /usr/binaries/mmpeg or something.

**Comment by wonderco** [comment]
Hello
my code is : 
`$ffmpeg = FFMpeg::create(array(
            'ffmpeg.binaries'  => '/root/bin/ffmpeg',
            'ffprobe.binaries' => '/root/bin/ffprobe',
            'timeout'          => 3600,
            'ffmpeg.threads'   => 12,
        ));`

but not work ! :(
please help me
![untitled-4](https://cloud.githubusercontent.com/assets/8298810/16715558/b3e58528-46f8-11e6-9ed1-447a2e06f136.jpg)

**Comment by feefk** [comment]
@wonderco you should install ffmpeg first.

**Comment by bapijun** [comment]
> Hello
> my code is :
> `$ffmpeg = FFMpeg::create(array( 'ffmpeg.binaries' => '/root/bin/ffmpeg', 'ffprobe.binaries' => '/root/bin/ffprobe', 'timeout' => 3600, 'ffmpeg.threads' => 12, ));`
> 
> but not work ! :(
> please help me
> ![untitled-4](https://cloud.githubusercontent.com/assets/8298810/16715558/b3e58528-46f8-11e6-9ed1-447a2e06f136.jpg)

try to move the ffmpeg to the /usr/local/ffmpeg,a binary in the root folder will not allow a non-root user to execute that command. so use this command "sudo mv /root/bin/ffmpeg /usr/local/ffmpeg"  "sudo nv /root/bin/ffprobe /usr/local/ffmpeg"

**Comment by oroalej** [comment]
How to fix this in Ubuntu?
I already run `sudo apt install ffmpeg` and confirmed that the `ffmpeg` and `ffprobe` existed in path `usr\bin\`;

```
FFMpeg::create([
      'ffmpeg.binaries'  =>'\usr\bin\ffmpeg',
      'ffprobe.binaries' => '\usr\bin\ffprobe',
      'timeout'          => 3600,
      'ffmpeg.threads'   => 12,
    ])->open($file)
      ->getStreams()
      ->videos()
      ->first();
```

**Comment by mohammad6006** [comment]
.env:
```
FFMPEG_BINARIES=/usr/bin/ffmpeg
FFPROBE_BINARIES=/usr/bin/ffprobe
```

**Comment by nikhilbhatia22** [comment]
For **Windows users**,

Do not forget the extension in the path, It was **_.exe_**, that I was missing in the path and thus leading to NotFoundException.

`FFMPEG_PATH=C:\ffmpeg\bin\ffmpeg.exe`
`FFPROBE_PATH=C:\ffmpeg\bin\ffprobe.exe`

**Comment by abelardolg** [comment]
Hi there,

I installed ffmpeg and ffprobe:
![image](https://user-images.githubusercontent.com/22522883/161602108-ec70223f-0e5c-4e20-aec6-acd6c2129752.png)
![image](https://user-images.githubusercontent.com/22522883/161602143-422c6473-dd94-4afd-abac-96f47f714e93.png)

My error:
![image](https://user-images.githubusercontent.com/22522883/161602347-f6d922e3-6849-4f8f-8810-b948edd8c22f.png)

The location of ffprobe:
![image](https://user-images.githubusercontent.com/22522883/161602420-f4f3ab9c-2f3c-41a6-a7ef-0948dd0e1d60.png)

My composer.json:
![image](https://user-images.githubusercontent.com/22522883/161602755-c5d88069-fefa-42ef-946b-c6a5552f5eb2.png)

PHP 7.4
My Ubuntu:
![image](https://user-images.githubusercontent.com/22522883/161602867-0d7aedd4-f50c-4db4-8e5b-447b8422bdd2.png)

What's wrong?

Just installed today.

**Comment by legionlad** [comment]
Here, how i solved it.

For me it was rather un-related. 

I was using SpatieMedia with ffmpeg to clip a video, store it in a temp folder then save .webm in the same directory created by spatiemedia.

The Ffprobe was loading right, it was the hard-coded paths in spatie-media which were wrong.

Fix
vendor\spatie\laravel-medialibrary\config\media-library.php 
 Changed those line to this, on my server Ubuntu 20
   
---------- 

    'ffmpeg_path' => '/usr/bin/ffmpeg',
        'ffprobe_path' =>  '/usr/bin/ffprobe',

----------


vendor\spatie\laravel-medialibrary\src\Conversions\ImageGenerators\Video.php
 Same change in convert() function

----------
 

      $ffmpeg = FFMpeg::create([
                'ffmpeg.binaries' => '/usr/bin/ffmpeg',
                'ffprobe.binaries' => '/usr/bin/ffprobe',
        ]);
----------
