### ISSUE TITLE
Video not clips

### ISSUE THREAD

**Issue by rvsky** [PHP-FFMpeg/PHP-FFMpeg#451]
Hi! I am using laravel and I want to cut video. Logs says that everything is okay, on page nothing happens but video is the same lenght. Here's my code: 

```
FFMpeg::fromDisk('public')
    ->open('/uploads/videos/' .$video->file_name)
    ->filters()
    ->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(2), FFMpeg\Coordinate\TimeCode::fromSeconds(2))
    ->synchronize();
```

What should I do?

**Comment by jens1o** [comment]
Could you send me the file you're trying it with?

**Comment by rvsky** [comment]
Here's the video:
[Link](http://www108.zippyshare.com/v/WFyAxLhz/file.html)

Why you need this?

**Comment by jens1o** [comment]
@rvsky To be able to reproduce it.

**Comment by rvsky** [comment]
@jens1o okay, and how? It is working?

**Comment by jens1o** [comment]
Let me set up my environment ;) I'll message you in a few moments.

**Comment by rvsky** [comment]
Okay, so I am waiting.

**Comment by rvsky** [comment]
Take a look here please
https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/48
maybe i am doing something wrong?

**Comment by jens1o** [comment]
There are no more pieces of information there. What version of FFMpeg(the software itself) and the wrapper(this) do you use?

**Comment by rvsky** [comment]
"version": "1.3.0",

Maybe there is sth wrong with chmods? But I think not, i gave even 777

**Comment by jens1o** [comment]
You're code is incomplete. You need to save the actual file, that's why your error logs are blank. Please refer to the readme of `laravel-ffmpeg` on how you save it.
