### ISSUE TITLE
Documentation for basic usage needed

### ISSUE THREAD

**Issue by nise** [PHP-FFMpeg/PHP-FFMpeg#452]
If I install PHP-FFMpeg by using composer I get a new folder called 'vendor' inside my project. 
When following the documentation in the readme.md the following call should load the PHP-FFMpeg
'$ffmpeg = FFMpeg\FFMpeg::create();', but it doesn't.

How do I need to deal with the paths here?

**Comment by nise** [comment]
Could you please add the line 'require_once 'vendor/autoload.php';' before the '$ffmpeg = FFMpeg\FFMpeg::create();' in order to make it clear that composer needs to loaded.
Thanx

**Comment by jens1o** [comment]
@nise Do you want to do that :)
