### ISSUE TITLE
Encoding failed : Can't save

### ISSUE THREAD

**Issue by beckharuo** [PHP-FFMpeg/PHP-FFMpeg#460]
| Q              | A
| -------------- | ---
| Bug?           | maybe
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | CentOS

ffmpeg version 2.8.1 Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-18)
configuration: --prefix=/usr/local/ffmpeg --enable-shared
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101

code:
```php
$con = array('ffmpeg.binaries' => 'path_to_ffmpeg',
            'ffprobe.binaries' => 'path_to_ffprobe',
            'timeout' => 3600,
            'ffmpeg.threads' => 12
            );
            $logger = 'path_to_/ffmpeg.log';
            $watermarkPath = 'path_to_logo.PNG';
            $ffmpeg = FFMpeg::create($con);
            $video = $ffmpeg->open('path_to_test.mp4');
            $frame = $video->frame(TimeCode::fromSeconds(2));
            $frame->save('path_to_image.jpg');
            $video->filters()
                ->watermark($watermarkPath, array(
                    'position' => 'relative',
                    'bottom' => 50,
                    'right' => 50,
                ));
            $format = new X264();
            $format->on('progress', function ($video, $format, $percentage) {
                echo "$percentage % transcoded";
            });
            $video->save($format,'path_to_video.mp4');
so i try 
$video->save(new X264('libmp3lame'),'path_to_video.mp4');
$video->save(new X264('acc'),'path_to_video.mp4');
                $format = new X264();
                $format->on('progress', function ($video, $format, $percentage) {
                    echo "$percentage % transcoded";
                });

                $format
                    ->setKiloBitrate(1000)
                    ->setAudioChannels(2)
                    ->setAudioKiloBitrate(256);

                $video->save($format, 'video.avi');
```
but they did't work ,plz help me,thx

**Comment by jens1o** [comment]
what's the exact error? Do you perhaps save to the same file you were reading out?

**Comment by beckharuo** [comment]
error Message：
ffmpeg failed to execute command '/usr/local/ffmpeg/bin/ffmpeg' '-y' '-i' '/upload/video/test.mp4' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' 'movie=/upload/logo.PNG [watermark];[in][watermark] overlay=main_w - 50 - overlay_w:main_h - 50 - overlay_h [out]' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes5a48d22a137b6n4ej1/pass-5a48d22a13860' '/upload/video.mp4'

The filename are different,And i saw save first param is an interface,but all document use instantiation class X264,Is this right?

**Comment by jens1o** [comment]
Does ffmpeg have the right to create, read and modify files in those directories?

**Comment by beckharuo** [comment]
the may right to create and read,beacuse $frame->save is working

**Comment by beckharuo** [comment]
and this folder permission 777

**Comment by beckharuo** [comment]
'/root/bin/ffmpeg' '-y' '-i' '/media/test.mp4' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libfdk_aac' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' 'movie=/media/1.png [watermark];[in][watermark] overlay=main_w - 50 - overlay_w:main_h - 50 - overlay_h [out]' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes5a4cf25757f5evaddr/pass-5a4cf25758016' '/media/video.mp4'
ffmpeg version N-89672-g41e51fb Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-16)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/root/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56.  7.100 / 56.  7.100
  libavcodec     58.  9.100 / 58.  9.100
  libavformat    58.  3.100 / 58.  3.100
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  8.100 /  7.  8.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/media/test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.41.100
  Duration: 00:00:09.67, start: 0.000000, bitrate: 744 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 480x480, 691 kb/s, 15 fps, 15 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[libx264 @ 0x44cc200] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x44cc200] ratecontrol_init: can't open stats file
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by jens1o** [comment]
does the user have permission to write and read from the `tmp` directory?

**Comment by beckharuo** [comment]
ffmpeg -i /media/test.mp4 -i /media/1.png -filter_complex "overlay=5:5" /media/out.mp4
