### ISSUE TITLE
Palettegen?

### ISSUE THREAD

**Issue by cclloyd** [PHP-FFMpeg/PHP-FFMpeg#461]
How would I do palettegen with this?  

The 2 commands I use are..

Generating the palette: 
`ffmpeg -y -ss 7 -i clip.mp4 -vf fps=30,scale=480:-1:flags=lanczos,palettegen palette.png`

Generating the gif from palette
`ffmpeg -ss 7 -i clip.mp4 -i palette.png -filter_complex "fps=30,scale=480:-1:flags=lanczos[x];[x][1:v]paletteuse" clip.gif`

**Comment by jens1o** [comment]
You can use `SimpleFilter`s to achieve that functionality.

Adding this as a feature request for 1.x.

**Comment by johanneshro** [comment]
/**
     * Saves the high quality gif in the given filename.
     *
     * @param string  $pathfile
     *
     * @return Gif
     *
     * @throws RuntimeException
     */
    public function save_with_high_quality($pathfile)
    {
        /**
         * @see http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
         */

		$filters = "fps=30,scale=".$this->dimension->getWidth().":-1:flags=lanczos";
		$palette = "/tmp/palette.png";

        $commands = array(
            '-ss', (string)$this->timecode
        );

        if(null !== $this->duration) {
            $commands[] = '-t';
            $commands[] = (string)$this->duration;
        }
        $commands[] = '-i';
        $commands[] = $this->pathfile;
        $commands[] = '-vf';
        $commands[] = $filters.",palettegen";
        $commands[] = '-y';
        $commands[] = $palette;

        $commands_2 = array(
            '-ss', (string)$this->timecode
        );

        if(null !== $this->duration) {
            $commands_2[] = '-t';
            $commands_2[] = (string)$this->duration;
        }
        $commands_2[] = '-i';
        $commands_2[] = $this->pathfile;
        $commands_2[] = '-i';
        $commands_2[] = $palette;
        $commands_2[] = '-lavfi';
        $commands_2[] = $filters." [x]; [x][1:v] paletteuse";
        $commands_2[] = '-y';

        $commands_2 = array_merge($commands_2, array($pathfile));

        try {
            $this->driver->command($commands);
        } catch (ExecutionFailureException $e) {
            $this->cleanupTemporaryFile($pathfile);
            throw new RuntimeException('Unable to generate palette', $e->getCode(), $e);
        }

        try {
            $this->driver->command($commands_2);
        } catch (ExecutionFailureException $e) {
            $this->cleanupTemporaryFile($pathfile);
            throw new RuntimeException('Unable to save gif', $e->getCode(), $e);
        }

        return $this;
    }

**Comment by jens1o** [comment]
@johanneshro Would you mind creating a pr?
