### ISSUE TITLE
Find replacement for composer dependency `alchemy/binary-driver`

### ISSUE THREAD

**Issue by jens1o** [PHP-FFMpeg/PHP-FFMpeg#463]
The driver is no longer maintained in a regular period of time, so in case somebody knows a good driver that meet our needs, there will be a new use here. :)

Otherwise, we could maintain it ourselves. :)

**Comment by romainneutron** [comment]
I'd recommend to fork alchemy/binary driver in the FFMPeg org. would you like that I do it ?

**Comment by jens1o** [comment]
@romainneutron Sure, but I do not have permission to fork any repositories. :)

**Comment by romainneutron** [comment]
It's been forked here https://github.com/PHP-FFMpeg/BinaryDriver/
You should be able to push in this repo

**Comment by jens1o** [comment]
Yeah, it works. Thank you!

**Comment by jens1o** [comment]
@romainneutron Perhaps you can link the old repo to the new one and perhaps abandon your package on packagist, so the users can use the maintained version?
