### ISSUE TITLE
Reason for Probe Failure?

### ISSUE THREAD

**Issue by cclloyd** [PHP-FFMpeg/PHP-FFMpeg#465]
| Q              | A
| -------------- | ---
| Bug?           | possibly
| New Feature?   | no
| FFmpeg Version | 
`ffprobe version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] [INPUT_FILE]`
| OS             | Your OS and version

Is there a way to get the actual error when using ffprobe with laravel/twig?  It shows the exception page when it gets thrown, but doesn't print out any information regarding WHY ffprobe failed, just that it did, and its stacktrace. 

How can I get the reason for ffprobe failing?  It's not failing when I probe using ssh.

**Comment by jens1o** [comment]
You could try debugging here: https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/2649d45b7b5b67e2699fff695a1ee7e800e4ff64/src/FFMpeg/FFProbe.php#L263

**Comment by jens1o** [comment]
Closed due to inactivity.
