### ISSUE TITLE
Unable to save frame as image

### ISSUE THREAD

**Issue by Nehadigi** [PHP-FFMpeg/PHP-FFMpeg#466]
| Q              | A
| -------------- | ---
| Bug?           | Yes

| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version
Symfony2.8
ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffprobe' '-y' '-ss' '00:00:05.00' '-i' '/home/dmlabs-5/iasp/IASP_platform/web/uploads/media/default/0001/01/529d9972c548e552271728e915cbbf98c9514f13.mp4' '-vframes' '1' '-f' 'image2' '/home/dmlabs-5/iasp/IASP_platform/web/uploads/media/default/0001/01/529d9972c548e552271728e915cbbf98c9514f13.jpg'

**Comment by jens1o** [comment]
Could you show your code?

Please notice that this is a wrapper and thus most "bugs" are created by users having wrong expectations. Take a deep look at permissions for your system.

**Comment by jens1o** [comment]
Closed due to inactivity.
