### ISSUE TITLE
FFmpeg race condition with PHP

### ISSUE THREAD

**Issue by sm2017** [PHP-FFMpeg/PHP-FFMpeg#469]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | May be
| Version Used   | 0.9.5
| FFmpeg Version | 2.6.5
| OS             | Centos 7

#### Actual Behavior

I have a problem with executing FFmpeg commands , I think PHP execute the `->save('frame.jpg');` line before ffmpeg complete the process , may be ffmpeg return success to process , I don't know exactly , But I'm sure something is wrong here 

#### Expected Behavior

In the following code `filesize` must be correct as I use `clearstatcache` to clear cache

#### Steps to Reproduce
```php
<?php
require 'vendor/autoload.php';

$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('video.mpg');
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
    ->save('frame.jpg');

clearstatcache();

echo filesize('frame.jpg')
?>
```
In the above mentioned script , it is hard to reproduce issue , I have a long running script that process million files , just 100-200 file has incorrect file size

#### Possible Solutions

I think , when php run `filesize` , ffmpeg still working on background and saving frame to `frame.jpg` and we need to force executing ` ->save('frame.jpg');` **synchronously** , and when ffmpeg completely process file , execute next line of PHP , I don't know how we can force FFmpeg?!

**Comment by jens1o** [comment]
Hi,

thanks for the issue. This sounds quite interesting to me, because actually everything is done synchronously(which is why the performance isn't that good at all). You can test this by outputting `"my random value"` and you see that it is done after(!) the frame has been extracted. You may want to add a sleep call to it.

**Comment by sm2017** [comment]
@jens1o I really don't known how it happens . I just know the output of `filesize` is incorrect . What you think? Why the output is incorrect? `clearstatcache` is called exactly before `filesize`
If ffpmpeg command executed synchronously . I think just maybe it is a PHP 7.1 core bug, may be!!

**Comment by jens1o** [comment]
What happens if you check the `filesize` when restarting the script(and removing the FFMpeg-part)?

**Comment by sm2017** [comment]
@jens1o The `filesize` is correct , Even if I don't remove FFMpeg-part
As I told before when I process million files just hundred(s) files have incorrect filesize , But If I run the script for those files again , The result is correct

**Comment by jens1o** [comment]
I don't know. perhaps this is a cache by the operating systems?

**Comment by jens1o** [comment]
@sm2017 Did you found out something new?

**Comment by sm2017** [comment]
@jens1o I found that is it not `PHP-FFMpeg` issue , the issue come from a dependency
