### ISSUE TITLE
is there a function to check if ffmpeg is installed on the system.

### ISSUE THREAD

**Issue by Abu3safeer** [PHP-FFMpeg/PHP-FFMpeg#479]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | yes
| Version Used   | 2649d45
| FFmpeg Version | FFmpeg 3.4.1
| OS             | ubuntu 16.04

Hello everyone, 
I like how this project help people who does not involve into video-encoding world to get what they need, so Thank you.

I was checking into documentation + browsing the code, but could not find any built-it function to check if ffmpeg is installed or not.

I did created my own function, but just want to make sure if this library has a function to use it instead or 'reinventing the wheel'.

Here is what I created (very simple):
```
$var = shell_exec('which ffmpeg');
if($var === null)
    return 'FFMPEG is not installed, please install it before you can use this app.';
else
    dd(shell_exec(trim($var) . ' -version'));
```

**Comment by jens1o** [comment]
You can initialize it and catch all `FFMpeg\Exception\ExecutableNotFoundException` exceptions that are being thrown when the executables couldn't be foud.
