### ISSUE TITLE
unable to convert video

### ISSUE THREAD

**Issue by thrijith** [PHP-FFMpeg/PHP-FFMpeg#480]
Hi 

i have using this to convert other video format to `.mp4` it is working in some cases but giving trouble in some other.

this is the code i have been currently using

         $format = new FFMpeg\Format\Video\X264( 'libmp3lame', 'libx264' );

         $format->setAudioCodec("libfdk_aac");

         $format->setAdditionalParameters( array('-crf', '28') );

         $format->on('progress', function ($media, $format, $percentage) { 

         echo "$percentage % transcoded \n"; 

         $this->file_job->progress = $percentage + 1;

         if (($this->file_job->progress % 20) == 0) {

            $this->file_job->save();

         } }); `

before adding the `crf` param i tried it using command line and was able to get desired result
i am not sure if this is the correct way to do it please guide if this is wrong 

here is a link to the videos used in the process
[MOV](https://drive.google.com/open?id=1abXBzVBWxzAcnR1DlomnS3HBS_NhITdM)
[MKV](https://drive.google.com/open?id=1blVJfY94_g_uUMlT9fr2W16lLEBNr_eu)

Thanks

**Comment by jens1o** [comment]
Can you elaborate this?
` some cases but giving trouble in some other.`

Please check the syntax of the executed command. Using additional parameters is risky.

**Comment by thrijith** [comment]
the conversion from `mkv` to `mp4` is working without issue but not working in `mov`'s case

**Comment by jens1o** [comment]
> Please use the issue template, so I can give you an proper answer.

> Please check the syntax of the executed command. Using additional parameters is risky.

**Comment by sagarnasit** [comment]
the problem in converting .mov to .mp4. other formats work fine.

**Comment by jens1o** [comment]
Then that's not a problem of this lib, but a ffmpeg issue.

**Comment by sagarnasit** [comment]
I checked with ffmpeg, it works fine. But when i'm using this lib to convert then it gets fail every time with only .mov file.
