### ISSUE TITLE
Creating multiple clips from the same video

### ISSUE THREAD

**Issue by msl2000** [PHP-FFMpeg/PHP-FFMpeg#487]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Ubuntu 16.04.3 LTS

#### Expected Behavior

What is the behavior you expect? 

To cut multiple clips from a video and concatenate them into a single output video

Apologies but considering there were no documentation on this possibly advanced feature, had to come by and raise a ticket.

Was just wondering how would one go around creating multiple clips from a single video and concatenating them into a single video.

**Comment by jens1o** [comment]
I'm not sure what you mean?

https://github.com/PHP-FFMpeg/PHP-FFMpeg#concatenation

Is this what you want to do?

**Comment by msl2000** [comment]
I see, yes I have attempted to cut it and save them individually before concatenating them. However, felt it to be rather a long roundabout way and figured I could clip videos, concatenate and then save.

I will play around with the the package and hopefully streamline it and help with the docs :)

**Comment by jens1o** [comment]
Alright. Closing this. If you have any questions, feel free to write a comment.
