### ISSUE TITLE
Add a PNG Frame over Video using FFMPEG PHP

### ISSUE THREAD

**Issue by socialpixe** [PHP-FFMpeg/PHP-FFMpeg#488]
Hello,

I am able to record a video, but now i need to add a frame over that video using FFMPEG. I have source of Vendor FFMPEG. but unable to add frame, error showing unable to handle the request. 

```
`require_once('vendor/autoload.php'); 

 

$probe = FFMpeg\FFProbe::create();

$formatString = $probe
    ->streams('../uploads/ad7ec88da987307a9ea068f6d8d0d49b.mp4')
    ->videos()
    ->first()
    ->get('codec_name');

$className = null;
switch($formatString) {
    case 'h264':
        $className = FFmpeg\Format\Video\X264::class;
    break;
    // add your format codecs here
    default:
        throw new \LogicException("Unknown video format {$formatString}");
}
    
// open actual video
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('../uploads/ad7ec88da987307a9ea068f6d8d0d49b.mp4');

$format = new $className;

$video->save($format, 'myFancyVideo.mp4');
````

I just want to add a PNG frame over video. Please share update. 

NOTE: I am using Shared hosting.

**Comment by jens1o** [comment]
> I just want to add a PNG frame over video.

I'm not sure what you want to do. Do you want to [watermark your video](https://github.com/PHP-FFMpeg/PHP-FFMpeg#watermark) or are you trying [to make thumbnails out of it](https://github.com/PHP-FFMpeg/PHP-FFMpeg#extracting-image)?

**Comment by socialpixe** [comment]
Yeah, exactly. i want to add watermark to my video. using C# and the process should run in background. because application is public

I tried this

```
public void AddWaterMark(string orginalVideoPath, string waterMarkPath, string outPutVideoPath)
        {
            string ffmpeg = System.AppDomain.CurrentDomain.BaseDirectory + @"\Tools\\ffmpeg.exe";

            System.Diagnostics.Process ffmpegProcess = new System.Diagnostics.Process();

            System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo(ffmpeg);

            startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Normal;

            startInfo.Arguments = " -i " + orginalVideoPath + " -i " + waterMarkPath + " -filter_complex \"overlay=10:10\" " + outPutVideoPath;
            try
            {
                System.Diagnostics.Process.Start(startInfo).WaitForExit();
            }
            catch (Exception err)
            {
                MessageBox.Show(err.Message);
            }
        }

```

**Comment by jens1o** [comment]
Please understand that we do not give support on using FFMpeg Filters in general, but we focus on using this library(with using PHP).

> process should run in background. because application is public

There can be a video encoding worker executed in the background ;)
PHP is not limited for serving webpages.
