### ISSUE TITLE
 ffmpeg failed to execute command

### ISSUE THREAD

**Issue by gifary** [PHP-FFMpeg/PHP-FFMpeg#489]
I am getting this error on ubuntu, ffmpeg already installed. please can you help me?
Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' 'resources/Danni no Transfer 2.wav' '-acodec' 'flac' '-b:a' '256k' '-ac' '1' 'audiob6abdd0.flac' in /var/www/html/geolocation/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /var/www/html/geolocation/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/local/bin...') #1 /var/www/html/geolocation/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #2 /var/www/html/geolocation/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, Array) #3 /var/www/html/geolocation/vendor/php-ffmpeg/php-ffmpeg/src/ in /var/www/html/geolocation/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Audio.php on line 74

**Comment by Abu3safeer** [comment]
just copy this:
'/usr/local/bin/ffmpeg' '-y' '-i' 'resources/Danni no Transfer 2.wav' '-acodec' 'flac' '-b:a' '256k' '-ac' '1' 'audiob6abdd0.flac'

and paste it in ternmenal to see if that command works or not.

**Comment by gifary** [comment]
@Abu3safeer ffmpeg version N-90176-g27cbbbb Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.1 (Ubuntu 5.4.1-2ubuntu1~16.04) 20160904
  configuration: 
  libavutil      56.  7.101 / 56.  7.101
  libavcodec     58. 13.100 / 58. 13.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 12.100 /  7. 12.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
Input #0, wav, from 'resources/Danni no Transfer 2.wav':
  Duration: 00:01:05.79, bitrate: 13 kb/s
    Stream #0:0: Audio: gsm_ms (1[0][0][0] / 0x0031), 8000 Hz, mono, s16, 13 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (gsm_ms (native) -> flac (native))
Press [q] to stop, [?] for help
Output #0, flac, to 'audiob602df5.flac':
  Metadata:
    encoder         : Lavf58.10.100
    Stream #0:0: Audio: flac, 8000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc58.13.100 flac
[gsm_ms @ 0x2e3b800] Packet is too small
Error while decoding stream #0:0: Invalid data found when processing input

I can't find solution for this

**Comment by gifary** [comment]
But it created the file audiob6abdd0.flac

**Comment by Abu3safeer** [comment]
the output file, does it work?

**Comment by Abu3safeer** [comment]
beside what is the version of ffmpeg you are currently using?

**Comment by gifary** [comment]
Yeah it's work, ffmpeg version N-90176

**Comment by Abu3safeer** [comment]
the version number is not really a number, looks like this is a special build.
the latest official build is (FFmpeg 3.4.2 "Cantor")

**where did you get this ffmpeg from?**

**Comment by gifary** [comment]
oh sorry i am wrong @Abu3safeer  this is my ffmpeg version 3.4.2-1

**Comment by gifary** [comment]
i try on macbook is running well, but on server getting trouble like above

**Comment by Abu3safeer** [comment]
Is the version on the macbook same as the version on the server?

**Comment by gifary** [comment]
thanks you for your response @Abu3safeer . I fixed that to set permission folder for save file to 777.

**Comment by Abu3safeer** [comment]
777 is danger, especially if you website is live, try to use more secure permissions.

**Comment by gifary** [comment]
yup, i try to chante 755 or 765 still error

**Comment by hemantachhami19** [comment]
Any solution?
