### ISSUE TITLE
 Got error 'PHP message: Uncaught PHP Exception FFMpeg\\Exception\\RuntimeException: "Unable to save frame"

### ISSUE THREAD

**Issue by Srijeeta** [PHP-FFMpeg/PHP-FFMpeg#490]
| Q              | A
| -------------- | ---
| Bug?           | Yes
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | 2.8.11
| OS             | Ubuntu 16.04

I'm using Ubuntu 16.04 and I'm facing this error.
I'm using this code with Drupal 8

`        $ffmpeg = \FFMpeg\FFMpeg::create(array(
        'ffmpeg.binaries' => exec('which ffmpeg'),
        'ffprobe.binaries' => exec('which ffprobe'),
        ));
        $video = $ffmpeg->open($url);
        $video
            ->filters()
            ->resize(new \FFMpeg\Coordinate\Dimension(320, 240))
            ->synchronize();
        $video
            ->frame(\FFMpeg\Coordinate\TimeCode::fromSeconds(10))
            ->save('/compressed_video/thumbnail.jpg');
        $video
            ->save(new \FFMpeg\Format\Video\X264(), 'compressed_video/export-x264.mp4')
            ->save(new \FFMpeg\Format\Video\WMV(), 'export-wmv.wmv')
            ->save(new \FFMpeg\Format\Video\WebM(), 'export-webm.webm'); `
All the folder permissions are checked. Still getting the same error. For the video the encoding failed as well. 
Please Help!!

**Comment by jens1o** [comment]
Please tell us which ffmpeg version you're using.

**Comment by Srijeeta** [comment]
I'm using 11.1

**Comment by jens1o** [comment]
Can you make sure that the directories referenced in your code are existant?

**Comment by jens1o** [comment]
Can you make sure that the directories referenced in your code are existant?

**Comment by Srijeeta** [comment]
@jens1o Checked!! They are all existant.

**Comment by jens1o** [comment]
Alright. Can you only let it save one video(so only one export)?

Then, if this still doesn't works, I need you to modify the statement to something like this:
`echo $video->getFinalCommand($myFormat);`

Then, please execute the command you've been given with the user that hosts the php thing.

**Comment by jens1o** [comment]
I told you to use the command that we provide. You should not use your own command.

**Comment by Srijeeta** [comment]
Could you please tell me what is wrong with the one I'm using.

**Comment by jens1o** [comment]
You're not using the library?

**Comment by Srijeeta** [comment]
I was giving wrong path to save the thumbnail. So that worked. But the encoding still failed.

**Comment by Srijeeta** [comment]
@jens1o 
`$video
            ->save(new \FFMpeg\Format\Video\X264(), 'sites/default/files/video-thumbnails/2018-02/compressed-video.mp4');
            ->save(new \FFMpeg\Format\Video\WMV(), 'sites/default/files/video-thumbnails/2018-02/compressed-video2.wmv')
            ->save(new \FFMpeg\Format\Video\WebM(), 'sites/default/files/video-thumbnails/2018-02/compressed-video2.webm');
`
I just checked wmv and webm are working, but not the mp4.

**Comment by Srijeeta** [comment]
Solved it!!
https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/310
This was very useful. Thanks anyway!

**Comment by jens1o** [comment]
Alright, closing this. Thank you.
