### ISSUE TITLE
composer update --lock Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by informaticosgb** [PHP-FFMpeg/PHP-FFMpeg#497]
Hi there! I have this error running composer update --lock

![image](https://user-images.githubusercontent.com/4468829/37168643-4a2fc926-22e4-11e8-8f3a-882b802df809.png)

Any help ? Thanks !

**Comment by DutchChannels** [comment]
I've the same issue, any solution yet?

**Comment by jens1o** [comment]
duplicate of #470
