### ISSUE TITLE
How merger Audio and  Video ? 

### ISSUE THREAD

**Issue by web256** [PHP-FFMpeg/PHP-FFMpeg#499]
code 

        $ffmpeg = FFMpeg\FFMpeg::create(array(
            'ffmpeg.binaries'  => '/usr/local/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/local/bin/ffprobe',
            'timeout'          => 3600, // The timeout for the underlying process
            'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
        ), $log);

                $video = $ffmpeg->open('/data/svn_data/weixin/web/mamamiya/web/static/upload/test003.mp4');
        $video->addFilter(new \FFMpeg\Filters\Audio\SimpleFilter(
            array('-i /data/svn_data/weixin/web/mamamiya/web/static/upload/test002.mp3')));
        
        
        $result = $video->save(new FFMpeg\Format\Video\X264('libmp3lame'), '/data/svn_data/weixin/web/mamamiya/web/static/upload/test1.mp4');

error:

Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/data/svn_data/weixin/web/mamamiya/web/static/upload/test003.mp4' '-i /data/svn_data/weixin/web/mamamiya/web/static/upload/test002.mp3' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes5aaa102c6b622a7f3d/pass-5aaa102c6b6f0' '/data/svn_data/weixin/web/mamamiya/web/static/upload/test1.mp4' in /data/svn_data/weixin/web/mamamiya/web/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php on line 111

shell exec command  success  ( /tmp/ffmpeg-passes5aa9fcebba6f4/pass-5aa9fcebba73atu0uu  dir exists)

/usr/local/bin/ffmpeg -y -i /data/svn_data/weixin/web/mamamiya/web/static/upload/test003.mp4 -i /data/svn_data/weixin/web/mamamiya/web/static/upload/test002.mp3 -threads 12 -vcodec libx264 -acodec libmp3lame -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k -pass 1 -passlogfile /tmp/ffmpeg-passes5aa9fcebba6f4/pass-5aa9fcebba73atu0uu /data/svn_data/weixin/web/mamamiya/web/static/upload/test.mp4

**Comment by jens1o** [comment]
This is not supported, because SimpleFilter are appended(at the very end).
