### ISSUE TITLE
Failed to avformat_open_input|watermark

### ISSUE THREAD

**Issue by Youngkingoo6** [PHP-FFMpeg/PHP-FFMpeg#500]
| Q              | A
| -------------- | ---
| Bug?           | maybe
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | win10

#### Actual Behavior
I just run below commond 
`"E:/ffmpeg/bin/ffmpeg.exe" -y -i E:\work\online\football\storage\app\aetherupload\video\201803\32836a8dfa09a6b4193daab449370bec.mp4 -async 1 -metadata:s:v:0 start_time=0 -threads 12 -vcodec libx264 -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k -vf "movie=E:/work/online/football/storage/watermark.png [watermark];[in]scale=320:240 [p0];[p0][watermark] overlay=main_w - 50 - overlay_w:50 [out]" -pass 1 -passlogfile "C:\Users\ADMINI~1\AppData\Local\Temp\ffmpeg-passes5aab98235d6b8boa2j/pass-5aab98235dbdf" "E:/myFancyVideo2.avi"`

And get the error 
ffmpeg version N-90315-gf706cdda56 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56.  9.100 / 56.  9.100
  libavcodec     58. 14.100 / 58. 14.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 13.100 /  7. 13.100
  libswscale      5.  0.102 /  5.  0.102
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\work\online\football\storage\app\aetherupload\video\201803\32836a8dfa09a6b4193daab449370bec.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2017-01-24T17:20:16.000000Z
  Duration: 00:04:57.88, start: 0.000000, bitrate: 539 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 299 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2017-01-24T17:20:16.000000Z
      handler_name    : L-SMASH Video Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 235 kb/s (default)
    Metadata:
      creation_time   : 2017-01-24T17:20:16.000000Z
      handler_name    : L-SMASH Audio Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[Parsed_movie_0 @ 0000015fec527d00] Failed to avformat_open_input 'E'
[AVFilterGraph @ 0000015fec4dfb00] Error initializing filter 'movie' with args 'E:/work/online/football/storage/watermark.png'
Error reinitializing filters!
Failed to inject frame into filter network: No such file or directory
Error while processing the decoded data for stream #0:0
Conversion failed!

I just do not know how to fix it

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by jens1o** [comment]
> Failed to inject frame into filter network: No such file or directory

Are you sure the given file exists? If so, could you append those?

**Comment by Youngkingoo6** [comment]
I am sure the file exist. If not,it will throw file not exist exception.what should i post
to you?

**Comment by Youngkingoo6** [comment]
if not add waterark,it could success.

**Comment by jens1o** [comment]
Okay, I then would like to try it out myself. Could you post your watermark(or send it privately) and an example video?

**Comment by Youngkingoo6** [comment]
i will post you later.

**Comment by jens1o** [comment]
Thanks for the files, but this is a ffmpeg issue itself.

**Comment by Youngkingoo6** [comment]
follow the https://trac.ffmpeg.org/wiki/CompilationGuide/Centos officail documents.
And use this 
$format = new X264('libfdk_aac', 'libx264');
It's fine.

**Comment by jens1o** [comment]
Glad you've got it! :)
