### ISSUE TITLE
mposer update

### ISSUE THREAD

**Issue by watnuweer** [PHP-FFMpeg/PHP-FFMpeg#506]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by jens1o** [comment]
Could you please elaborate?

**Comment by watnuweer** [comment]
Sorry but I don't know what I did to open this ticket. I don't have any issues and love the product.
Keep up the good work!

**Comment by jens1o** [comment]
Alright, thank you! :)
