### ISSUE TITLE
can we extract frames constantly instead of received a full video file from user?

### ISSUE THREAD

**Issue by videni** [PHP-FFMpeg/PHP-FFMpeg#510]
Let's assume a user is uploading a 5 seconds long video as this flow

User   -> Server  A ->  Server B

# the wish

At the first second my php server A receives that video, I need to get  10 pictures  from that 1 second , then deliver these pictures to another server B,  the Server B then reply the process result through  the Server A  to user.   the  so does the rest seconds. 

# the reality
currently , we  extract 10*5=50 pictures after we received the full video. the user can feel considerable delay. is impossible to do this job as the first way?

**Comment by jens1o** [comment]
Piping is not supported by this library, and due to PHP lack of support(and usefulness) for that, I need to say that we can't do this.
