### ISSUE TITLE
Config and unable to location FFProbe

### ISSUE THREAD

**Issue by jerauf** [PHP-FFMpeg/PHP-FFMpeg#511]
I'm trying to retrieve a frame of a video. I'm using this code in my controller.

`use Pbmedia\LaravelFFMpeg\FFMpegFacade as FFMpeg;
`
And then to get the frame:

`
	    $media = FFMpeg::open('http://myvideo.com/video/100');
		$frame = $media->getFrameFromString('00:00:13.37');

`

And my error is:

`Unable to load FFProbe`

I looked through the issues here and the config was mentioned but I'm not sure what the paths mean. Shouldn't they be pointing to the vendor folder?

`    'ffmpeg.binaries' => '/usr/local/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/local/bin/ffprobe',
`

**Comment by jens1o** [comment]
@jerauf Why did you closed the issue?

**Comment by jerauf** [comment]
I posted it on in the wrong repo. Mean to post in the Laravel version of this.
