### ISSUE TITLE
How to set interval about progress function?

### ISSUE THREAD

**Issue by carrotis** [PHP-FFMpeg/PHP-FFMpeg#512]
Hello PHP FFMPEG users~

$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage % transcoded";
});

It's call every 1 sec, I'd like to set some values.
How can do that ?

**Comment by carrotis** [comment]
That code is called every second.
So every second print  "$percentage % transcoded";"
I'd like to set interval.

**Comment by jens1o** [comment]
That's not possible, because PHP is not event-driven.
