### ISSUE TITLE
SlideShow from images. 

### ISSUE THREAD

**Issue by ezequiel9** [PHP-FFMpeg/PHP-FFMpeg#513]
I found many examples by command console but nothing by this library. 

I need to create a slideshow from images. VERY SIMPLE slideshow.  Charge dynamically some pictures and add some audio. Anyone know how to do that?

Thanks!

**Comment by jens1o** [comment]
There is no built-in support for that. You'd need to use SimpleFilter's all over the place. I think it is not possible to use this lib, because basically everything bases on one input path, but you could look how far you can go with the concat feature.
