### ISSUE TITLE
Unable to load FFProbe

### ISSUE THREAD

**Issue by glkhg** [PHP-FFMpeg/PHP-FFMpeg#518]
| Q              | A
| -------------- | ---
| Bug?           | may be
| New Feature?   | no
| Version Used   | latest master
| FFmpeg Version | N-90704-g23e994ca49
| OS             | win7

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

{message: "Unable to load FFProbe", exception: "FFMpeg\Exception\ExecutableNotFoundException",…}
exception
:
"FFMpeg\Exception\ExecutableNotFoundException"
file
:
"D:\www\magic\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php"
line
:
50
message
:
"Unable to load FFProbe"

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by glkhg** [comment]
I installed ffmpeg on D:\software\ffmpeg folder
and my config is 
$config = [
                'ffmpeg.binaries'  => 'D:/software/ffmpeg/bin/ffmpeg',
                'ffprobe.binaries' => 'D:/software/ffmpeg/bin/ffprobe',
                'timeout'          => 3600, // The timeout for the underlying process
                'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
            ];

**Comment by glkhg** [comment]
i also add it to environment path which i can run ffmpeg and ffprobe  at any path

**Comment by jens1o** [comment]
> windows must specify exact path
fuck windows

😀
