### ISSUE TITLE
How to get an image in base64 format without save image file to disk?

### ISSUE THREAD

**Issue by qcjackman** [PHP-FFMpeg/PHP-FFMpeg#532]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Centos6

## When I set **$returnBase64** as **true** calling Frame::save()
```
$video = $ffmpeg->open($file);

$frame = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(1));

$cover = $frame->save($outfile, false, true);
```

## I got a fatal error:
```
Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-ss' '00:00:01.00' '-i' '/tmp/phpEOqJ5S' '-vframes' '1' '-f' 'image2pipe' '-' '/tmp/cover_zhiliao.png' in /usr/share/nginx/html/qcjackman@hotmail.com/anything/ffmpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Frame.php on line 130
```

**Comment by qcjackman** [comment]
I have found out the cause of the problem, The source code has a bug in

> Frame::save()

When set $returnBase64 true, the generated commands always contain the output file path, It`s unright, So I fixed it like this in line 119 of src\FFMpeg\Media\Frame.php:

> if(!$returnBase64) {
            $commands = array_merge($commands, array($pathfile));
        }

I`m from china, please forgive my English for not very good, So, Am I right?

**Comment by jens1o** [comment]
@qcjackman Could you create a pull request please?

**Comment by qcjackman** [comment]
@jens1o Yes, I've done that.
