### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by MahdiPishguy** [PHP-FFMpeg/PHP-FFMpeg#537]
#### Actual Behavior

How does PHP-FFMpeg work with lastest Laravel as 5.6?

#### Install fail

I get this error when i try to install this library on laravel 5.6

```
Problem 1
    - Conclusion: don't install php-ffmpeg/php-ffmpeg v0.11.1-pl-1
    - Conclusion: remove symfony/console v4.0.9
    - Installation request for php-ffmpeg/php-ffmpeg ^0.11.1 -> satisfiable by php-ffmpeg/php-ffmpeg[v0.11.1, v0.11.1-pl-1].
    - Conclusion: don't install symfony/console v4.0.9
    - Conclusion: don't install alchemy/binary-driver 1.6.0

...

```

**Comment by jens1o** [comment]
It doesn't work yet. A search on the existing issues would yield to an already existing issue: https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/470. Thank you.

**Comment by mpryvkin** [comment]
Possibly related to #525 where workaround is listed
