### ISSUE TITLE
Can't install with php 7.0

### ISSUE THREAD

**Issue by Sofianio** [PHP-FFMpeg/PHP-FFMpeg#538]
| Q              | A
| -------------- | ---
| Bug?           | i don't know
| New Feature?   | no
| Version Used   | 0.11.1
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | OSX 10.12

Ican't install on my machine, I run  `$ composer require php-ffmpeg/php-ffmpeg`
I get
```
Using version ^0.11.1 for php-ffmpeg/php-ffmpeg
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/event-dispatcher v4.0.7 requires php ^7.1.3 -> your PHP version (7.1.10) overridden by "config.platform.php" version (7.0.10) does not satisfy that requirement.
    - symfony/event-dispatcher v4.0.7 requires php ^7.1.3 -> your PHP version (7.1.10) overridden by "config.platform.php" version (7.0.10) does not satisfy that requirement.
    - symfony/event-dispatcher v4.0.7 requires php ^7.1.3 -> your PHP version (7.1.10) overridden by "config.platform.php" version (7.0.10) does not satisfy that requirement.
    - Installation request for symfony/event-dispatcher (locked at v4.0.7) -> satisfiable by symfony/event-dispatcher[v4.0.7].


Installation failed, reverting ./composer.json to its original content.
```
I set config.platform.php" version (7.0.10) because in cli i have php 7.1 but in MAMP it's php7.0
And i don't want to upgrade my MAMP to php 7.1
my question is:
Why is event-dispatcher locked at 4.0.7? can't i use v3.x?
please help.

**Comment by jens1o** [comment]
Please file this issue at symfony's repo. This is not our problem.

**Comment by ulfw** [comment]
additionally: there is another problem with the php version
composer requires at least php v5.39 or v7.0
but the also required doctrine cache requires php v7.1

so update composer required section to php ^7.1 and its fine
