### ISSUE TITLE
Can't encode video Fatal error

### ISSUE THREAD

**Issue by iki789** [PHP-FFMpeg/PHP-FFMpeg#539]
| Q              | A
| -------------- | ---
| Bug?           | Yes
| New Feature?   | no
| Version Used   | v0.11.1
| FFmpeg Version |  N-90920-ge07b1913fc
| OS             | Windows 10 x64

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?
I'm trying to encode an video however I keep getting this fatal error:

> Fatal error:  Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command C:\ffmpeg\bin\ffmpeg.EXE -y -i C:\wamp64\www\memevibe\vid.mp4 -vcodec libx264 -acodec libfaac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 256k -ac 2 -pass 1 -passlogfile "C:\WINDOWS\TEMP\ffmpeg-passes5b1135d42c19c9th7l/pass-5b1135d42c4bc" C:\wamp64\www\memevibe\vid21.mp4 in C:\wamp64\www\memevibe\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php:100
> Stack trace:
> #0 C:\wamp64\www\memevibe\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure('C:\\ffmpeg\\bin\\f...')
> #1 C:\wamp64\www\memevibe\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false)
> #2 C:\wamp64\www\memevibe\vendor\alchemy\binar in C:\wamp64\www\memevibe\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\Video.php on line 109

Here is my code which is really basic.

```
$ffmpeg = \FFMpeg\FFMpeg::create();
$video = $ffmpeg->open($video_path);
$format = new \FFMpeg\Format\Video\X264();

$video->save($format, "C:\\wamp64\\www\\web\\vid21.mp4");

```

$video->save(...) is throwing the error

I also tried catching exceptions but failed to.
```
try{
  ...
}catch(\Alchemy\BinaryDriver\ConfigurationInterface $e){
  echo $e->getMessage();
}catch(\Alchemy\BinaryDriver\Exception\ExecutionFailureException $e){
  echo $e->getMessage();
}catch(\FFMpeg\Driver\FFProbeDriver $e){
  echo $e->getMessage();
}
```

**Comment by jens1o** [comment]
Could you please execute the command `C:\ffmpeg\bin\ffmpeg.EXE -y -i C:\wamp64\www\memevibe\vid.mp4 -vcodec libx264 -acodec libfaac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 256k -ac 2` using `cmd` and report the output?

**Comment by iki789** [comment]
Executing: 
`ffmpeg.EXE -y -i C:\wamp64\www\memevibe\vid.mp4 -vcodec libx264 -acodec libfaac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 256k -ac 2 C:\wamp64\www\memevibe\vid1.mp4`

leads to an error saying **Unknown encoder 'libfaac'**

**Comment by jens1o** [comment]
That's weird, as we are preferring aac over libfaac..

https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/0c1ed583e6dbb9101c2017947de49bea75da70fa/src/FFMpeg/Format/Video/X264.php#L74

**Comment by iki789** [comment]
Hmm. Maybe change [this](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/0c1ed583e6dbb9101c2017947de49bea75da70fa/src/FFMpeg/Format/Video/X264.php#L43) to 'aac'

**Comment by jens1o** [comment]
@iki789 Oh, good catch. Would you mind filing a pr to change it?

**Comment by chris-redbeed** [comment]
For me only `aac` works

**Comment by jens1o** [comment]
Does somebody wants to create a PR? :)

**Comment by Romain** [comment]
@jens1o @chris-redbeed @iki789 If the problem is `libfaac`, why would we change default value from MP3 to AAC?

**Comment by Romain** [comment]
As an answer to my previous comment, the link posted by @iki789 pointed to the `DefaultVideo` class which uses MP3 as the default codec, when  the PR #759 created by @41i-6h0rb4n1 actually addresses the X264 class, which is where the error resided.
