### ISSUE TITLE
isValid method Exception handling

### ISSUE THREAD

**Issue by carrotis** [PHP-FFMpeg/PHP-FFMpeg#545]
Hi
I use "isvaild" function to check correct video or not.

eg.
        $ffprobe = FFMpeg\FFProbe::create();
        try {
          $ffprobe->isValid($src_video_path);
        } catch (Exception $e) {
                echo " wrong format";
        } 

But try / catch method not work when wrong format.
Terminate immediately with message " PHP Fatal error:  Uncaught Error: Call to a member function get() on null in ... "
How can I do that ?

**Comment by jens1o** [comment]
`Terminate immediately with message " PHP Fatal error: Uncaught Error: Call to a member function get() on null in ... "`

Please paste the full error message, sounds like you found a bug.

**Comment by carrotis** [comment]
Sorry, late reply.
It's same code, I want to do  call API server if the video file has problem.
But it's terminate before calling.
 
      $src_video_path="broken_video.avi";

      try {
          $ffprobe->isValid($src_video_path);
        } catch (Exception $e) {
            echo 'Caught exception: ',  $e->getMessage(), "\n";
            $description = array('comment'=> "not valid video" );
            ApiCall ( $description );
            exit ;
       }

**Comment by jens1o** [comment]
Looks like you are misunderstanding something. `$ffprobe->isValid()` returns only a bool(`true/false`), and does not throw an exception. You need to check the return status on your own.
