### ISSUE TITLE
ffmpeg with nice (CPU priority)

### ISSUE THREAD

**Issue by skaynetmen** [PHP-FFMpeg/PHP-FFMpeg#546]
Is there any way to start the conversion with [nice](https://en.wikipedia.org/wiki/Nice_(Unix))?

on linux on the command line it looks like this:
`nice -n 10 ffmpeg -i input.mp4 output.mkv`

**Comment by jens1o** [comment]
No, that's not possible. You could try using `proc_nice` before, because the subprocesses also inherit that value :)
