### ISSUE TITLE
this error showing

### ISSUE THREAD

**Issue by rohitgaidhane** [PHP-FFMpeg/PHP-FFMpeg#552]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | windows 10

#### Actual Behavior
Actually i wanted to Compress video so is that possible or not?................
( ! ) Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutableNotFoundException' with message 'Executable not found, proposed : avprobe, ffprobe' in C:\wamp64\www\imgcomp\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php on line 50
--

i m working on php

**Comment by jens1o** [comment]
You need to install the binary ffmpeg to use this libary.
