### ISSUE TITLE
\FFMpeg\Format\Audio\Aac uses non-native codec by default

### ISSUE THREAD

**Issue by bensquire** [PHP-FFMpeg/PHP-FFMpeg#567]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | 0.12.0
| FFmpeg Version | 4.0.2 (static)
| OS             | Centos7

#### Actual Behavior

Encode failure because codec doesn't exist

#### Expected Behavior

Encode works

#### Steps to Reproduce

Use a static version of FFMPEG (such as https://johnvansickle.com/ffmpeg/) which doesn't include the libfdk_aac codec

#### Possible Solutions

Update \FFMpeg\Format\Audio\Aac to include 'aac' as well as 'libfdk_aac'. Given that 'aac' native always exists, maybe 'libfdk_aac' shouldn't be the default.

#### Updated class
```
<?php

/*
 * This file is part of PHP-FFmpeg.
 *
 * (c) Alchemy <info@alchemy.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace FFMpeg\Format\Audio;

/**
 * The AAC audio format
 */
class Aac extends DefaultAudio
{
    public function __construct()
    {
        $this->audioCodec = 'aac';
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableAudioCodecs()
    {
        return array('libfdk_aac', 'aac');
    }
}
```

**Comment by jens1o** [comment]
Thanks for the bug report. Do you want to fix this and make a pull request on the `1.x` branch?

**Comment by bensquire** [comment]
@jens1o done...

**Comment by jens1o** [comment]
thank you. :) Please use `setAudioCodec` for now. :)

**Comment by artem-dev2** [comment]
> thank you. :) Please use `setAudioCodec` for now. :)

Does not help:

 $format = new Aac();
 $format->setAudioCodec('aac');

Getting: 
 "Error converting file: Wrong audiocodec value for aac, available formats are libfdk_aac"

**Comment by olaulau** [comment]
this PR solves this issue : https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/880
