### ISSUE TITLE
Missing string type hint

### ISSUE THREAD

**Issue by eriksulymosi** [PHP-FFMpeg/PHP-FFMpeg#570]
https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/dd47d409667621230a49205acde029a1df9561dd/src/FFMpeg/Media/AbstractVideo.php#L125

https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/dd47d409667621230a49205acde029a1df9561dd/src/FFMpeg/Media/AbstractVideo.php#L144

PHP Warning:  Declaration of FFMpeg/Media/AbstractVideo::getFinalCommand(FFMpeg/Format/FormatInterface $format, $outputPathfile) should be compatible with FFMpeg/Media/Audio::getFinalCommand(FFMpeg/Format/FormatInterface $format, string $outputPathfile) in /home/erik/Code/Web/PointMedia/drive/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/
Media/AbstractVideo.php on line 27

**Comment by jens1o** [comment]
Which version are you using?

**Comment by jens1o** [comment]
Okay, you know that this is currently unstable. ;) Would you like to file a PR?

**Comment by eriksulymosi** [comment]
i know it, but the older one has some compatibility problem with Laravel 5.7.

PR is here: https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/571

**Comment by jens1o** [comment]
thanks, fixed.

**Comment by eriksulymosi** [comment]
thanks for merge ;)
