### ISSUE TITLE
Best way for adding extra commands

### ISSUE THREAD

**Issue by kenianbei** [PHP-FFMpeg/PHP-FFMpeg#574]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | yes
| Version Used   |v0.12
| FFmpeg Version | ffmpeg 4.0
| OS             | linux

#### Actual Behavior

Following up from issue #431 
It would be nice to be able to add extra custom commands

#### Expected Behavior

Ability to add extra commands to save method

#### Steps to Reproduce

NA

#### Possible Solutions

I'm not sure how best to go about this, but being able to pass some appended commands in the save method for Audio and Video would be nice, such as:

```php
$commands = [
  'max_muxing_queue_size' => 2400
];

$video->save($format, $output, $commands);
```

Let me know if you have advice on this, I have time to write this and submit a PR.

**Comment by jens1o** [comment]
Cool you want to get involved! Personally, I would rewrite the entire filter system and add priorities to every single command part, and then we can simply inject some with a priority, and then the users are literally able to put them anywhere they want.

**Comment by Xakki** [comment]
$format->setAdditionalParameters(['-max_muxing_queue_size' , '4096']);

> Q 	A
> Bug? 	no
> New Feature? 	yes
> Version Used 	v0.12
> FFmpeg Version 	ffmpeg 4.0
> OS 	linux
> #### Actual Behavior
> 
> Following up from issue #431
> It would be nice to be able to add extra custom commands
> #### Expected Behavior
> 
> Ability to add extra commands to save method
> #### Steps to Reproduce
> 
> NA
> #### Possible Solutions
> 
> I'm not sure how best to go about this, but being able to pass some appended commands in the save method for Audio and Video would be nice, such as:
> 
> ```
> $commands = [
>   'max_muxing_queue_size' => 2400
> ];
> 
> $video->save($format, $output, $commands);
> ```
> 
> Let me know if you have advice on this, I have time to write this and submit a PR.

You need this
$format->setAdditionalParameters(['-max_muxing_queue_size' , '4096']);

**Comment by kenianbei** [comment]
Thanks, that's what I eventually did...
