### ISSUE TITLE
Symfony 4 compatible release

### ISSUE THREAD

**Issue by wachterjohannes** [PHP-FFMpeg/PHP-FFMpeg#575]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | current master
| FFmpeg Version | none
| OS             | none

##### Question

I saw that you changed your dependencies to be compatible to symfony 4 a few weeks ago. When do you plan to release this change? The reason why i ask is, that we from @sulu depend on your library and cannot upgrade to because of this missing release 🙈

**Comment by jens1o** [comment]
thanks for the ping, I just missed that it was in the `0.x` release. See https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/559#issuecomment-423138352

**Comment by wachterjohannes** [comment]
@jens1o thanks for the quick response :)
