### ISSUE TITLE
Unable to save concatenated video

### ISSUE THREAD

**Issue by FrancescoMussi** [PHP-FFMpeg/PHP-FFMpeg#580]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | dev-master#c11b79ab5b0174aa1a56c54c67491169e78a4c17
| FFmpeg Version | 4.0.2
| OS             | MacOS High Sierra 10.13.6

#### Actual Behavior

I am trying to concat two videos, but I am getting the following error:

`ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-f' 'concat' '-safe' '0' '-i' '/private/var/folders/dw/919v2nds7s78pz_qhp7z9rcm0000gn/T/ffmpeg-concateaHp0L' '-c' 'copy' '/Users/francescomussi/Desktop/Apps/cameraProject/back-end/camera-laravel/storage/app/public/videos/output.mp4'`

This is a dump of the commands:

![screen shot 2018-10-01 at 16 59 53](https://user-images.githubusercontent.com/5312907/46294027-8ebba680-c59d-11e8-976f-87d20c2d4404.png)

#### Expected Behavior

I expected the command to be executed.

#### Steps to Reproduce

For the code I am following the docs:

```
$video = $ffmpeg->open( $path1 );
$video
    ->concat(array($path1, $path2))
    ->saveFromSameCodecs($path_output, TRUE);

```

**EDIT:** 
I have tried a basic resizing and conversion and it worked fine. 
So it should everything alright with the installation of the library and the installation of FFMpeg in the system. 
So it may be just related with some details concerning the concat.

**EDIT2:**
I have opened a SO question: https://stackoverflow.com/questions/52593866/php-ffmpeg-how-to-properly-concatenate-two-videos 
And it seems that another user (this time on windows) encounter the same issue.
Could you please be so kind to test if the concat function it is still working properly?
Thanks!

**Comment by rolandstarke** [comment]
Changing the following line:
https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/fc8dbd6f02d1682c8db810b30897bf0bc5219db0/src/FFMpeg/Media/Concat.php#L108
to
```php
$line .= "file '".$videoPath . "'";
```
Fixed the issue for me. But i don't know whats the correct escaping here.




Here the contents of the temp file not working
```
file C:\Users\Roland\Documents\MyStuff\programmieren\test/big_buck_bunny.mp4
file C:\Users\Roland\Documents\MyStuff\programmieren\test/big_buck_bunny.mp4
```
and here the working version
```
file 'C:\Users\Roland\Documents\MyStuff\programmieren\test/big_buck_bunny.mp4'
file 'C:\Users\Roland\Documents\MyStuff\programmieren\test/big_buck_bunny.mp4'
```

**Comment by FrancescoMussi** [comment]
I think I have found the cause.

When I am trying to concat using the command line: 

`ffmpeg -f concat -safe 0 -i mylist.txt -c copy output.mp4`

I get this error:

![screen shot 2018-10-02 at 11 29 01](https://user-images.githubusercontent.com/5312907/46338787-cb3ce000-c639-11e8-9085-5538e3dbfde8.png)

And that may be because the two video files have audio opus codec.

So if I run this commands it works:

`ffmpeg -f concat -safe 0 -i mylist.txt -c:v copy -c:a aac output.mp4`

The video is properly created as a concatenation of the two videos.

Do you know how can change the code, in order to convert the output file to aac?

**Comment by rolandstarke** [comment]
Hey, ah so its something with the mp4 files themselves. Sadly my skills are
limited to reading the docs. So maybe using saveFromDifferentCodecs could
help.

// In order to instantiate the video object, you HAVE TO pass a path
to a valid video file.// We recommand that you put there the path of
any of the video you want to use in this concatenation.$video =
$ffmpeg->open( '/path/to/video' );
$format = new FFMpeg\Format\Video\X264();$format->setAudioCodec("libmp3lame");
$video
    ->concat(array('/path/to/video1', '/path/to/video2'))
    ->saveFromDifferentCodecs($format, '/path/to/new_file');

But if that dosn’t help i am out of luck.

Am Di., 2. Okt. 2018 um 10:57 Uhr schrieb Francesco Mussi <
notifications@github.com>:

**Comment by jens1o** [comment]
> Do you know how can change the code, in order to convert the output file to aac?

Not supported directly, yet. Although it sounds very decent for a new version(1.x).

**Comment by jens1o** [comment]
Please send us the hole output of `/usr/local/bin/ffmpeg -f concat -safe 0 -i /private/var/folders/dw/919v2nds7s78pz_qhp7z9rcm0000gn/T/ffmpeg-concatVZ6Ncg -c copy /Users/francescomussi/Desktop/Apps/cameraProject/back-end/camera-laravel/storage/app/public/videos/output.mp4`

**Comment by FrancescoMussi** [comment]
This is the output:

`/private/var/folders/dw/919v2nds7s78pz_qhp7z9rcm0000gn/T/ffmpeg-concatVZ6Ncg: No such file or directory`

![screen shot 2018-10-03 at 12 02 36](https://user-images.githubusercontent.com/5312907/46400968-626e6a00-c704-11e8-9d82-24d7e6d6bf99.png)

This is what happen inside the folder `/private/var/folders/dw/919v2nds7s78pz_qhp7z9rcm0000gn/T/` right after I run the command:

![ffmpeg](https://media.giphy.com/media/x49zVLcNvbKcsi2KSB/giphy.gif)

Something is being created and deleted soon afterwards

**Comment by jens1o** [comment]
Okay, more debugging here. I need a full list of files(with their respective filepath) you want to concat.

**Comment by FrancescoMussi** [comment]
These are the paths of the two mp4 videos and the output:

![screen shot 2018-10-03 at 12 34 10](https://user-images.githubusercontent.com/5312907/46402633-fb06e900-c708-11e8-9bda-eb25b8f488f2.png)

**Comment by FrancescoMussi** [comment]
If I can exclude with certainty some reasons for the failure I would say:
- It's not because of the files themselves (I have tried with many different mp4 and webm videos - also video samples downloaded here and there)
- It's not because of the path (I don't get any ffprobe error message)
- It's not because of the ffmpeg in the system (command lines in console work. I also have reinstalled it with all the possible libraries included)

What else can be?
The library has been installed through the laravel bundle: https://github.com/pascalbaljetmedia/laravel-ffmpeg

In the composer.json of that bundle, the PHP-FFMpeg library is included as following:

`"php-ffmpeg/php-ffmpeg": "dev-master#c11b79ab5b0174aa1a56c54c67491169e78a4c17",`

Is that correct? I am not sure which version is that..

**Comment by FrancescoMussi** [comment]
And actually this is the whole code:

```
$disk = FFMpeg::fromDisk('local');

$video1 = $disk->open('public/videos/test3.mp4');
$video2 = $disk->open('public/videos/test4.mp4');
$output = $disk->open('public/videos/output.mp4');
$path1 = $video1->getPathfile();
$path2 = $video2->getPathfile();
$output_path = $output->getPathfile();

$result = $video1
    ->concat([$path1, $path2])
    ->saveFromSameCodecs($output_path, TRUE);

return response()->json(compact('result')); 
```

**Comment by FrancescoMussi** [comment]
The issue has been finally been resolved!

The problem was that I totally misunderstood about the output file.
I thought it has to exists and with video and audio coded of the other two.
I don't remember where I read or if I dream about.

That was the reason why it was failing...

If the output doesn't exists then everything works perfectly!!

Thank you very much for your time

By the way is it possible to improve that error message in the source code.
For example: 

- before executing the commands - check that there is no existing file in the output_path given. 

- If it exists then give error: 'output file already exists in the path given. Commands cannot be executed'

Something like that. 
Otherwise `ffmpeg failed to execute command ...` is generic and difficult to identify the actual cause.

If is possible would be great!

**Comment by jens1o** [comment]
Great! Yeah, giving users a hint what could have failed is on track #310 :)

**Comment by FrancescoMussi** [comment]
Ah great! That will be perfect!

**Comment by VicGUTT** [comment]
If anyone is still encountering this problem (on Window at least), consider the following code :

``` php

// Creating the files to work with
// $this->storage --> \Illuminate\Support\Facades\Storage::disk('testing')
if (!$this->storage->exists('ffmpeg/file-to-concat-1.mp4')) {
    $this->storage->copy('ffmpeg/some-file.mp4', 'ffmpeg/file-to-concat-1.mp4');
}
if (!$this->storage->exists('ffmpeg/file-to-concat-2.mp4')) {
    $this->storage->copy('ffmpeg/some-file.mp4', 'ffmpeg/file-to-concat-2.mp4');
}
if (!$this->storage->exists('ffmpeg/file-to-concat-3.mp4')) {
    $this->storage->copy('ffmpeg/some-file.mp4', 'ffmpeg/file-to-concat-3.mp4');
}

$basePath = storage_path('app/testing/ffmpeg');

// $this->ffmpeg --> \Pbmedia\LaravelFFMpeg\FFMpegFacade
$this->ffmpeg::fromDisk('testing')->open('ffmpeg/file-to-concat-1.mp4')
        ->concat([
            str_replace('\\', '/', $basePath . '/file-to-concat-2.mp4'),
            str_replace('\\', '/', $basePath . '/file-to-concat-3.mp4')
        ])
        ->saveFromSameCodecs(str_replace('\\', '/', $basePath . '/' . time() . '-concatinated-file.mp4'), true);

```

The important things to note here are :
- `str_replace('\\', '/', 'full-path-to-file-to-concat.mp4')`
- `saveFromSameCodecs(str_replace('\\', '/', 'full-path-to-file-to-concatinated-file-uniquely-named.mp4'), true);`

**Explication**

My code kept throwing the _"Unable to save concatenated video"_ error and it was impossible to figure out why from the this PHP package side of things. So I in my terminal I had to reproduce what the [Concat.php#L82](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/f9cc3d0c429fade5a144db674272eb8b48db8dce/src/FFMpeg/Media/Concat.php#L82) was doing, which is (for those too lazy to read the code) :
Create a _file-to-concat-list.txt_ with the following content :
``` txt
file C:/[...]/file-to-concat-2.mp4
file C:/[...]/file-to-concat-3.mp4
```
_replacing all the `\` with `/`_, otherwise you'll get an `Impossible to open 'file-to-concat-2.mp4'`.

And finally running the command :
```
"C:/ffmpeg/bin/ffmpeg.exe" -f concat -safe 0 -i C:/[...]/file-to-concat-list.txt -c copy "C:/[...]/concatinated-file.mp4"
```
After some trials and errors I adapted my code to one that finally work as posted above.
Hope it helps 👌
