### ISSUE TITLE
Unable to probe video in Laravel ffmpeg

### ISSUE THREAD

**Issue by CodeGirl300** [PHP-FFMpeg/PHP-FFMpeg#589]
I need help. I keep getting error unable to probe myvideo.mp4 here is my code

`  $ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('myvideo.mp4');
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
    ->save('frame.jpg');
$video
    ->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4')
    ->save(new FFMpeg\Format\Video\WMV(), 'export-wmv.wmv')
    ->save(new FFMpeg\Format\Video\WebM(), 'export-webm.webm');`

**Comment by jens1o** [comment]
Please fill out the issue template.
