### ISSUE TITLE
Overlaying Audio Files.

### ISSUE THREAD

**Issue by Mzril** [PHP-FFMpeg/PHP-FFMpeg#590]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | Yes
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

I'd like the request to be able to apply complex filters with delays as seen
[here](https://superuser.com/questions/1172109/how-to-concatenate-several-short-audio-mp3-files-with-a-specific-overlap-duratio?noredirect=1&lq=1), I didn't see anything remotely similar documented, and I was wonder if there was an option to do a "raw" command. 

It would be exactly this command. 

ffmpeg -i 1.mp3 -i 2.mp3 -i 3.mp3 -i 4.mp3
   -filter_complex
     "[1]adelay=delay1|delay1[b];
      [2]adelay=delay2|delay2[c];
      [3]adelay=delay3|delay3[d];
      [0][b][c][d]amix=4"
merged.mp3

In order to overlay several audio files at differing points of time.

**Comment by jens1o** [comment]
Sounds like a good idea. Feel free to file a PR :)
