### ISSUE TITLE
convertion of files with a set of formats to eachother

### ISSUE THREAD

**Issue by xtoolkit** [PHP-FFMpeg/PHP-FFMpeg#595]
I've been trying to use this library from I came to find on gitcomposer to convert a set of audi/video formats to eachother. To give you more insight on what I want to do I'm gonna make use of an example.
Imagine there's an application that has a file on a server with mp4 format and I want the server to automatically create the same file with other formats such as m4v, ogv, webm and webmv using this library and if the application has any other format in this set like webm, I want the server to convert that file to other formats in the mentioned set which are m4v, ogv, webmv and mp4 formats.
I've studied the article below which gives a detailed guide on how this can be done via mentioned library but it get quite confusing for me so I wanted to know whether there was another simpler and quicker way to do this without taking special cases about codec type into account or not?
Thank you for your time in advance

**Comment by jens1o** [comment]
I'm sorry, but I do not write any code for you. You're looking for a file watcher basically.
