### ISSUE TITLE
PHP FFMPEG ERROR : Unable to open key file

### ISSUE THREAD

**Issue by artxuan** [PHP-FFMpeg/PHP-FFMpeg#597]
i use php ffmpeg download m3u8 file , error Unable to open key file;
but try at Terminal run 

> ffmpeg -i "https://hls.xxxxx.net/edadcab31a13794380_1.m3u8?ts=1540540201000&sign=331ea6fcd4a82b56c0ba4d89f3f7e951&pid=1540540133233X1717798" -c copy 1.ts
it's success!

PHP code is as follows

> ```
> date_default_timezone_set("Asia/Shanghai");
> require 'vendor/autoload.php';
> $ffmpeg = FFMpeg\FFMpeg::create();
> $ffmpeg->getFFMpegDriver()->listen(new \Alchemy\BinaryDriver\Listeners\DebugListener());
> $ffmpeg->getFFMpegDriver()->on('debug', function ($message) {
>     echo $message."\n";
> });
> $videos = 'https://hls.xxxxx.net/edadcab31a13794380_1.m3u8?ts=1540540201000&sign=331ea6fcd4a82b56c0ba4d89f3f7e951&pid=1540540133233X1717798';
> 
> $video = $ffmpeg->open($videos);
> $video
>     ->save(new FFMpeg\Format\Video\X264('libfaac', 'libx264'), 'test.ts');
> ```

**Comment by jens1o** [comment]
Please do not download in production areas. I'm not able to assist any further without a link.

**Comment by artxuan** [comment]
> Please do not download something when possible in production areas. I'm not able to assist any further without a link.

link need user-sign , only support once link and five min time;

**Comment by jens1o** [comment]
Then please find a example I can reproduce with. Feel free to reopen this as you have found a way to reproduce this with public sources.

**Comment by artxuan** [comment]
> Then please find an example I can reproduce with. Feel free to reopen this as you have found a way to reproduce this with public sources.

http://hls.videocc.net/a0dedeea8b/5/a0dedeea8beabadb1ff41551aa6cd755_3.m3u8?pid=1540607205494X1620202
