### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by StudyForZX** [PHP-FFMpeg/PHP-FFMpeg#600]
My environment：
+ PHP version: '7.2.1'
+ php-ffmpeg: '0.13.0'

Error info:
+ PHP error: 500 Internal Server Error
+ Apache log: [Mon Oct 29 16:13:54.280059 2018] [core:error] [pid 74008:tid 2092] [client 127.0.0.1:11252] End of script output before headers: index.php

When I switch PHP version to '7.0.12', it still has problem:
Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in dir\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php on line 16

How to resolve this? please, thank u guys.

**Comment by jens1o** [comment]
> `\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php`

It looks like it is not ready for PHP 7.x in the version we use in the `0.x` branch.

**Comment by jens1o** [comment]
I do not have access to my development machine right now, but could you upload the contents of the file `\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php`, please? I assume you are on windows?

**Comment by StudyForZX** [comment]
Yes,My development environment is windows。

CacheProvider.php  line 16:
```php
abstract class CacheProvider implements Cache, FlushableCache, ClearableCache, MultiOperationCache
{
    public const DOCTRINE_NAMESPACE_CACHEKEY = 'DoctrineNamespaceCacheKey[%s]'; // line 16
    ...
}
```
I have no idea where the address `hastebin/pastebin/gist/` is, sorry.

Are you really 16 years old? Why r u so cool？

**Comment by jens1o** [comment]
Okay, thank you. Please remain using PHP 7.2([doctrine is using newer language features there](https://secure.php.net/manual/en/migration71.new-features.php#migration71.new-features.class-constant-visibility)).

Apache is basically telling that the HTTP headers are missing. Could you provide the logging lines before this(for the same request only)?

> I have no idea where the address hastebin/pastebin/gist/ is, sorry.

This is a place where you can upload such files. 
For example: https://hastebin.com/ , http://pastebin.com/ or https://gist.github.com/

> Are you really 16 years old? Why r u so cool？

haha, thanks.

**Comment by StudyForZX** [comment]
```shell
$ ./httpd -v
Server version: Apache/2.4.23 (Win32)
Server built:   Jul  1 2016 16:42:20
```
The whole request only recorded one log
`End of script output before headers: index.php`

The problem might be clearly when  I run the script on the command line:
```shell
PHP Fatal error:  Uncaught Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in dir\vendor\alche
my\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php:160

Next FFMpeg\Exce in dir\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php on line 50
```

AbstractBinary.php line 160:
```php

    /**
     * {@inheritdoc}
     */
    public static function load($binaries, LoggerInterface $logger = null, $configuration = array())
    {
        $finder = new ExecutableFinder();
        $binary = null;
        $binaries = is_array($binaries) ? $binaries : array($binaries);

        foreach ($binaries as $candidate) {
            if (file_exists($candidate) && is_executable($candidate)) {
                $binary = $candidate;
                break;
            }
            if (null !== $binary = $finder->find($candidate)) {
                break;
            }
        }

        if (null === $binary) {
            throw new ExecutableNotFoundException(sprintf( // line 160
                'Executable not found, proposed : %s', implode(', ', $binaries)
            ));
        }

        if (null === $logger) {
            $logger = new Logger(__NAMESPACE__ . ' logger');
            $logger->pushHandler(new NullHandler());
        }

        $configuration = $configuration instanceof ConfigurationInterface ? $configuration : new Configuration($configuration);

        return new static(new ProcessBuilderFactory($binary), $logger, $configuration);
    }
```
FFProbeDriver.php line 50:

```php
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'ffprobe';
    }

    /**
     * Creates an FFProbeDriver.
     *
     * @param array|ConfigurationInterface $configuration
     * @param LoggerInterface              $logger
     *
     * @return FFProbeDriver
     */
    public static function create($configuration, LoggerInterface $logger = null)
    {
        if (!$configuration instanceof ConfigurationInterface) {
            $configuration = new Configuration($configuration);
        }

        $binaries = $configuration->get('ffprobe.binaries', array('avprobe', 'ffprobe'));

        try {
            return static::load($binaries, $logger, $configuration);
        } catch (BinaryDriverExecutableNotFound $e) {
            throw new ExecutableNotFoundException('Unable to load FFProbe', $e->getCode(), $e); // line 50
        }
    }
```

I not only run the demo script and install composer normaly but also do the same thing on another pc.The same problem it is, so I think this should be internal error.To be honestly,I am very curiously that why other people doesn't in this case.

**Comment by jens1o** [comment]
I think you may run into `max_execution_time` errors. Could you try increasing those timeouts(both php.ini and httpd.conf) or try a smaller file to process?

**Comment by fishcg** [comment]
I have this problem, I update my php.ini:
```sh
max_execution_time = 0 # no limit
```
but it don't work
```sh
End of script output before headers: index.php
```
