### ISSUE TITLE
how install it with composer?

### ISSUE THREAD

**Issue by pws2016** [PHP-FFMpeg/PHP-FFMpeg#602]
I want install your script in my local host (wamp), but i don't know anything on composer and how use it!
plzease can help me and get me how i can install the script step by step?

thanks

**Comment by jens1o** [comment]
Please do a (quick) research before asking stuff here. :)

But basically:

https://getcomposer.org/doc/00-intro.md

go into the right directory you want it to be installed.

https://github.com/PHP-FFMpeg/PHP-FFMpeg#installation
