### ISSUE TITLE
How to remove a video bitrate option?

### ISSUE THREAD

**Issue by phamhoangha** [PHP-FFMpeg/PHP-FFMpeg#605]
Hello. I'm want to convert video() to an mp4 file with no **-b:v** option.
But **-b:v 1000k** is default option of API.
How can I remove this option?

**Comment by jens1o** [comment]
You could try setting additional parameters and then set the same `-b:v` as you got from the/one input.

ref #430

**Comment by phamhoangha** [comment]
I had tried.
ffmpeg can't get a video bitrate from mpeg format.
I'll try another way
Thanks for your reply.
