### ISSUE TITLE
Q: Server 'freeze' on ffmpeg action?

### ISSUE THREAD

**Issue by itsRems** [PHP-FFMpeg/PHP-FFMpeg#606]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.13.0
| FFmpeg Version | FFmpeg 3.4.4
| OS             | Unbuntu 18.04.1 - Apache2

####Introduction
Hi,
I'm working on a video platform project an plan to use php-ffmpeg for a while (we can't afford big transcoding server, all has to be done on the same server).
So I've added a function that takes the file people upload and transcodes it to mp4 (We only accept mp4, webm & ogg for now, but are planning to accept as many as possible)
The only problem is that when I transcode a video via the php-ffmpeg library, the server 'freezes' until the encoding is done; The entire server returns a loading loop. I don't know if this is normal (even though it seems sort of normal for me) and if there is a way to avoid that.
#### Actual Behavior

Server "freeze" on video transcode: the website becomes unavaible until the ffmpeg action is done.

#### Expected Behavior

No freeze: being able to use the website while the action is in progress.

#### Steps to Reproduce

Try to encode a file with an apache server, I guess?

**Comment by jens1o** [comment]
You can increase the number of parallel php processes handling incoming requests to resolve this issue.

Please note that it is not recommended to let this action be executed in the same request as the user is uploading it.

I'd create a background queue, that processes such media and the user may poll in that time.

**Comment by MrGoatsy** [comment]
How would you go about creating a background queue?
