### ISSUE TITLE
How to create a tile image from a video?

### ISSUE THREAD

**Issue by iljalukin** [PHP-FFMpeg/PHP-FFMpeg#610]
I'm using ffmpeg with the following command for a spritemap creation:

`ffmpeg -i input.mp4 -vf 'scale=142:80,fps=1,tile=10x10:margin=2:padding=2' output.jpg`

I've already tried to use the CustomFilter to create it within PHP-FFmpeg, but it lacks of saving image formats. What could be done to save the filtered tile image?

**Comment by iljalukin** [comment]
I've ended up with implementing CustomFrameFilter using existing CustomFilter as an example.
The following code works for me:
```php
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('/some/video.mp4');
$video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(0))
      ->addFilter(new CustomFrameFilter('scale=142:80,fps=1,tile=10x10:margin=2:padding=2'))
      ->save('/some/picture.jpg');
```
Please look at https://github.com/iljalukin/PHP-FFMpeg/commit/6dacd82c9b1c86e67563340d509b500815144178 whether it's worth for PR.

**Comment by jens1o** [comment]
This is great. It would be awesome if you file a PR. :)
