### ISSUE TITLE
IIS + PHP 7.2 = Your FFProbe version is too old and does not support `-help` option, please upgrade

### ISSUE THREAD

**Issue by TCB13** [PHP-FFMpeg/PHP-FFMpeg#612]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | `"php-ffmpeg/php-ffmpeg": "^0.13.0"`
| FFmpeg Version | 4.1-static
| OS             | Windows 10 Pro 64bit + 7.2.12 (cli) (built: Nov  8 2018 05:47:24) ( NTS MSVC15 (Visual C++ 2017) x64 )

#### Actual Behavior

```
try {
	$video = $this->ffmpeg->open($file);
	$frame = $video->frame(TimeCode::fromSeconds(5));
	$thumb = $frame->save(null, false, "image2");
} catch (\Exception $e) {
	$e...
}

```
`Your FFProbe version is too old and does not support `-help` option, please upgrade.`

#### Steps to Reproduce

1. Setup IIS + PHP 7.2;
2. Download ffmpeg 4.1-static (from here https://ffmpeg.zeranoe.com/builds/) to your website root;
3. Try to process some file

#### Possible Solutions

` ffprobe.exe -h` on the project root runs fine. However, inside PHP it hits this line:

![bug](https://user-images.githubusercontent.com/6315832/49453862-dea42d00-f7db-11e8-9778-86a10acc2288.png)

It appears that the process is returning the status code 0. I don't have disabled functions in my `php.ini`.

**Comment by jens1o** [comment]
This is most likely because of permission issues. I never worked with IIS, but does the user has access to the files you want to edit *and* may execute the `ff(probe|mpeg).exe` in your document root?

**Comment by TCB13** [comment]
@jens1o thanks for the answer. I'm not that experienced in IIS also but I found an interesting thing, if I run it on powershell calling PHP directly it works as expected, however via IIS I get this error.

**Comment by TCB13** [comment]
Managed to fix this, one more complex thing within IIS.

I had to change IIS Application Pool > Advanced Settings > Process Model > Identity from `ApplicationPoolIdentity` to `LocalSystem`.

Maybe this should be added to the readme?

**Comment by jens1o** [comment]
> Maybe this should be added to the readme?

I would love to see this. I never used this proprietary software once, I have no clue and I'd like somebody else to take responsibility on wording it.
