### ISSUE TITLE
Thumbnail resize not working

### ISSUE THREAD

**Issue by azaddeveloper** [PHP-FFMpeg/PHP-FFMpeg#613]
I am using this code, for changing the dimension of an image. But it is generating a thumbnail with its actual(video dimension) size.

$video = $ffmpeg->open('intro.mp4');
$video ->filters()
             ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
             ->synchronize();
$video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(1))
           ->save('save.jpg');

**Comment by jens1o** [comment]
Could you provide the original video you can reproduce with?

**Comment by azaddeveloper** [comment]
Sorry for the late answer .
This is the Dropbox URL, you will find the video from here.
https://www.dropbox.com/s/nsdx3royiurl1k2/intro.mp4?dl=0

**Comment by jens1o** [comment]
Thanks for your reply. I'm attending 35c3 now, so I cannot look at it until December, 31. I will look at this issue as soon as possible.

Thank you for your understanding.

**Comment by azaddeveloper** [comment]
ok

**Comment by azaddeveloper** [comment]
@jens1o  can you look on my issue?.

**Comment by jens1o** [comment]
Hi, this is a easy issue: works as designed.

The problem is, that you apply a resize filter on a video, and on the very same video(before you actually made it smaller), you are extracting a frame. This could be solved in a new version when there are (more) filters for a `Frame`. You cna solve your problem like this:

```php
<?php
declare(strict_types=1);

require_once './../vendor/autoload.php';

$ffmpeg = FFMpeg\FFMpeg::create();

$video = $ffmpeg->open('intro.mp4');
$video ->filters()
->resize(new FFMpeg\Coordinate\Dimension(320, 240))
->synchronize();
$video->save(new FFMpeg\Format\Video\X264('aac'), 'minified-intro.mp4');

$video = $ffmpeg->open('minified-intro.mp4');
$video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(1))
->save('save.jpg');
```

**Comment by azaddeveloper** [comment]
Hi @jens1o,
Thanks, It is working perfectly.
