### ISSUE TITLE
PHP-FFMpeg has no voice on the Apple operating system

### ISSUE THREAD

**Issue by ChinaBygones** [PHP-FFMpeg/PHP-FFMpeg#614]
PHP-FFMpeg has no voice on the Apple operating system, but downloading a player will make a voice on the Apple mobile phone as well. But Android has voice. My code is as follows.

```php

<?php
require 'vendor/autoload.php';
$ffmpeg = FFMpeg\FFMpeg::create(['ffmpeg.threads'=>"8"]);
$video = $ffmpeg->open('./sp.mp4');
$format = new FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage % transcoded";
});
$video->save($format, 'test.mp4');

```

**Comment by jens1o** [comment]
What do you mean with `voice`? Do you mean that there is no audio?

**Comment by ChinaBygones** [comment]
> 你是什​​么意思`voice`？你的意思是没有音频吗？

Thank you for your reply. Yeah, after the video is generated, there is no sound. I don't know what's going on or there are few parameters.

**Comment by jens1o** [comment]
Could you provide the file you can reproduce with? This is most likely not an issue with this driver itself.

**Comment by ChinaBygones** [comment]
> Could you provide the file you can reproduce with? This is most likely not an issue with this driver itself.

Okay, wait a minute. I'll pack it and upload it to GitHub for you to download.

**Comment by ChinaBygones** [comment]
> 你能提供你可以复制的文件吗？这很可能不是这个驱动程序本身的问题。

Okay, here's the code link you can clone

Https://github.com/ChinaBygones/PHP-FFmpegcode

**Comment by ChinaBygones** [comment]
> Could you provide the file you can reproduce with? This is most likely not an issue with this driver itself.

I solved it. I changed a decoder from libmp3lame to libfdk_aac. Thank you very much for your reply.

**Comment by jens1o** [comment]
I'm sorry, but I'm not able to be here 24/7. Glad it works for you now! :)
