### ISSUE TITLE
getenv()  went wrong

### ISSUE THREAD

**Issue by Jingfengshi** [PHP-FFMpeg/PHP-FFMpeg#620]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   |  ^0.13.0
| FFmpeg Version | 4.1
| OS             | win10

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?
When I was doing video processing, the server kept reporting 500 errors.

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

I found such a code snippet in vendor/symfony/process/Process.php
```
 private function getDefaultEnv()
    {
        $env = array();
        foreach ($_SERVER as $k => $v) {

            if (\is_string($v) && false !== $v = getenv($k)) {
                $env[$k] = $v;
            }
        }
        dump($env);
        foreach ($_ENV as $k => $v) {
            if (\is_string($v)) {
                $env[$k] = $v;
            }
        }

        return $env;
    }

```
I use php7.2.10 + Apache 
The getenv function acquiring $_REQUEST ['REMOTE_ADDR'] in Apache environment will report an error
#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

```
 private function getDefaultEnv()
    {
        $env = array();
        //foreach ($_SERVER as $k => $v) {

           // if (\is_string($v) && false !== $v = getenv($k)) {
              //  $env[$k] = $v;
            //}
        //}
        foreach ($_ENV as $k => $v) {
            if (\is_string($v)) {
                $env[$k] = $v;
            }
        }

        return $env;
    }
```
it works!

**Comment by jens1o** [comment]
I honestly do not believe this is an error, more like a bug of your server (mis-)configuration. Either way, we're using an unsupported version of `symfony/process`, so I don't believe this is getting fixed.
