### ISSUE TITLE
Extracting audio from video, ffmpeg command

### ISSUE THREAD

**Issue by Hesesses** [PHP-FFMpeg/PHP-FFMpeg#628]
When using ffmpeg on command line I have:
`ffmpeg -i video.mp4 -ss 00:03:05 -t 00:00:45 -vn -acodec copy audio.aac`

I would like to extract audio (copy, not re encoding) from video and specify start (-ss) and duration (-t) timecodes

Is this possible to do this with php-ffmpeg?

**Comment by jens1o** [comment]
You can see https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/252

Maybe separate processes will be needed to cut it afterwards.
