### ISSUE TITLE
how to get progress directly to a txt file rather than using file_put_contents...

### ISSUE THREAD

**Issue by huemane** [PHP-FFMpeg/PHP-FFMpeg#630]
Currently this is how i'm doing it but i know it can be done better (and hopefully faster!), just can't figure out how:

$format->setAdditionalParameters(...)
			
**```
$format->on('progress', function ($clip, $format, $percentage) {
				$pc = "$percentage";
				file_put_contents(ABSPATH . 'progress.txt', $pc);
```**

**Comment by jens1o** [comment]
I would ask something different: Do you really need to write it down? Memory-based databases (e.g. Redis) are proven to be much faster than using I/O. 

If you need to put it inside a file, there's no real way to make it better.

**Comment by huemane** [comment]
What i was hoping to find out is how can i get process.txt written directly to a txt file by ffmpeg?

In CLI mode they use the following:

`ffmpeg -i ".$image." -i ".$music." video.avi **1> progress.txt**`

But I am using thea different php coding method as follows:
    ```
$video = $ffmpeg->open($thevideo); // "path/to/video.mov"

    $video
      ->filters()
      ->resize(new \FFMpeg\Coordinate\Dimension(640, 360))
      ->synchronize();

			$format = new \FFMpeg\Format\Video\X264();
			$format->on('progress', function ($video, $format, $percentage) {
				$pc = "$percentage";
				file_put_contents('progress.txt', $pc);
			});
			
			$video->save($format, $newvideo);
```

Any ideas?
