### ISSUE TITLE
get process.txt written directly to a txt file by ffmpeg

### ISSUE THREAD

**Issue by huemane** [PHP-FFMpeg/PHP-FFMpeg#631]
Trying to find out is how can i get process.txt written directly to a txt file by ffmpeg?

In CLI mode they use the following:

`ffmpeg -i ".$image." -i ".$music." video.avi **1> progress.txt**`

But I am using the different phpFFMPEG method as follows:

```
$video = $ffmpeg->open($thevideo);

    $video
      ->filters()
      ->resize(new \FFMpeg\Coordinate\Dimension(640, 360))
      ->synchronize();

			$format = new \FFMpeg\Format\Video\X264();
			$format->on('progress', function ($video, $format, $percentage) {
				$pc = "$percentage";
				file_put_contents('progress.txt', $pc);
			});
			
			$video->save($format, $newvideo);
```

Any ideas how i can alter how I'm doing it which is messy to the cleaner way in first example?
Can't figure out where to put the write to process.txt statement in the code. Thanks for any HELP :)

**Comment by jens1o** [comment]
What do you actually want to achieve? You may need to say more about what you want to achieve, not how.

**Comment by huemane** [comment]
> What do you actually want to achieve? You may need to say more about what you want to achieve, not how.

I'm giving the user progress feedback during conversion. It works the way i'm doing it but it's slow.
It seems that FFMPEG has internal coding to write the progress to a file, I'm hoping that is faster.
Hence I'm trying to find out how i can implement it with my code.
I've seen different methods but they all seem to be for CLI mode or when executing a direct command...

**Comment by jens1o** [comment]
> Hence I'm trying to find out how i can implement it with my code.

This is the most appropiate solution. Are you sure this exact thing is causing the slowness? Do you have numbers for that?

**Comment by huemane** [comment]
Oh, I thought perhaps FFmpeg's built in method was probably faster.
Nevermind, thanks for the info!
