### ISSUE TITLE
FFprobe fails to analyze my video file on server, but working good on local.

### ISSUE THREAD

**Issue by alfazappy** [PHP-FFMpeg/PHP-FFMpeg#632]
Something went wrong: FFprobe failed to analyze your video file "/home/ejhi7ltfu7s2/public_html/application/controllers/Admin/../../../assets/Admin/videos/latest_news/d6a1b0917316550ba8751423bece143f.mp4".

**Comment by jens1o** [comment]
This is not useful at all. Please report that issue to your wrapper-wrapper, so we can get a more detailed cause of the exception.
