### ISSUE TITLE
Encoding failed

### ISSUE THREAD

**Issue by shankiflang** [PHP-FFMpeg/PHP-FFMpeg#634]
Hello,

I have a problem with the encode. I was coding on my windows computer and every things was fine. Since I put my laravel website on internet, ffmpeg can't encode my videos.
Here is the errors : 
`- ffmpeg failed to execute command './ffmpeg/ffmpeg' '-y' '-i' '/tmp/phpSANJ06' '-async' '1' '-metadata:s:v:0' 'start_time=0' '-f' 'webm' '-vcodec' 'libvpx' '-acodec' 'libvorbis' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' '[in]scale=256:144 [out]' '/home/slatsh/public_html/storage/app/files/lR5Wu12LSeE/videos/lR5Wu12LSeE_144.webm' (0)`
And
`The process has been signaled with signal "9". (0)`

Do you have any idea why my website, when in my host don't want to encode ?

Regards

**Comment by jens1o** [comment]
Could you manually execute `'./ffmpeg/ffmpeg' '-y' '-i' '/tmp/phpSANJ06' '-async' '1' '-metadata:s:v:0' 'start_time=0' '-f' 'webm' '-vcodec' 'libvpx' '-acodec' 'libvorbis' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-vf' '[in]scale=256:144 [out]' '/home/slatsh/public_html/storage/app/files/lR5Wu12LSeE/videos/lR5Wu12LSeE_144.webm'` and append the full output?
