### ISSUE TITLE
Execute command manually

### ISSUE THREAD

**Issue by 4unkur** [PHP-FFMpeg/PHP-FFMpeg#636]
First I was trying really hard to get it workin though the laravel package that's is wrapper of this lib. Then I tried to use it without wrapper. Finally I was able to find a command that will do what I need. It's:

```
ffmpeg -hide_banner -i myfile.webm -preset veryfast -c:v libx264 -c:a libmp3lame myfile.mp4
```

Is it possible to execute this command using your library or somehow set parameters to be like that?

**Comment by jens1o** [comment]
Could you try reading the README at first, please?

Anyway, this is not completely supported, yet(as we don't support presets at the moment.)

**Comment by lwmirkk** [comment]
This is old, but is it possible to somehow execute a previously created command? a manual command.
I already have and use commands in ffmpeg. I would like to bring them to php-ffmpeg.

Ty.
