### ISSUE TITLE
 Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command

### ISSUE THREAD

**Issue by Daksh14** [PHP-FFMpeg/PHP-FFMpeg#639]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.13.0
| FFmpeg Version | N-93548-g4d2f62150d
| OS             | Windows 10

#### Actual Behavior
`Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command C:\Fibble\nginx\Fibble\lib\\ffmpeg.EXE -y -i "C:/Fibble/nginx/Fibble/posts/33443rocketleague32bitdx914102018180636.mp4" -vcodec libx264 -acodec libfaac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k -pass 1 -passlogfile "C:\Users\HP\AppData\Local\Temp\ffmpeg-passes5cadedf1956e0sfdld/pass-5cadedf19588a" 33443rocketleague32bitdx914102018180636.mp4 in C:\Fibble\nginx\Fibble\lib\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php:100 Stack trace: #0 C:\Fibble\nginx\Fibble\lib\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure('C:\\Fibble\\nginx...') #1 C:\Fibble\nginx\Fibble\lib\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\ in C:\Fibble\nginx\Fibble\lib\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\AbstractVideo.php on line 106
`
#### Expected Behavior

I expect it to save as a mp4, with no errors.

#### Steps to Reproduce
```
move_uploaded_file($file_loc,$folder.$final_file);
$video = $ffmpeg->open("C:/Fibble/nginx/Fibble/posts/".$oldfile."");
          $final_file = substr($final_file, 0, strpos($final_file, "."));
          $final_file = $final_file.'.mp4';
          // some operations to delete the old file
          $video
          ->save(new FFMpeg\Format\Video\X264(), $final_file); // save the new file
```

This works in command prompt but also gives `At least one output file must be specified` in red, I just want to convert most video formats to .mp4

**Comment by Daksh14** [comment]
Update: `$e->getMessage()` returns Encoding failed

**Comment by jens1o** [comment]
Please execute this command `C:\Fibble\nginx\Fibble\lib\\ffmpeg.EXE -y -i "C:/Fibble/nginx/Fibble/posts/33443rocketleague32bitdx914102018180636.mp4" -vcodec libx264 -acodec libfaac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k 33443rocketleague32bitdx914102018180636.mp4` and send the full stdout.

**Comment by PaulANormanNZ** [comment]
Hi,
I was getting exactly the same problem, and used this successfully...

$format=new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264'); 
$video->save($format, $small_mp4_file_path . ".mp4")

instead of the more direct approach...

$video->save(new FFMpeg\Format\Video\X264(), $small_mp4_file_path . ".mp4"); // save the new file

And it works.

Are there any other options than libmp3lame', 'libx264' ?

Paul

**Comment by jens1o** [comment]
Yeah, you can see them here: https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/89b0c2b4d0d12c515c4feaa2803f62259b631118/src/FFMpeg/Format/Video/X264.php#L57
