### ISSUE TITLE
FFProbe not found, PHP-FFmpeg not working...

### ISSUE THREAD

**Issue by bfeyaerts** [PHP-FFMpeg/PHP-FFMpeg#64]
Similar to issue #45, I seem to have a problem loading FFProbe (but that issue didn't actually present any working solution).
I use Xampp (32-bit version) on a Windows 7 (64-bit) computer.
PHP version is 5.4.7.

Before trying PHP-FFmpeg I had (and still have) ffmpeg-php installed.
After a fruitless search for decent (install) information about ffmpeg-php, I found out it was simply too slow, so therefore I resorted to PHP-FFmpeg, hoping for a better experience.
Alas, for PHP-FFmpeg I found even less information, and no information at all about solving problems...
So any help is very welcome.

This is the expetion php throws at me...
Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutableNotFoundException' with message 'Executable not found, proposed : avprobe, ffprobe' in path\to\vendor\Alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php:160
Stack trace:
-0 path\to\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration))
-1 path\to\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFProbe.php(206): FFMpeg\Driver\FFProbeDriver::create(Array, NULL)
-2 path\to\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFMpeg.php(118): FFMpeg\FFProbe::create(Array, NULL, NULL)
-3 path\to\script.php(20) in <b>path\to\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php</b> on line <b>50</b>

**Comment by jack-fdrv** [comment]
What mean "Have you registered the path to FFMpeg binary folder in your system Path ?" ?

**Comment by legionlad** [comment]
Here, how i solved it.

For me it was rather un-related. 

I was using SpatieMedia with ffmpeg to clip a video, store it in a temp folder then save .webm in the same directory created by spatiemedia.

The Ffprobe was loading right, it was the hard-coded paths in spatie-media which were wrong.

Fix
vendor\spatie\laravel-medialibrary\config\media-library.php 
 Changed those line to this, on my server Ubuntu 20
   
---------- 

    'ffmpeg_path' => '/usr/bin/ffmpeg',
        'ffprobe_path' =>  '/usr/bin/ffprobe',

----------


vendor\spatie\laravel-medialibrary\src\Conversions\ImageGenerators\Video.php
 Same change in convert() function

----------
 

      $ffmpeg = FFMpeg::create([
                'ffmpeg.binaries' => '/usr/bin/ffmpeg',
                'ffprobe.binaries' => '/usr/bin/ffprobe',
        ]);
----------
