### ISSUE TITLE
How to add transparent watermark ?

### ISSUE THREAD

**Issue by CodingMonkTech** [PHP-FFMpeg/PHP-FFMpeg#640]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | maybe
| Version Used   | ^0.13.0
| FFmpeg Version | ^0.13.0
| OS             | Your OS and version

#### Actual Behavior

I want to add transparent watermark using following code. 
`$video->filters()->custom('movie=logo.png [watermark]; [in][watermark] overlay=main_w-overlay_w-5:5 [out]');`

It applies watermark but without transparency.

couldn't find any documentation as well.    

#### Expected Behavior

Video with transparent overlay, watermark

#### Possible Solutions

If we do it with -filter_complex, we can do it, but i can't able to apply -filter_complex using filters()->custom() function.

**Comment by jens1o** [comment]
Could you give the FFMpeg command part for the watermark you want to execute, please?

**Comment by CodingMonkTech** [comment]
```
$ffmpeg = \FFMpeg\FFMpeg::create([ 'ffmpeg.binaries' => '/usr/bin/ffmpeg', 'ffprobe.binaries' => '/usr/bin/ffprobe'
            ]);

$video = $ffmpeg->open(storage_path('app/'.$Resource->raw_video_path));

$watermark=storage_path('app/public/uploads/settings/watermark_image.png');

$video->filters()->custom('movie='.$watermark.' [watermark];[in][watermark]  overlay=main_w-overlay_w-5:5 [out]');

```
If i do with exec(ffmpeg raw_ffmpeg_command_without_this_library) then i can do it, but i want to apply transparant watermark with custom filter command, plz share solution if you have.

**Comment by jens1o** [comment]
I meant what the `raw` ffmpeg command would be in this case, sorry for confusion! :(
