### ISSUE TITLE
Error execution test

### ISSUE THREAD

**Issue by camilo246800** [PHP-FFMpeg/PHP-FFMpeg#641]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Current
| FFmpeg Version | 4.1.3-static 
| OS             | Amazon Linux 2 AMI

#### Actual Behavior

I'm having trouble running the test script. It is not working for me ... I have checked the binaries and they are already installed.

#### Expected Behavior

Operation of the tests.

#### Steps to Reproduce

My CODE:

`error_reporting(E_ALL);
ini_set('display_errors', '1');

require 'vendor/autoload.php';
use FFMpeg\Format\Audio\Mp3;
use FFMpeg\Media\Video;
use FFMpeg\Media\Audio;

    
$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/local/bin/ffmpeg/ffmpeg',
    'ffprobe.binaries' => '/usr/local/bin/ffmpeg/ffprobe'
));

$video = $ffmpeg->open('video.mp4');

// Set an audio format
$audio_format = new FFMpeg\Format\Audio\Mp3();

// Extract the audio into a new file as mp3
$video->save($audio_format, 'result.mp3');`

ERROR:
`Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/local/bin/ffmpeg/ffmpeg' '-y' '-i' 'video.mp4' '-acodec' 'libmp3lame' '-b:a' '128k' 'result.mp3' in /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/local/bin...') #1 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #2 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, Array) #3 /var/www/html/includes/php-ffmpeg/vendor/php-ffmpeg/php in /var/www/html/includes/php-ffmpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/AbstractVideo.php on line 106`

#### Possible Solutions

- The installation of the binaries has already been checked from the console with ffmpeg -version.
- For some reason it seems you are not working, Change of version in the binaries, recommended?

**Comment by jens1o** [comment]
Could you run `which ffmpeg` and `which ffprobe` please?

**Comment by camilo246800** [comment]
Hello Jens!

Execute the commands, octuve the routes of the binaries and update my code. But I'm still wrong.

The good news: Probe the cod from the console and there it works without problems, octuve the correct result.

What could it be?

Result of which:

`/usr/bin/ffmpeg`
`/usr/bin/ffprobe`

My code update:

`require 'vendor/autoload.php';
use FFMpeg\Format\Audio\Mp3;
use FFMpeg\Media\Video;
use FFMpeg\Media\Audio;


    
$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe'
));


$video = $ffmpeg->open('video.mp4');

// Set an audio format
$audio_format = new FFMpeg\Format\Audio\Mp3();

// Extract the audio into a new file as mp3
$video->save($audio_format, 'result.mp3');`

Get error:

`Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-i' 'video.mp4' '-acodec' 'libmp3lame' '-b:a' '128k' 'result.mp3' in /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffmpe...') #1 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #2 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, Array) #3 /var/www/html/includes/php-ffmpeg/vendor/php-ffmpeg/php-ffmpeg/src/F in /var/www/html/includes/php-ffmpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/AbstractVideo.php on line 106`

I tried the commands in console and they worked! I got the audio. But not from php.

Any suggestions? THANK YOU.

**Comment by jens1o** [comment]
Could you post the exact output of `'/usr/bin/ffmpeg' '-y' '-i' 'video.mp4' '-acodec' 'libmp3lame' '-b:a' '128k' 'result.mp3'` and its exitcode(just execute `echo $?` after it)?

**Comment by camilo246800** [comment]
Hello Jens! Thanks for the support.

I was not clear about the fact $? (Sorry, the translation is not very clear).

Now, I have executed, with sudo (without it does not work). And the code works, I get the test script audio.

This is seen in the process console:

`[ec2-user@ip-172-31-17-179 ~]$ sudo '/usr/bin/ffmpeg' '-y' '-i' '/var/www/html/includes/php-ffmpeg/video.mp4' '-acodec' 'libmp3lame' '-b:a' '128k' '/var/www/html/includes/php-ffmpeg/result2.mp3'


ffmpeg version 4.1.3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/html/includes/php-ffmpeg/video.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-10-28T20:14:01.000000Z
  Duration: 00:03:50.37, start: 0.000000, bitrate: 571 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 473 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2018-10-28T20:14:01.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 10/28/2018.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2018-10-28T20:14:01.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 10/28/2018.
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to '/var/www/html/includes/php-ffmpeg/result2.mp3':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    TSSE            : Lavf58.20.100
    Stream #0:0(und): Audio: mp3 (libmp3lame), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2018-10-28T20:14:01.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 10/28/2018.
      encoder         : Lavc58.35.100 libmp3lame
size=    3601kB time=00:03:50.37 bitrate= 128.0kbits/s speed=41.8x
video:0kB audio:3600kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.015055%
`


I think it may be something of permission, but I have not been able to solve it. Any ideas?

Thank you!

**Comment by jens1o** [comment]
Okay, this is a great found!  

Who is the file owner of the files? Who owns the directory? Could you please make it so that the owner is the same user that executes the php script?

**Comment by camilo246800** [comment]
Hello Jens! Question of permissions, I could cut an audio, I am very happy.

Now I need to be able to concatenate audios. But I receive an error, apparently does not find the concat () method;

My code:

`<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

require 'vendor/autoload.php';

use FFMpeg\Format\Audio\Mp3;
use FFMpeg\Media\Audio;
use FFMpeg\Media\Concat;
    
$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe'
));


$audio = $ffmpeg->open( 'audio.mp3' );

$format = new \FFMpeg\Format\Audio\Mp3();

$audio->concat(array('audio.mp3', 'audio.mp3'))
      ->saveFromSameCodecs('audio-contact.mp3', TRUE);
     
?>`


My error:

`Fatal error: Uncaught Error: Call to undefined method FFMpeg\Media\Audio::concat() in /var/www/html/includes/php-ffmpeg/demo.php:21 Stack trace: #0 {main} thrown in /var/www/html/includes/php-ffmpeg/demo.php on line 21`


I tried to follow some examples that you have about this and previous questions, but it did not work for me.

Any ideas? Thanks for the support and follow-up!

**Comment by jens1o** [comment]
Oh wow. I missed to release this stuff, even when it was implemented more than half a year ago. Please try update to 0.14 and try again.

**Comment by camilo246800** [comment]
Hello Jens! Thank you.

I made the update, but in this case I get another error. :(

Any ideas?

My code:
 `<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

require 'vendor/autoload.php';

use FFMpeg\Format\Audio\Mp3;
use FFMpeg\Media\Audio;
use FFMpeg\Media\Concat;
    
$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe'
));


$audio = $ffmpeg->open( 'audio.mp3' );

$audio->concat(array('audio.mp3', 'audio.mp3'))
      ->saveFromSameCodecs('audio-contact.mp3', TRUE);
     
?>`


My error:

`Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffmpeg' '-f' 'concat' '-safe' '0' '-i' '/tmp/ffmpeg-concatoCMC8o' '-c' 'copy' 'audio-contact.mp3' in /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffmpe...') #1 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #2 /var/www/html/includes/php-ffmpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, NULL) #3 /var/www/html/includes/php-ffmpeg/vendor/php-ffmpeg in /var/www/html/includes/php-ffmpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Concat.php on line 149`

Thanks, Jens!!!

**Comment by camilo246800** [comment]
Hello @jens1o !

It was all about the routes, it works now!

Another query: Can I convert mp3 to wav or manage some formats? Or should I install the recommended library to increase the codecs? I have doubts with that library: Is it implemented in the same directory?

Thank you!

**Comment by jens1o** [comment]
Glad it works!


> I have doubts with that library: Is it implemented in the same directory?

Which library do you mean? If you have any doubts with this library: The complete source code is open(and contributions welcome!).

> Can I convert mp3 to wav or manage some formats?

Sure! Just open the file and when you want to `save` it, pass a different format. See https://github.com/PHP-FFMpeg/PHP-FFMpeg#transcoding-1 for an example. Also, what do you mean exactly by `manage some formats`?

**Comment by camilo246800** [comment]
Hey @jens1o 

For a moment I thought that to export wav I should make use of this recommendation: https://github.com/PHP-FFMpeg/PHP-FFMpeg-Extras

When I say administer, it is to work with different formats to concatenate, cut and export. Mp3, wav, wma.

Thank you!

**Comment by jens1o** [comment]
Ah, I see what you mean.

WAV is actually supported by this library, just use the `Wav` audio format class(https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Format/Audio/Wav.php).

WMA is not yet supported. Please open a new issue, and I'll treat it as an feature request.

**Comment by camilo246800** [comment]
Great! @jens1o!

Thanks for the support!
