### ISSUE TITLE
Allow copy audio codec for X264 and WebM

### ISSUE THREAD

**Issue by CamiloManrique** [PHP-FFMpeg/PHP-FFMpeg#645]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | yes
| Version Used   | master
| FFmpeg Version | ^4.1.3
| OS             | Windows 10

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

If I set copy as audio codec for any Video Format, I get an InvalidArgumentException

#### Expected Behavior

It allows copy as an audio codec when you are using X264 or WebM. I'm not expert on FFMpeg, but I already tested that this two formats allow copy. This is nice when you don't need/care to re encode the audio of your video. This way you don't need to worry about picking an audio codec, and also the whole transcoding can be faster (at least on what I tested, it is) 

#### Possible Solutions

Adding 'copy' as an available codec for X264 and WebM

**Comment by usamaejaz** [comment]
What if you also want to copy for video?
