### ISSUE TITLE
How to save direct in s3 Bucket?

### ISSUE THREAD

**Issue by KelvynCarbone** [PHP-FFMpeg/PHP-FFMpeg#656]
How to save direct in S3 Bucket, using Storage?

**Comment by vasanthudhaya** [comment]
FFMpeg::fromDisk('input_disk')
->open('input')
->addFilter(function ($filters) {
  $filters->clip();
})
->export()
->toDisk('output_disk')
->inFormat(new \FFMpeg\Format\Video\X264())
->save('output');

**Comment by jens1o** [comment]
This would require saving it locally first and then uploading it to the cloud. .)
