### ISSUE TITLE
Class 'FFMpeg\FFMpeg\Format\Video\X264' not found

### ISSUE THREAD

**Issue by moingeek** [PHP-FFMpeg/PHP-FFMpeg#657]
| Question
| When trying to save a new video with watermark using save method passing the             
$format = new FFMpeg\Format\Video\X264(); generate the error not found?
 
use FFMpeg\FFMpeg;

My code :
$ffmpeg = FFMpeg::create(array(
                'ffmpeg.binaries' => exec('which ffmpeg'),
                'ffprobe.binaries' => exec('which ffprobe')
            ));
            $filePath = public_path('storage/' . $media->model_id . '/' . $media->file_name);
            $watermarkPath = '/home/bakbuck-5/Downloads/watermark.png';
            $video = $ffmpeg->open($filePath);
            $format = new FFMpeg\Format\Video\X264();
            $video
                ->filters()
                ->watermark($watermarkPath, array(
                    'position' => 'relative',
                    'bottom' => 50,
                    'right' => 50,
                ));
            $video->save($format, 'watermarked.mp4');

Expected Solution:
It gets the format specified.

**Comment by vasanthudhaya** [comment]
@moingeek attach the video stream and audio stream. Use the below one
 
new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264'))

**Comment by moingeek** [comment]
> @moingeek attach the video stream and audio stream. Use the below one
> 
> new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264'))

Thank you ! This worked for me. I missed mentioning those streams as it were not in the documentation of official package of PHP-FFMPEG
