### ISSUE TITLE
Using this library in a docker context

### ISSUE THREAD

**Issue by jonathangreco** [PHP-FFMpeg/PHP-FFMpeg#660]
I'm using a docker cluster composed with

RabbitMQ / Symfony / A PHP worker / MySQL / Nginx

and the new one, FFMPEG.

my dockerfile is simple :

```
FROM alpine:3.8
RUN apk upgrade -U \
 && apk add ca-certificates ffmpeg libva-intel-driver \
 && rm -rf /var/cache/*

ENTRYPOINT ["/usr/bin/ffmpeg"]
```

But in my handler, I can't find in my path ffmpeg nor ffprobe, it's empty.

`
        dump(exec("which ffmpeg"), exec('which ffprobe'));
`

```
workers_1  | 
workers_1  |  [OK] Consuming messages from transports "ffmpeg".                              
workers_1  | 
workers_1  |  // The worker will automatically exit once it has received a stop signal via   
workers_1  |  // the messenger:stop-workers command.                                         
workers_1  | 
workers_1  |  // Quit the worker with CONTROL-C.                                             
workers_1  | 
workers_1  |  // Re-run the command with a -vv option to see logs about consumed messages.   
workers_1  | 
workers_1  | ""
workers_1  | ""
```

Last two lines show nothing.

Plus,

a docker-compose ps always show ffmpeg as exit 1, even if i just started it

```
docker-compose ps
          Name                       Command              State               Ports           
----------------------------------------------------------------------------------------------
my_project_back_ffmpeg_1    /usr/bin/ffmpeg                Exit 1                   

```

Any ideas ?

**Comment by jens1o** [comment]
Hey, I don't think this is a good place for such a question, as it is more related to docker itself. I would recommend you asking in another kind of forum. :)

**Comment by jonathangreco** [comment]
I understand, But now each PHP project with video treatment have a great chance to be dockerized, and ffmpeg is a pain in the ass to configure inside a docker cluster. It should be great if this plugin could provide a `dockerfile` that is compatible with a PHP container and accesible in the cluster.

It's the devops aspect that misses sometimes

**Comment by jens1o** [comment]
Hey, I'd like to file a new issue for that, however I wonder why that would make sense? This library is intended to be included in your real-world application, so why should it be isolated(and how is it even possible?)

**Comment by jonathangreco** [comment]
PHP-FFMpeg so as FFMpeg are included in my cluster within a docker container named `worker` . This PHP container allows me to manage my messages from rabbitMQ.  Each AMQP message contains a FFMPEG process to be executed.

Since I can't isolate ffmpeg in its own container, it's my `worker` container that takes care of it. A PHP handler (written with Symfony) will send call to the PHP-FFMpeg api in order to manipulate ffmpeg.
It works but it not a good practice.

I would have liked to be able to separate my `worker' container and FFMPEG, to be able to upgrade both more easily.

**Comment by jens1o** [comment]
Okay, thanks for the insights on how you are using this wrapper. I still cannot see the general need for a Dockerfile(what should it provide?), but thank you very much! :)
