### ISSUE TITLE
latest version don't support ffmpeg 4.1

### ISSUE THREAD

**Issue by steve3d** [PHP-FFMpeg/PHP-FFMpeg#666]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | yes
| Version Used   | 0.14
| FFmpeg Version | ffmpeg-4.1.3
| OS             | doesn't matter

#### Actual Behavior

in latest ffmpeg 4.1, ffmpeg has changed the command argument of `ffprobe` and `ffmpeg`, now ffmpeg and ffprobe both need `-h full` to get all command arguments. without `full` they both output very basic command argument list, so like `-show_streams` won't be listed, so throws a exception says: version 4.1 is too old..

#### Expected Behavior

should work on ffmpeg 4.1

**Comment by jens1o** [comment]
Thanks for this good bug report! :)

I don't happen to have an old version of ffmpeg installed, but it would it matter to say `-h full` to it?

**Comment by jens1o** [comment]
The code position would be https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/233742db0a0ec9b7e648b49b5725c36e16ca4e26/src/FFMpeg/FFProbe/OptionsTester.php#L61 

> I don't happen to have an old version of ffmpeg installed, but it would it matter to say -h full to it?

Otherwise we need to parse the version and check against different API levels.

**Comment by steve3d** [comment]
I don't have old version now, only ffmpeg 4.1.3, and to get full help for `ffmpeg`, you need to use `ffmpeg -h full`, but for `ffprobe`, you just need to use `ffprobe -h` for now.

**Comment by steve3d** [comment]
ah.... sorry, this might be my problem.

I have misconfigured the ffmpeg to run `ffprobe` and ffprobe to run `ffmpeg`.

after I set the correct value, it seems no problem at all.

sorry.

**Comment by jens1o** [comment]
Okay, because I just looked into it and I weren't able to reproduce it. :/
