### ISSUE TITLE
Allow for background/async ffmpeg operations so timeouts don't matter

### ISSUE THREAD

**Issue by mbmjertan** [PHP-FFMpeg/PHP-FFMpeg#671]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | yes
| Version Used   | v0.14
| FFmpeg Version | ffmpeg version 3.4.6-0ubuntu0.18.04.1
| OS             | Ubuntu 18.04 under WSL2

#### Actual Behavior

PHP-FFMpeg produces a timeout while converting a ~30MB mp4 video to webm under php7.3-fpm and nginx.

#### Expected Behavior

I understand that video operations are expensive, however, it would be useful for developers to have an option to execute ffmpeg commands in the background so ffmpeg operations don't block the rest of the script if ffmpeg doesn't finish the operation in time.  Currently, if php-ffmpeg times out, the ffmpeg command continues to execute, but the rest of PHP code doesn't. 

Additionally, having (at least shell commands) code that executes upon ffmpeg finishing the background operation would be nice (at least in the case of an error)

For me personally, increasing timeouts doesn't help much as I can't know how long a certain video will take to convert.

#### Steps to Reproduce

This is the code that produces the timeout:

```php
$ffmpeg = FFMpeg\FFMpeg::create([
                    'ffmpeg.binaries' => exec('which ffmpeg'),
                    'ffprobe.binaries' => exec('which ffprobe'),
                ]);
		$video = $ffmpeg->open('uploads/'.$videoRow['originalUploadFile']);
		$action = $queueRow['action'];
		$action = explode('/', $action);
		$resolution = $action[2];
		$format = $action[1];
		switch($resolution){
			case '1080p':
				$Dimension = new FFMpeg\Coordinate\Dimension(320, 240);
			break;
			case '720p':
				$Dimension = new FFMpeg\Coordinate\Dimension(960, 720);
			break;
			case '480p':
				$Dimension = new FFMpeg\Coordinate\Dimension(854, 480);
			break;
			case '360p':
				$Dimension = new FFMpeg\Coordinate\Dimension(640, 360);
			break;
		}
		switch($format){
			case 'mp4':
				$exportFormat = new FFMpeg\Format\Video\X264();
				$exportExt = '.mp4';
			break;
			case 'webm':
				$exportFormat = new FFMpeg\Format\Video\WebM();
				$exportExt = '.webm';
			break;
		}
		$format = $action[1];
		$video->filters()->resize($Dimension, FFMpeg\Filters\Video\ResizeFilter::RESIZEMODE_INSET, true)->synchronize();
		$exportFormat->on('progress', function ($video, $exportFormat, $percentage) {
    		echo "$percentage % transcoded";
		});
		$video->save($exportFormat, 'uploads/'.$videoRow['vmssID'].'_'.$format.'_'.$resolution.$exportExt);
```

#### Possible Solutions

If this is a feature you'd be willing to accept, I could work on implementing it.

**Comment by tenry18** [comment]
您可以在后台单独启动一个进程(cli),而不是在fpm中使用它,并且设置

    $ffmpeg = FFMpeg::create([
                'timeout'=>'0',
    ]);

**Comment by jens1o** [comment]
In addition to what @tenry18 says, please check whether the PHP script has a timeout set (maybe by the webserver?). Async processing is not really a thing in PHP.
