### ISSUE TITLE
Clip save method increase size of video

### ISSUE THREAD

**Issue by rtd21** [PHP-FFMpeg/PHP-FFMpeg#672]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | ffmpeg version 2.8.15-0ubuntu0.16.04.1
| OS             | ubuntu 16.04.1

#### Actual Behavior

I try to cut video using clip method. It increase size of original video in several times.
For example, original video size is 1,8 mb and duration 36 seconds. The clip size is 4 mb and duration 30 seconds.

#### Expected Behavior

Clip should have the same size or smaller, than original video.

#### Steps to Reproduce

$ffmpeg = FFMpeg::create($config);
$video = $ffmpeg->open($form->item->tempName);
$clip = $video->clip(TimeCode::fromSeconds($start), TimeCode::fromSeconds($this->maxVideoLength));
$format = new X264( 'libmp3lame', 'libx264' );
$clip->save($format, $name);

**Comment by jens1o** [comment]
duplicate https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/430
