### ISSUE TITLE
How get metada video file (width, height, format, duration, audio, size)?

### ISSUE THREAD

**Issue by g0d0** [PHP-FFMpeg/PHP-FFMpeg#673]
Relates to #264

#264 issue answers not working... streams() method not exists on FFMpeg class.

- I'm using version composer package version "php-ffmpeg/php-ffmpeg": "^0.14.0".
- PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )

**Comment by Pandiora** [comment]
It works for me:

```
$filename '<path to your file>'
$configuration = array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe'
);
$ffprobe = FFMpeg\FFProbe::create($configuration);

$stream = $ffprobe->streams($filename);

echo '<pre>'.htmlentities(print_r($stream,  true), ENT_SUBSTITUTE).'</pre>';
```

**Comment by KuToo** [comment]
$source = 'path';
        //创建ffmpeg
        $ffmpeg = FFMpeg::create([
            'ffmpeg.binaries' => '/usr/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/bin/ffprobe',
            'timeout' => 3600,
            'ffmpeg.threads' => 12,
        ]);
        $video=$ffmpeg->open($source);
        $video->getStreams()->audios()->first()->all();//音频参数
        $video->getStreams()->videos()->first()->all();//视频频参数
        //$video->getStreams()->videos()->first()->get('duration')
        $video->getStreams()->videos()->first()->getDimensions()->getHeight();//高度
        $video->getStreams()->videos()->first()->getDimensions()->getWidth();//宽度
        $video->getStreams()->videos()->first()->getDimensions()->getRatio();//频率

**Comment by KuToo** [comment]
`$source = 'path';
        //创建ffmpeg
        $ffmpeg = FFMpeg::create([
            'ffmpeg.binaries' => '/usr/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/bin/ffprobe',
            'timeout' => 3600,
            'ffmpeg.threads' => 12,
        ]);
        $video=$ffmpeg->open($source);
        $video->getStreams()->audios()->first()->all();//音频参数
        $video->getStreams()->videos()->first()->all();//视频频参数
        //$video->getStreams()->videos()->first()->get('duration')
        $video->getStreams()->videos()->first()->getDimensions()->getHeight();//音频参数
        $video->getStreams()->videos()->first()->getDimensions()->getWidth();//音频参数
        $video->getStreams()->videos()->first()->getDimensions()->getRatio();//音频参数`

**Comment by KuToo** [comment]
`$source = 'path';
        //创建ffmpeg
        $ffmpeg = FFMpeg::create([
            'ffmpeg.binaries' => '/usr/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/bin/ffprobe',
            'timeout' => 3600,
            'ffmpeg.threads' => 12,
        ]);
        $video=$ffmpeg->open($source);
        $video->getStreams()->audios()->first()->all();//音频参数
        $video->getStreams()->videos()->first()->all();//视频频参数
        //$video->getStreams()->videos()->first()->get('duration')
        $video->getStreams()->videos()->first()->getDimensions()->getHeight();//高
        $video->getStreams()->videos()->first()->getDimensions()->getWidth();//宽

**Comment by KuToo** [comment]
`
$source = 'path';
//创建ffmpeg
$ffmpeg = FFMpeg::create([
'ffmpeg.binaries' => '/usr/bin/ffmpeg',
'ffprobe.binaries' => '/usr/bin/ffprobe',
'timeout' => 3600,
'ffmpeg.threads' => 12,
]);
$video=$ffmpeg->open($source);
$video->getStreams()->audios()->first()->all();//音频参数
$video->getStreams()->videos()->first()->all();//视频频参数
//$video->getStreams()->videos()->first()->get('duration')
$video->getStreams()->videos()->first()->getDimensions()->getHeight();//高
$video->getStreams()->videos()->first()->getDimensions()->getWidth();//宽
`

**Comment by jens1o** [comment]
^ See this answer. :)

**Comment by RomanBurningMan** [comment]
$source = 'path'; //创建ffmpeg $ffmpeg = FFMpeg::create([ 'ffmpeg.binaries' => '/usr/bin/ffmpeg', 'ffprobe.binaries' => '/usr/bin/ffprobe', 'timeout' => 3600, 'ffmpeg.threads' => 12, ]); $video=$ffmpeg->open($source); $video->getStreams()->audios()->first()->all();//音频参数 $video->getStreams()->videos()->first()->all();//视频频参数 //$video->getStreams()->videos()->first()->get('duration') $video->getStreams()->videos()->first()->getDimensions()->getHeight();//高 $video->getStreams()->videos()->first()->getDimensions()->getWidth();

**Comment by PaulCnth** [comment]
No suggestion.  Just make the code easy-to-read :)

```php
$source = 'path';

//create ffmpeg
$ffmpeg = FFMpeg::create([
    'ffmpeg.binaries' => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe',
    'timeout' => 3600,
    'ffmpeg.threads' => 12,
]);

$video=$ffmpeg->open($source);

//audio params
$video->getStreams()->audios()->first()->all();

//video params
$video->getStreams()->videos()->first()->all();

// duration
$video->getStreams()->videos()->first()->get('duration');

//height
$video->getStreams()->videos()->first()->getDimensions()->getHeight();

//width
$video->getStreams()->videos()->first()->getDimensions()->getWidth();
```
