### ISSUE TITLE
laravel6 cann`t install

### ISSUE THREAD

**Issue by hamdon** [PHP-FFMpeg/PHP-FFMpeg#674]
alchemy/binary-driver 1.5.0 requires monolog/monolog ~1.3 
but：
Installation request for monolog/monolog (locked at 2.0.0) -> satisfiable by monolog/monolog[2.0.0].

**Comment by varmtech13** [comment]
Same issue

**Comment by WanglinGuo** [comment]
> Same issue. Call composer require "monolog/monolog:^1.3" before.

Thank you for solving my problem.
