### ISSUE TITLE
Unknown encoder `libfaac` !!

### ISSUE THREAD

**Issue by W7orld** [PHP-FFMpeg/PHP-FFMpeg#681]
Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command "C:/FFmpeg/bin/ffmpeg.exe" -y -i video1.mp4 -async 1 -metadata:s:v:0 start_time=0 -threads 12 -vcodec libx264 -acodec libfaac -b:v 1000k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k -vf "[in]scale=320:240 [out]" -pass 1 -passlogfile "C:\Users\DELL\AppData\Local\Temp\ffmpeg-passes5d9e35f516ce1e66b8/pass-5d9e35f517030" export-x264.mp4: Error Output: ffmpeg version N-95216-ge6625ca41f Copyright (c) 2000-2019 the FFmpeg developers built with gcc 9.2.1 (GCC) 20190918 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheor in C:\xampp\htdocs\Anime\s2\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\AbstractVideo.php on line 106`

**Comment by EmiiKhaos** [comment]
Just pass the right audiocodec in the constructor of the `X265` class.

```
$video->save(new FFMpeg\Format\Video\X264('aac'), 'export-x264.mp4')
```

see https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/89b0c2b4d0d12c515c4feaa2803f62259b631118/src/FFMpeg/Format/Video/X264.php#L25

**Comment by EmiiKhaos** [comment]
P.S: And just don't, don't write maintainers to their personal email...

**Comment by W7orld** [comment]
Ok. Thanks
