### ISSUE TITLE
Compress the video

### ISSUE THREAD

**Issue by matrix4583** [PHP-FFMpeg/PHP-FFMpeg#684]
How do i compress the video using php? The documentation only refers to size as in dimension of the video, but i don't want that. I want the video to resize from let say 100mb to 50 mb of video.

**Comment by tenry18** [comment]
我的命令是这样:
$video=$ffmpeg->open(xxxx);
$video_info=$video->getStreams()->videos()->first()->all();
$audio_info=$video->getStreams()->audios()->first()->all();
$format=new X264('aac','libx264');
 $format
                ->setKiloBitrate($video_bit_rate/1024)  //视频比特率
                ->setAudioChannels($audio_info['channels'])   // 声道设置，1单声道，2双声道，3立体声
                ->setAudioKiloBitrate($audio_bit_rate)//音频比特率
                ->setAdditionalParameters(['-vf','scale=-2:480']);//设置成480p

$video->save($format,xxxx);
通过调整分辨率以及音视频比特率来达到压缩的效果
