### ISSUE TITLE
Support HHVM please...

### ISSUE THREAD

**Issue by legol** [PHP-FFMpeg/PHP-FFMpeg#693]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | yes
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by jens1o** [comment]
As HHVM does not strive for PHP compatibility anymore, I don't see the point why I should now maintain two versions.
