### ISSUE TITLE
Will not install on Symfony 5

### ISSUE THREAD

**Issue by tacman** [PHP-FFMpeg/PHP-FFMpeg#697]
Run this from the command line in any empty directory

     symfony new --full .  && composer require php-ffmpeg/php-ffmpeg

The result:

```
Using version ^0.14.0 for php-ffmpeg/php-ffmpeg
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - alchemy/binary-driver v5.1.1 requires symfony/process ^2.3|^3.0|^4.0 -> no matching package found.
    - alchemy/binary-driver v2.0.0 requires symfony/process ^2.3|^3.0|^4.0 -> no matching package found.
    - alchemy/binary-driver 5.1.0 requires symfony/process ^2.3|^3.0|^4.0 -> no matching package found.
    - alchemy/binary-driver 5.0.0 requires symfony/process ^2.3|^3.0|^4.0 -> no matching package found.
    - alchemy/binary-driver 1.6.0 requires symfony/process ^2.0|^3.0 -> no matching package found.
    - alchemy/binary-driver 1.5.0 requires symfony/process ~2.0 -> no matching package found.
    - php-ffmpeg/php-ffmpeg v0.14 requires alchemy/binary-driver ^1.5 || ~2.0.0 || ^5.0 -> satisfiable by alchemy/binary-driver[1.5.0, 1.6.0, 5.0.0, 5.1.0, v2.0.0, v5.1.1].
    - Installation request for php-ffmpeg/php-ffmpeg ^0.14.0 -> satisfiable by php-ffmpeg/php-ffmpeg[v0.14].
```

It doesn't seem to matter if you change the version to 0.13, or set the minimum stability to dev, or install just the skeleton (without the --full).  Is there any way around this?  Or a way to prioritize the update of the dependencies?  Or install without the dependencies, since I don't need to use everything that this excellent package offers, just some basic stuff.

Thanks.

**Comment by alexander-schranz** [comment]
We are working on this `alchemy/binary-driver` was merged and think @jens1o is working on a release for this.
We also need to update `neutron/temporary-filesystem` to be compatible to symfony 5 PR is open https://github.com/romainneutron/Temporary-Filesystem/pull/15 hope @jens1o has also access to this and can create a release for it.

**Comment by jens1o** [comment]
This should be resolved by now, shouldn't it?

**Comment by alexander-schranz** [comment]
@jens1o yes this is resolved now and can be closed. Thank you!
