### ISSUE TITLE
How to fix EXT-X-MAP:URI in m3u8 when specifying absolute hls_fmp4_init_filename using ffmpeg?

### ISSUE THREAD

**Issue by ryancwalsh** [PHP-FFMpeg/PHP-FFMpeg#705]
This is not an "issue"/bug but more of a question: https://stackoverflow.com/q/60460212/470749

Probably this Issues section is only for suspected bugs, and I have no reason to think that there is a bug in PHP-FFMpeg (although maybe in ffmpeg itself?), so feel free to close this immediately. But I'd love to hear any thoughts here or on StackOverflow if you have a moment.

**Comment by jens1o** [comment]
I'm sorry, but due to my time constraints, I'm not able to provide general guidance with `ffmpeg` itself, but only `php-ffmpeg`. However, I am fine with anyone responding here in that case.
