### ISSUE TITLE
How to install minimum version?

### ISSUE THREAD

**Issue by n0ego** [PHP-FFMpeg/PHP-FFMpeg#706]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | v0.14
| FFmpeg Version | 2.8.15
| OS             | CentOS 7

Currently I can install the complete version of PHP-FFMPEG fine through composer. How do I install only a bare minimum version without docs, tests, etc?

Many thanks.

**Comment by jens1o** [comment]
`composer require php-ffmpeg/php-ffmpeg --prefer-dist` should be fine. :) If you notice anything in that package that doesn't necessarily need to be there, please raise a new issue.

**Comment by n0ego** [comment]
Thank for you reply. I've cleared cache then execute the command and it's still downloading docs and tests folders, etc.
Please see directory structure below.
.
├── composer.json
├── composer.lock
├── composer.phar
└── vendor
    ├── alchemy
    │   └── binary-driver
    │       ├── CHANGELOG.md
    │       ├── composer.json
    │       ├── LICENSE
    │       ├── phpunit.xml.dist
    │       ├── README.md
    │       ├── src
    │       └── tests
    ├── autoload.php
    ├── composer
    │   ├── autoload_classmap.php
    │   ├── autoload_files.php
    │   ├── autoload_namespaces.php
    │   ├── autoload_psr4.php
    │   ├── autoload_real.php
    │   ├── autoload_static.php
    │   ├── ClassLoader.php
    │   ├── installed.json
    │   └── LICENSE
    ├── doctrine
    │   └── cache
    │       ├── composer.json
    │       ├── lib
    │       ├── LICENSE
    │       ├── README.md
    │       └── UPGRADE.md
    ├── evenement
    │   └── evenement
    │       ├── CHANGELOG.md
    │       ├── composer.json
    │       ├── doc
    │       ├── examples
    │       ├── LICENSE
    │       ├── phpunit.xml.dist
    │       ├── README.md
    │       ├── src
    │       └── tests
    ├── neutron
    │   └── temporary-filesystem
    │       ├── CHANGELOG.md
    │       ├── composer.json
    │       ├── LICENSE
    │       ├── phpunit.xml.dist
    │       ├── README.md
    │       ├── src
    │       └── tests
    ├── php-ffmpeg
    │   └── php-ffmpeg
    │       ├── CHANGELOG.md
    │       ├── composer.json
    │       ├── docs
    │       ├── LICENSE
    │       ├── phpunit.xml.dist
    │       ├── README.md
    │       ├── src
    │       └── tests
    ├── psr
    │   └── log
    │       ├── composer.json
    │       ├── LICENSE
    │       ├── Psr
    │       └── README.md
    └── symfony
        ├── filesystem
        │   ├── CHANGELOG.md
        │   ├── composer.json
        │   ├── Exception
        │   ├── Filesystem.php
        │   ├── LICENSE
        │   └── README.md
        ├── polyfill-ctype
        │   ├── bootstrap.php
        │   ├── composer.json
        │   ├── Ctype.php
        │   ├── LICENSE
        │   └── README.md
        └── process
            ├── CHANGELOG.md
            ├── composer.json
            ├── Exception
            ├── ExecutableFinder.php
            ├── InputStream.php
            ├── LICENSE
            ├── PhpExecutableFinder.php
            ├── PhpProcess.php
            ├── Pipes
            ├── Process.php
            ├── ProcessUtils.php
            └── README.md
