### ISSUE TITLE
BUG |  FFMpeg doesnt read anyfile while terminal reads

### ISSUE THREAD

**Issue by helvetica123** [PHP-FFMpeg/PHP-FFMpeg#708]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | Latest
| FFmpeg Version | ffmpeg version n4.1.4
| OS             | Ubuntu Server version 18.04 LTS (bionic) 64-bit, 

#### Actual Behavior
FFMpeg doesnt read anyfile while terminal reads
How does PHP-FFMpeg behave at the moment?
Same
#### Expected Behavior
I expect doing something such as concert etc. with media files from FFMpeg.
What is the behavior you expect?
I wish it read files
#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

I can see files with ftp connection even more with terminal but ffmpeg command doesnt do it.I show the error on youtube link.

```
    root@cixme:/var/www/html# ls
    deneme.php  index.html  PHP-FFMpeg-master
    drop.avi    info.php    php-html5-video-converter-master
    root@cixme:/var/www/html# 
```
  
  https://youtu.be/9JbMCE9QioA

the link shows the error how disapers.

I use ubuntu vps server.the program is remmina

  https://i.stack.imgur.com/9hgEo.png

 ```
   root@cixme:/# sudo ffmpeg -i drop.mp4
    sudo: unable to resolve host cixme
    Error: unable to open display 
    ffmpeg version n4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
      built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
      configuration: --prefix= --prefix=/usr --disable-debug --disable-doc --disable-static --enable-avisynth --enable-cuda --enable-cuvid --enable-libdrm --enable-ffplay --enable-gnutls --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopus --enable-libpulse --enable-sdl2 --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-nonfree --enable-nvenc --enable-omx --enable-openal --enable-opencl --enable-runtime-cpudetect --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-xlib
      libavutil      56. 22.100 / 56. 22.100
      libavcodec     58. 35.100 / 58. 35.100
      libavformat    58. 20.100 / 58. 20.100
      libavdevice    58.  5.100 / 58.  5.100
      libavfilter     7. 40.101 /  7. 40.101
      libswscale      5.  3.100 /  5.  3.100
      libswresample   3.  3.100 /  3.  3.100
      libpostproc    55.  3.100 / 55.  3.100
    drop.mp4: No such file or directory


```

**Comment by jens1o** [comment]
Please note that `php-ffmpeg` is not `ffmpeg`. Please file the issue at the appropriate location.
