### ISSUE TITLE
I install ffmpeg with docker. How can I fill in ffmpeg.binaries

### ISSUE THREAD

**Issue by onlyquan** [PHP-FFMpeg/PHP-FFMpeg#709]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by jens1o** [comment]
Please fill out the issue template.

To answer your question, please install the ffmpeg binary into your docker-container and let the magic happen. :)
