### ISSUE TITLE
Run video encoding in background

### ISSUE THREAD

**Issue by gnumbs** [PHP-FFMpeg/PHP-FFMpeg#71]
I use PHP-FFmpeg for online video encoding, and it's very useful...But I need to allow users to do other things during video encoding. 

In other words, the php script must proceed after call of PHP-FFmpeg's save function, like the "ffmpeg" command has "&" option.

Can PHP-FFmpeg do this ?

Thanks, and sorry for my bad english.

**Comment by NSBrianWard** [comment]
So my understanding is that this would significantly decrease CPU usage when running FFMpeg in the background (Dean's answer): http://stackoverflow.com/questions/2946479/lower-cpu-used-by-ffmpeg-process-via-php-flv-video-conversion
