### ISSUE TITLE
composer require php-ffmpeg/php-ffmpeg --prefer-dist doesn't ignore dev folders

### ISSUE THREAD

**Issue by n0ego** [PHP-FFMpeg/PHP-FFMpeg#710]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | v0.14
| FFmpeg Version | 2.8.15
| OS             | CentOS 7

Hi, I execute the suggested command in issue #706 to ignore development folders such as docs, tests but it doesn't work.
See directory structure after running the command below.
.
├── composer.json
├── composer.lock
├── composer.phar
└── vendor
├── alchemy
│   └── binary-driver
│   ├── CHANGELOG.md
│   ├── composer.json
│   ├── LICENSE
│   ├── phpunit.xml.dist
│   ├── README.md
│   ├── src
│   └── tests
├── autoload.php
├── composer
│   ├── autoload_classmap.php
│   ├── autoload_files.php
│   ├── autoload_namespaces.php
│   ├── autoload_psr4.php
│   ├── autoload_real.php
│   ├── autoload_static.php
│   ├── ClassLoader.php
│   ├── installed.json
│   └── LICENSE
├── doctrine
│   └── cache
│   ├── composer.json
│   ├── lib
│   ├── LICENSE
│   ├── README.md
│   └── UPGRADE.md
├── evenement
│   └── evenement
│   ├── CHANGELOG.md
│   ├── composer.json
│   ├── doc
│   ├── examples
│   ├── LICENSE
│   ├── phpunit.xml.dist
│   ├── README.md
│   ├── src
│   └── tests
├── neutron
│   └── temporary-filesystem
│   ├── CHANGELOG.md
│   ├── composer.json
│   ├── LICENSE
│   ├── phpunit.xml.dist
│   ├── README.md
│   ├── src
│   └── tests
├── php-ffmpeg
│   └── php-ffmpeg
│   ├── CHANGELOG.md
│   ├── composer.json
│   ├── docs
│   ├── LICENSE
│   ├── phpunit.xml.dist
│   ├── README.md
│   ├── src
│   └── tests
├── psr
│   └── log
│   ├── composer.json
│   ├── LICENSE
│   ├── Psr
│   └── README.md
└── symfony
├── filesystem
│   ├── CHANGELOG.md
│   ├── composer.json
│   ├── Exception
│   ├── Filesystem.php
│   ├── LICENSE
│   └── README.md
├── polyfill-ctype
│   ├── bootstrap.php
│   ├── composer.json
│   ├── Ctype.php
│   ├── LICENSE
│   └── README.md
└── process
├── CHANGELOG.md
├── composer.json
├── Exception
├── ExecutableFinder.php
├── InputStream.php
├── LICENSE
├── PhpExecutableFinder.php
├── PhpProcess.php
├── Pipes
├── Process.php
├── ProcessUtils.php
└── README.md

**Comment by jens1o** [comment]
This could be solved by this tutorial and I'm happy to merge a Pull Request for it: https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

**Comment by Romain** [comment]
PR #783 fixes this.
