### ISSUE TITLE
How can i open file from cloud in order to process it?

### ISSUE THREAD

**Issue by rohitjalmi90** [PHP-FFMpeg/PHP-FFMpeg#714]
I am using FFmpeg library. I wanted to know if I can upload a file from the cloud server and process it.

I am aware of php-ffmpeg-video-streaming but i'll glad to know if such a feature is available in this library.

Regards,

**Comment by jens1o** [comment]
You would need to temporarily download the file(s) and then upload it back again on the servers you don't own (a.k.a. cloud).
