### ISSUE TITLE
Freezes when using video concat

### ISSUE THREAD

**Issue by tnduc** [PHP-FFMpeg/PHP-FFMpeg#716]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | ^0.14 (laravel-ffmpeg)
| FFmpeg Version | ffmpeg version 2.8.15-0ubuntu0.16.04.1
| OS             |  Docker - Ubuntu

#### Actual Behavior

```
 $disk = FFMpeg::fromDisk('local');

  $pathVideos = [];

 foreach ($this->videos as $key => $video) {
    $pathVideos[$key] = $video->getPath();
  }

 $disk->open("{$this->videos[0]->id}/{$this->videos[0]->file_name}")
     ->concat($pathVideos)
     ->saveFromSameCodecs(storage_path('app/' .  $this->videos[0]->collection_name) . ".mp4", TRUE);

```

#### Expected Behavior

No freezing, output_video duration = total_video duration

#### Steps to Reproduce

Video demo output: https://streamable.com/hnuzyp

#### Possible Solutions

Is it related to the processor thread or amd chip?

**Comment by jens1o** [comment]
Could you provide samples you can reproduce wiwth?

**Comment by tnduc** [comment]
> Could you provide samples you can reproduce with?

List videos:
[video 1](https://v16.tiktokcdn.com/2aa6cc9d026c3c81403eb0d62db9ccda/5e962c8e/video/n/v0102/85a9d787f3b041a8b307c65bef9fd03f/?a=1180&br=1266&bt=633&cr=0&cs=0&dr=3&ds=3&er=&l=20200414153455010189036023503D8E6B&lr=tiktok&qs=0&rc=anV2Z2Y5aTxyczMzMzgzM0ApaGc4aDo8Ozs8Nzs6aTY4M2dib2ouZl9jaHBfLS00LzRzcy0xXzFeMC4xYF8vXjJhL146Yw%3D%3D&vl=&vr=)
[video error](https://v16.tiktokcdn.com/305c96f44e5fa7f2ad5cf28c71bdc340/5e962c8f/video/n/v0102/5abd22a39bea4f9aade618736b08dd92/?a=1180&br=3782&bt=1891&cr=0&cs=0&dr=3&ds=3&er=&l=20200414153455010189036023503D8E6B&lr=tiktok&qs=0&rc=anVxd3lxPHlyczMzZzgzM0ApZTY0aWlkOzw1NzhoOTU8NWdpbWtlMXJhZ3BfLS1gLzRzcy4yYC8vMS00MzEuNC00YF86Yw%3D%3D&vl=&vr=)
[video 3](https://v16.tiktokcdn.com/016d21a8f65e5bcd437d67cd1e74669d/5e962c8a/video/tos/alisg/tos-alisg-pve-0037/37845aeeab6f4a66aefa7316fef28641/?a=1180&br=1192&bt=596&cr=0&cs=0&dr=3&ds=3&er=&l=20200414153455010189036023503D8E6B&lr=tiktok&qs=0&rc=M2lmcHZlZXB5czMzMzgzM0ApNmc2NDZoO2VlNzk7NjU8aGdmX3FiZGVqc3BfLS00LzRzc2JhMWM2YWBhXy1jY140LjE6Yw%3D%3D&vl=&vr=)

**Comment by tnduc** [comment]
> Could you provide samples you can reproduce with?

I have solved the problem with `framerate ()`, due to the different aspect ratios of videos.

**Comment by bmpf** [comment]
I'm having the same trouble, the videos have diferent framerates and different aspect ratios, how did you manage to solve it ? 

```
$video = $ffmpeg->open( '01.mp4' );
$video->filters()
->framerate( new FFMpeg\Coordinate\FrameRate(60), 9 )
->resize(new FFMpeg\Coordinate\Dimension(1920, 1080) , FFMpeg\Filters\Video\ResizeFilter::RESIZEMODE_SCALE_HEIGHT )->synchronize();
$video->save(new FFMpeg\Format\Video\X264(), '01-new.mp4');

$video = $ffmpeg->open( '02.mp4' );
$video->filters()
->framerate( new FFMpeg\Coordinate\FrameRate(60), 9 )
->resize(new FFMpeg\Coordinate\Dimension(1920, 1080) , FFMpeg\Filters\Video\ResizeFilter::RESIZEMODE_SCALE_HEIGHT )->synchronize();
$video->save(new FFMpeg\Format\Video\X264(), '02-new.mp4');


$video = $ffmpeg->open( '01-new.mp4' );
$video->concat([
        __DIR__ . '/01-new.mp4' ,
        __DIR__ . '/02-new.mp4' , 
])->saveFromSameCodecs('final.mp4', TRUE);
```


When playing the video, final.mp4, using VLC, from 01-new.mp4 to 02-new.mp4 the windows is resized and appears a black frame as transition that is not in both videos, even though the height and width of the converted videos are the same.
