### ISSUE TITLE
Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffprobe failed to execute command

### ISSUE THREAD

**Issue by netesy** [PHP-FFMpeg/PHP-FFMpeg#717]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | php-ffmpeg/php-ffmpeg via composer recently
| FFmpeg Version | FFmpeg git-2019-11-26-59d264b
| OS             | Windows 10

#### Actual Behavior

` Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffprobe failed to execute command C:\laragon\www\upload\include\ffmpeg\ffprobe.exe "https://upload.test/videos\Lekki_M.I_&_FAlZ___Erriga_upload.test_.mp4" -show_streams -print_format json: Error Output: ffprobe version git-2019-11-26-59d264b Copyright (c) 2007-2019 the FFmpeg developers built with gcc 9.2.1 (GCC) 20191125 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable- in C:\laragon\www\upload\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFProbe.php on line 263`

#### Expected Behavior

transcode the file

#### Steps to Reproduce
The encode function
`public function encode($link, string $name, $scale)
    {
		$logger = '';
        $ffmpeg = \FFMpeg\FFMpeg::create(array(
			'ffmpeg.binaries'  => getenv('BASE_PATH').getenv('FFMPEG'),
			'ffprobe.binaries' => getenv('BASE_PATH').getenv('FFPROBE'),
			'timeout'          => 3600, // The timeout for the underlying process
			'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
		));
        $video = $ffmpeg->open($link);
        if($scale == 360){
            $scale = new FFMpeg\Coordinate\Dimension(640, 360);
        }elseif ($scale == 480) {
            $scale = new FFMpeg\Coordinate\Dimension(854, 480);
        }elseif ($scale == 720) {
            $scale = new FFMpeg\Coordinate\Dimension(1280, 720);
        }elseif ($scale == 1080) {
            $scale = new FFMpeg\Coordinate\Dimension(1920, 1080);
        }else {
            throw new Exception("Error Wrong Video Scale ", $scale);
        }`
        
        //rescale the video
        $video->filters()->resize($scale)->synchronize();
        //watermark the video
        //$watermarks = self::watermark;
		//$video->addFilter(new SimpleFilter(['-crf', '27', '-preset', 'veryfast']));
        $video->filters()->watermark($this->watermark, array('position' => 'relative','bottom'=> 50,'right' => 50,));
        $format = new FFMpeg\Format\Video\X264();
		$percentage = $this->percentage;
        $format->on('progress', function ($video, $format, $percentage) {echo "$percentage % transcoded";});
        //$format->setKiloBitrate(1000)->setAudioChannels(2)->setAudioKiloBitrate(256);
        $video->save($format, "$name.mp4");
        //$video->save(new FFMpeg\Format\Video\WebM(), 'export-webm.webm');
    }`

the encode
`				$encode = new Encode();
				$encode->encode($url, $name, '360');`

**Comment by jens1o** [comment]
Could you please further troubleshoot yourself? A good pointer would be to run ` C:\laragon\www\upload\include\ffmpeg\ffprobe.exe "https://upload.test/videos\Lekki_M.I_&_FAlZ___Erriga_upload.test_.mp4" -show_streams -print_format json` manually and look for the error message yourself. :)

**Comment by netesy** [comment]
This is the response.
`ffprobe version git-2019-11-26-59d264b Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191125
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 36.100 / 56. 36.100
  libavcodec     58. 62.100 / 58. 62.100
  libavformat    58. 35.100 / 58. 35.100
  libavdevice    58.  9.101 / 58.  9.101
  libavfilter     7. 67.100 /  7. 67.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
{
[tls @ 000002264e4ffc00] Key usage violation in certificate has been detected.
https://upload.test/videos\Lekki_M.I_&_FAlZ___Erriga_upload.test_.mp4: I/O error

}`

**Comment by netesy** [comment]
solved the issue by using http://upload.test/videos\Lekki_M.I_&_FAlZ___Erriga_upload.test_.mp4. I think its because laragon certificate is self signed.

**Comment by jens1o** [comment]
Thank you. :)
