### ISSUE TITLE
Call to a member function setArguments() on null at xxx/Alchemy/BinaryDriver/ProcessBuilderFactory.php:171

### ISSUE THREAD

**Issue by Romoloso** [PHP-FFMpeg/PHP-FFMpeg#721]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.16.0
| FFmpeg Version | 4.2.2
| OS             | CentOS Linux release 7.7.1908 (Core) 

### Actual Behavior

I want add watermark to my video, because of the video is too large, so I used laravel queue.  

It is normal when I  run a job immediately (synchronously)，
but it tips  
 **call to a member function setArguments() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function setArguments() on null at /xxx/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessBuilderFactory.php:171)**   
 when I ran a job asynchronously

### Expected Behavior

run a job asynchronously like synchronously

###  Error message
local.ERROR: Call to a member function setArguments() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function setArguments() on null at /home/app/www/cross_b/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessBuilderFactory.php:171)
[stacktrace]
#0 /home/app/www/cross_b/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\\BinaryDriver\\ProcessBuilderFactory->create(Array)
#1 /home/app/www/cross_b/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(61): Alchemy\\BinaryDriver\\AbstractBinary->command(Array)
#2 /home/app/www/cross_b/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(43): FFMpeg\\FFProbe\\OptionsTester->retrieveHelpOutput()
#3 /home/app/www/cross_b/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(237): FFMpeg\\FFProbe\\OptionsTester->has('-show_streams')
#4 /home/app/www/cross_b/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(206): FFMpeg\\FFProbe->probe('/data/www/cross...', '-show_streams', 'streams')
#5 /home/app/www/cross_b/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(95): FFMpeg\\FFProbe->streams('/data/www/cross...')
#6 /home/app/www/cross_b/app/Lib/Tool/FFmpeg.php(75): FFMpeg\\FFMpeg->open('/data/www/cross...')
#7 /home/app/www/cross_b/app/Jobs/VideoAddWatermark.php(41): App\\Lib\\Tool\\FFmpeg->addWatermark('/data/www/cross...')
#8 [internal function]: App\\Jobs\\VideoAddWatermark->handle()

How can i fix it ?
Thanks

**Comment by jens1o** [comment]
Thanks for reporting! I created an issue at https://github.com/alchemy-fr/BinaryDriver/issues/45 as the problem lays deeper there.

**Comment by dangdungcntt** [comment]
Quick fix for this issue, when use with queued job, create FFMpeg instance in handle function instead of __construct


    public function __construct()
    {
        //$this->ffmpeg = FFMpeg::create(config('ffmpeg.create_options'));
    }

    public function handle()
    {
        $ffmpeg = FFMpeg::create(config('ffmpeg.create_options'));
    }
