### ISSUE TITLE
Video convert error. can you please help me

### ISSUE THREAD

**Issue by upendraalwafaa** [PHP-FFMpeg/PHP-FFMpeg#722]
Hii, 
i'm getting some error when i try to convert webm
My code is this 
can u help me please
i downloaded this composer 
composer require php-ffmpeg/php-ffmpeg
![Capture](https://user-images.githubusercontent.com/32842147/81262905-b8796100-904f-11ea-9d1d-14beb578ac4e.PNG)

require 'vendor/autoload.php';

$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('test.mp4');
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
    ->save('frame.jpg');
$video
    ->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4')
    ->save(new FFMpeg\Format\Video\WMV(), 'export-wmv.wmv')
    ->save(new FFMpeg\Format\Video\WebM(), 'export-webm.webm');

**Comment by jens1o** [comment]
Please install `ffmpeg` on the machine and supply its path to the `FFMpeg::create()` method. Please see the README for more details.
