### ISSUE TITLE
FFMpeg Audio merge Encoding failure.

### ISSUE THREAD

**Issue by Jessetje30** [PHP-FFMpeg/PHP-FFMpeg#731]
| Q              | A
| -------------- | ---
| Bug?           | Yes
| New Feature?   | no
| Version Used   | Latest
| FFmpeg Version | 3.4.6-ubuntu 
| OS             | Your OS and version

I have been working with FFMPEG, still a beginner but I learnt alot.

So I have to merge 2 audio's one that belongs to a video and one that is just an .mp3 file. I got the correct shell exec, but now I want to use the FFMPEG php library.

This is the correct (I think) and working shell command:

`/usr/bin/ffmpeg -y -i video-short.mp4 -i audio-short.mp3 -filter_complex "[0:a][1:a]amerge=inputs=2 [a]" -map 0:v -map "[a]" -c:v copy -c:a aac -ac 2 -b:a 128k video3-audio-output.mp4`
This outputs a video with 2 audio's.

I got this figured after I made the php code and editing some of the outputted code so the script works. Here is the php code, where I can't seem to figure out how to return the correct shell.

```
        $video = $this->ffmpeg->openAdvanced([
        'video-short.mp4',
        'audio-short.mp3'
    ]);
    $video
        ->filters()
        ->custom('[0:a][1:a]', 'amerge=inputs=', '2[a]' );
    $video
        ->map(array('0:v', '"[a]"'), new X264('aac'),
        'video3-audio-output.mp4'
    )
        ->save();
```
Now I need to get the code to return something like the shell that does work, I've been trying for alot of hours.

This is what my php returns it gives an encoding error, plus

`No channel layout for input 1`

`/usr/bin/ffmpeg -y -i video-short.mp4 -i audio-short.mp3 -filter_complex [0:a][1:a]amerge=inputs=2[a] -map 0:v -map "[a]" -vcodec libx264 -acodec aac -b:a 128k video3-audio-output.mp4`

So I added 'Copy' to FFMpeg\Format\Video\X264 getAvaiableVideoCodecs().

If I add 'copy' to new X264('aac', 'copy') It does dump the correct (above) Shell command, but it still crashes on "Encoding Failed"

Also Im not sure if I have the latest version of FFMPEG, I have no clue how to update the ubuntu package. I tried everything with sudo apt-get install/update and reinstalling

**Comment by Jessetje30** [comment]
I found the solution and it might be a common issue.

So you need to add 'copy' to FFMpeg\Format\Video\X264 getAvaiableVideoCodecs().

But instead of "amerge", which for some reason doesn't merge the given audio files in the frontend and returns Encoding Failed. We use amix.

Use amix. Here is an example on how the code looks like if it works.

$video = $this->ffmpeg->openAdvanced(array(
    'videoplayback.mp4',
    'audio-short.mp3'
));
$video
    ->filters()
    ->custom('[0:a][1:a]', 'amix=inputs=', '2[a]' );
$video
    ->map(array('0:v', '[a]'), new X264('aac', 'copy'),
   'video3-audio-output.mp4'
)
    ->save();
This can help people in the future.

**Comment by vijayantkatyal** [comment]
> I found the solution and it might be a common issue.
> 
> So you need to add 'copy' to FFMpeg\Format\Video\X264 getAvaiableVideoCodecs().
> 
> But instead of "amerge", which for some reason doesn't merge the given audio files in the frontend and returns Encoding Failed. We use amix.
> 
> Use amix. Here is an example on how the code looks like if it works.
> 
> ```
> $video = $this->ffmpeg->openAdvanced(array(
>     'videoplayback.mp4',
>     'audio-short.mp3'
> ));
> $video
>     ->filters()
>     ->custom('[0:a][1:a]', 'amix=inputs=', '2[a]' );
> $video
>     ->map(array('0:v', '[a]'), new X264('aac', 'copy'),
>    'video3-audio-output.mp4'
> )
>     ->save();
> ```
> 
> This can help people in the future.

this worked. thanks
