### ISSUE TITLE
clip audio

### ISSUE THREAD

**Issue by Ily-1606** [PHP-FFMpeg/PHP-FFMpeg#736]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             |  Windows 10 64bit

#### Actual Behavior

Error FFMpeg\Filters\Video\ClipFilter::apply()

#### Expected Behavior

Cut music $from -> $to 

#### Steps to Reproduce

function render_music($file, $dir, $from, $to)
{
    $config = [
        'ffmpeg.binaries'  => 'C:/ffmpeg/bin/ffmpeg.exe',
        'ffprobe.binaries' => 'C:/ffmpeg/bin/ffprobe.exe',
        'timeout'          => 3600, // The timeout for the underlying process
        'ffmpeg.threads'   => 4,   // The number of threads that FFmpeg should use
    ];
    $ffmpeg = FFMpeg\FFMpeg::create($config);
    $video = $ffmpeg->open($file);
    $video->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds($from), FFMpeg\Coordinate\TimeCode::fromSeconds($to));
    $audio_format = new FFMpeg\Format\Audio\Mp3();
    $video->save($audio_format,$_SERVER["DOCUMENT_ROOT"]."/storage/1/music/media.flac");
    return true;
}
Error response: 
Fatal error: Uncaught TypeError: Argument 2 passed to FFMpeg\Filters\Video\ClipFilter::apply() must be an instance of FFMpeg\Format\VideoInterface, instance of FFMpeg\Format\Audio\Mp3 given, called in...

**Comment by hnrazevedo** [comment]
Try to save the clip first and immediately after opening it, save the audio:

```
$video = $ffmpeg->open($file);
$clip = $video->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds($from), FFMpeg\Coordinate\TimeCode::fromSeconds($to));

$clip->save('clip.mp4');
$clipSave = $ffmpeg->open('clip.mp4');
$audio_format = new FFMpeg\Format\Audio\Mp3();
$clipSave ->save($audio_format,$_SERVER["DOCUMENT_ROOT"]."/storage/1/music/media.flac");
```

**Comment by rziw** [comment]
The same error while using like this:

**Comment by rziw** [comment]
The same error when trying to clip mp3 Audio like this:

`$ffmpeg = FFMpeg\FFMpeg::create();
        $audio = $ffmpeg->open($path);
        $format = new FFMpeg\Format\Audio\Mp3();

        $audio->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(10), FFMpeg\Coordinate\TimeCode::fromSeconds(20)); //0-30s

        $audio->save($format, $tdestination_path);`

It works only when I change ClipFilter to AudioClipFilter in clip method of VideoFilters.php  ,it seems the code goes for VideoFilter not the AudioFilter

**Comment by Ily-1606** [comment]
Thanks, I'm fixed

**Comment by Caoxl-C** [comment]
> Thanks, I'm fixed

How to fix, i have same error;

**Comment by fpolli** [comment]
This issue could be reopened. I have just experienced the same thing. Using the library in Laravel, I put the following at the head of the controller:

use FFMpeg\FFMpeg;
use FFMpeg\Media\Video;
use FFMpeg\Media\Audio;
use FFMpeg\Coordinate\TimeCode;
use FFMpeg\Format\Video\X264;
use FFMpeg\Format\Audio\Mp3;
use FFMpeg\Media\Waveform;

I have a function that clips and saves video. That works fine. I have an audio processing function that generates and saves a waveform, then optionally clips the audio, and saves it whether clipped or not. The waveform part works fine. The audio file will be successfully saved, but if I pass the function a begin and end, the clipping fails with the same error reported above. The function:

protected function processAudio($inaud,$disk,$outName,$begin,$end) {

  $outPath = "audio/$outName";
  $savePath = config("filesystems.disks.$disk.root") . "/$outPath";
  $wavePath = "$savePath.png";

  $ffmpeg = FFMpeg::create();
  $audio = $ffmpeg->open($inaud);
  //generate waveform
  $waveform = $audio->waveform(5120, 640, array('#0000FF','#FFFF00','#00AA00','#FF0000','#FF6600','#00FF00','#FF00FF','#ED00FF','#FFFFFF'));
  $waveform->save($wavePath);
  //if begin and end, trim
  if($end) {
    $duration = $end - $begin;
    $audio->filters()->clip(TimeCode::fromSeconds($begin), TimeCode::fromSeconds($duration));
  }

  $audio->save(new Mp3(), $savePath);


  return $outPath;
}

The error:

exception: "TypeError"
file: "......../vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Filters/Video/ClipFilter.php"
line: 61
message: 
"FFMpeg\\Filters\\Video\\ClipFilter::apply(): Argument #2 ($format) must be of type FFMpeg\\Format\\VideoInterface, FFMpeg\\Format\\Audio\\Mp3 given, called in ................./vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/AbstractVideo.php on line 168"

**Comment by greenreptile** [comment]
> The same error when trying to clip mp3 Audio like this:
> 
> ```
>    `$ffmpeg = FFMpeg\FFMpeg::create();
>     $audio = $ffmpeg->open($path);
>     $format = new FFMpeg\Format\Audio\Mp3();
> 
>     $audio->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(10), FFMpeg\Coordinate\TimeCode::fromSeconds(20)); //0-30s
> 
>     $audio->save($format, $tdestination_path);`
> ```
> 
> It works only when I change ClipFilter to AudioClipFilter in clip method of VideoFilters.php ,it seems the code goes for VideoFilter not the AudioFilter

I Experienced this issue in some specific mp3 files and find out open method in : src\FFMpeg\FFMpeg.php
can not detect file type correctly. **I suggest that this function accept second param (optional) that user can select file type manually**. something like this :

```
 public function open($pathfile,$type="audio")
    { 
```
Currently I did it myself. 😕

**Comment by nyc2phx** [comment]
> **I suggest that this function accept second param (optional) that user can select file type manually**. something like this :

@greenreptile - I did exactly this as well - explicitly give it what kind of file we're opening as the "auto detect" isn't really detecting.
I changed the function to this...
```

public function open($pathfile, $type = "audio")
    {
        if (null === $streams = $this->ffprobe->streams($pathfile)) {
            throw new RuntimeException(sprintf('Unable to probe "%s".', $pathfile));
        }

        if ( $type == "video" ) {
             // its a video file
             return new Video($pathfile, $this->driver, $this->ffprobe);
        } elseif ( $type == "audio" ) {
             // its an video file
             return new Audio($pathfile, $this->driver, $this->ffprobe);
        } 

        throw new InvalidArgumentException('Unable to detect file format, only audio and video supported');
    }
```
