### ISSUE TITLE
customize

### ISSUE THREAD

**Issue by michelmelo** [PHP-FFMpeg/PHP-FFMpeg#744]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

customize.
hello I have a command that is working by command line, and what I want to do now is to transform it using this class. how can i customize?

ffmpeg -i /piloto/000.mp4 -i /piloto/001.mp4 -c:v copy -c:a aac /piloto/output.mp4

**Comment by CharlieBrownCharacter** [comment]
@michelmelo were you able to implement your custom command?
