### ISSUE TITLE
Check if the video has an audio track

### ISSUE THREAD

**Issue by hnrazevedo** [PHP-FFMpeg/PHP-FFMpeg#746]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | Possible
| Version Used   | 0.14.0
| FFmpeg Version | ffmpeg version git-2020-04-12-f1894c2
| OS             | Windows 10 64bit

#### Actual Behavior

I am making a video system similar to Youtube currently, separating the video file from the audio file, until then everything was ok, but when trying to upload a video file without audio, the same one from the following error when trying to save the audio files:

```
Output #0, mp3, to 'C:\Server\www\html\assets\video\2\193a4cb653cacec13a1de6b9848ceebff09a87f5\audio\193a4cb653cacec13a1de6b9848ceebff09a87f5.mp3':
Output file #0 does not contain any stream
```

#### Expected Behavior

I would like to know if there is any way via FFMPeg-PHP to check if the video file has an audio track, before entering to extract it.

#### Steps to Reproduce

```
$audio = $ffmpeg->open($fileVideoNotAudioFound);
$formatAudio = new \FFMpeg\Format\Audio\Mp3();
$audio->save($formatAudio,$pathFileAudio.'.mp3');

```

#### Possible Solutions

Any function to check if there is an audio track?

**Comment by jens1o** [comment]
Most likely you could use the [FFProbe functionality](https://github.com/PHP-FFMpeg/PHP-FFMpeg#ffprobe) to check whether an audio track is included.
