### ISSUE TITLE
Windows Binaries

### ISSUE THREAD

**Issue by JorgeosorioDev** [PHP-FFMpeg/PHP-FFMpeg#765]
Hello I cant download the windows binaries, can you help me. 
Thanks.

**Comment by fhdalikhan** [comment]
You can download them directly from the ffmpeg website at: https://ffmpeg.org/download.html#build-windows

The link provided in the description no longer works but can be accessed at the below link:
https://web.archive.org/web/20200901144023if_/https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20200831-4a11a6f-win64-static.zip

You can browse the website as well: https://web.archive.org/web/20200919011114/https://ffmpeg.zeranoe.com/builds/
