### ISSUE TITLE
Encoding failed. thanks a lot for extended information. no examples for rigt error handling. ffmpeg in console has mach more info about error then your library. try/catch doesnot help. thanks a lot

### ISSUE THREAD

**Issue by morozovsk** [PHP-FFMpeg/PHP-FFMpeg#768]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

#### Actual Behavior

How does PHP-FFMpeg behave at the moment?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
Otherwise remove this section.

**Comment by morozovsk** [comment]
thanks a lot

**Comment by mdolnik** [comment]
FYI: The exceptions thrown are nested, so you would want to get the previous exception(s) in order to get more valuable encoding error messages (eg the FFMPEG error output).

Eg:
```
try {
  $video = $ffmpeg->open( 'video.mp4' );
  $format = new FFMpeg\Format\Video\X264();
  $video->save($format, 'video.avi');
catch (Throwable $e) {
  echo $e->getMessage();
  echo $e->getPrevious()->getMessage();
}
```

If you want ALL of the errors (not _as_ useful, but may help in some cases):
```
try {
  $video = $ffmpeg->open( 'video.mp4' );
  $format = new FFMpeg\Format\Video\X264();
  $video->save($format, 'video.avi');
catch (Throwable $e) {
  echo $e->getMessage();
  echo $e->getTraceAsString();
  echo 'Previous Errors...';
  $e_clone = $e;
  while (NULL !== $e_clone = $e_clone->getPrevious()) {
    echo $e_clone->getMessage();
    echo $e_clone->getTraceAsString();
    echo "\n";
  }
}
```
