### ISSUE TITLE
Tag release with PHP 8.0 support 

### ISSUE THREAD

**Issue by pascalbaljet** [PHP-FFMpeg/PHP-FFMpeg#769]
Hey @jens1o! Could you please tag a new version so that there's a stable release with PHP 8.0 support? The Laravel community is quite progressive when it comes to upgrading. This way, we can tag a new release of [Laravel-FFMpeg](https://github.com/protonemedia/laravel-ffmpeg) as well :)

Not much has changed in the master branch since v0.16, so it can be a minor release.
https://github.com/PHP-FFMpeg/PHP-FFMpeg/compare/v0.16...master

Thanks in advance! 🙌

**Comment by freekmurze** [comment]
Also waiting for this to be able to run [laravel-medialibrary](https://spatie.be/docs/laravel-medialibrary) on PHP 8.

**Comment by Salman98** [comment]
waiting for this PR to merge

**Comment by kornrunner** [comment]
Actually, #782 should be merged in prior to tagging - it includes fixes for `call_user_func_array` (needed for PHP 8)

**Comment by pascalbaljet** [comment]
Thanks @kornrunner, @alexander-schranz and @Romain!
