### ISSUE TITLE
Set audio WAV file sample rate

### ISSUE THREAD

**Issue by PeterTough2** [PHP-FFMpeg/PHP-FFMpeg#784]
I want to set WAV audio file sample rate to 8000hz, which method can I achieve this with.

My code so far
```
$ffmpeg = FFMpeg\FFMpeg::create();
$audio = $ffmpeg->open('ttsMP3.com_VoiceText_2020-12-10_10.mp3');

$format = new FFMpeg\Format\Audio\Wav();
$format->on('progress', function ($audio, $format, $percentage) {
    echo "$percentage % transcoded";
});

$format->setAudioChannels(1)->setAudioKiloBitrate(16);
$audio->save($format, 'pbx_version_800.wav');
```

**Comment by tsmgeek** [comment]
I think you need to add a filter `AudioResamplableFilter` or you can go into doing an advanced

```
$audio->addFilter(new FFMpeg\Filters\Audio\AudioResamplableFilter(8000));
$audio->save($format, 'pbx_version_800.wav');

```

**Comment by PeterTough2** [comment]
> 
> 
> I think you need to add a filter `AudioResamplableFilter` or you can go into doing an advanced
> 
> ```
> $audio->addFilter(new FFMpeg\Filters\Audio\AudioResamplableFilter(8000));
> $audio->save($format, 'pbx_version_800.wav');
> ```

The right solution I was looking for.
Thanks.
