### ISSUE TITLE
How to monitor transcoding start event and transcoding finish event?

### ISSUE THREAD

**Issue by etjson** [PHP-FFMpeg/PHP-FFMpeg#802]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | v0.17.0
| FFmpeg Version | 4.3.2
| OS             | Windows 10

How to monitor transcoding start event and transcoding finish event?

**Comment by Romain** [comment]
Hi @etjson,
You can easily monitor the progress of your encoding. Using the percentage of progress, you'll now when it starts or finish.

```php
$video_ffmpeg = $ffmpeg->open( $full_video_path );

$format_x264 = new FFMpeg\Format\Video\X264();
$format_x264->setAudioCodec("libmp3lame");

$format_x264->on('progress', function ($video_ffmpeg, $format_x264, $percentage) use ($my_variable, $my_other_variable) {
    // Do whatever you want here with the percentage of progress...
});

$video_ffmpeg
    ->save($transcoded_file);
```

Hope this helps.
Romain
