### ISSUE TITLE
Laravel 8 Installation -> Monolog 1.3 error

### ISSUE THREAD

**Issue by thomasdseao** [PHP-FFMpeg/PHP-FFMpeg#823]
Hello,

I would like to install PHP-FFMpeg in my laravel 8 project but i got this error : 

**composer require php-ffmpeg/binary-driver=dev-master**
 _Problem 1
    - Root composer.json requires php-ffmpeg/binary-driver dev-master -> satisfiable by php-ffmpeg/binary-driver[dev-master].
    - php-ffmpeg/binary-driver dev-master requires monolog/monolog ^1.3 -> found monolog/monolog[1.3.0, ..., 1.x-dev] but the package is fixed to 2.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command._

**composer require "monolog/monolog:^1.3"**
 _Problem 1
    - laravel/framework is locked to version v8.48.1 and an update of this package was not requested.
    - laravel/framework v8.48.1 requires monolog/monolog ^2.0 -> found monolog/monolog[dev-main, 2.0.0-beta1, ..., 2.x-dev (alias of dev-main)] but it conflicts with your root composer.json require (^1.3)._

Someone already used this package with laravel 8 ?

Regards

**Comment by stevebauman** [comment]
For anyone else looking here:

Try deleting your `composer.lock` and your `vendor` directory, then run `composer require php-ffmpeg/php-ffmpeg` again. That resolved my issue.

It seems if you have a `composer.lock` file with the `v2.0` major version, then it won't downgrade it to `v1.3`, so you have to reset your applications composer environment to re-target `v1.3`.

This will likely be a problem in the future though. This package seems dead, so hoping someone can pick up its maintenance.

**Comment by pascalbaljet** [comment]
Fixed in [v1.0.0](https://github.com/PHP-FFMpeg/PHP-FFMpeg/releases/tag/v1.0.0).
