### ISSUE TITLE
PHP-FFMPEG throws runtime exception but the the ffmpeg process is still running.

### ISSUE THREAD

**Issue by tdaryani01** [PHP-FFMpeg/PHP-FFMpeg#86]
Hi,

First of all, I would like to thank you for the awesome library you have built.

I have been using PHP-FFMpeg for couple of months and it has been great. Yesterday, My server had utilized its CPU 100%. looking into the cause I realized that there were quite few processes running ffmpeg. It turns out that my worker was trying to encode an avi file, but each time it would fail because of a frame sync error and it would start again trying to encode the file again. But each time that it failed, the background process created by PHP-FFMpeg to run ffmpeg was still running so the server ended up with few ffmpeg processes that slowed down the server. When I ran the command manually, I noticed that ffmpeg threw an error complaining about frame sync error and it then continued to encode the file afterwards. the encoded video actually had good quality. I saw the same issue when my worker failed due to encoding taking longer than expected but when i checked the background process was still running. here is the message I got:

 [Symfony\Component\Process\Exception\ProcessTimedOutException]  
  The process "'/usr/bin/ffmpeg' '-y' '-i' '/home/taher/public_html/phonics.com/app/../web/uploads/5328ce9822be2.avi' '-f' 'webm' '-threads' '12' '-vcodec' 'libvpx' '-acodec' 'libvorbis' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '/home/taher/public_html/phonics.com/app/../web/uploads/5328d82329f8b.webm'" exceeded the timeout of 3600 seconds.   

However, the background process doing the encoding is still running:

PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND  
29057 taher  20   0 1055m  31m 5600 R  570  0.4 434:47.50 ffmpeg   

Here is  my code:

$ffmpeg->open($path)
                ->save(new Video\WebM(), $webmPath)
                ->save(new Video\X264(), $mp4Path);

Is there a way to configure php-ffmpeg to  just log errors like this and continue with encoding and only throw exceptions if the background ffmpeg process exites with failure. Is there a way to make sure that the background process stops if php-ffmpeg throws an exception?

Thanks
Taher

**Comment by jonathangreco** [comment]
Hi, @romainneutron @Romain  Why this issue is closed ? was it fixed ? Because I ran into this issue yesterday on my worker.
