### ISSUE TITLE
Image to video?

### ISSUE THREAD

**Issue by slaviczavik** [PHP-FFMpeg/PHP-FFMpeg#88]
Hi,

is possible to set an image(wetermark) to video?

Thx

**Comment by JoeDawson** [comment]
I too am interested in trying to do this, I've browsed the README several times but can't see any way of doing so. Although I have done with the command line. Preferably though, I'd love to include audio too.

This works from the command line;

```
ffmpeg -loop 1 -i image.jpg -i audio.mp3 -shortest -acodec copy -f x264 video.mp4
```

I was wondering how I would do this with this package?

**Comment by blainesch** [comment]
:+1: would really love this feature

**Comment by khalyomede** [comment]
Sorry to revive this thread like a zombie but, do we have any information how/why this issue have been closed? Is there any way to convert a bunch of images to a video using this library?

**Comment by slaviczavik** [comment]
> Sorry to revive this thread like a zombie but, do we have any information how/why this issue have been closed? Is there any way to convert a bunch of images to a video using this library?

I'm not longer using PHP for my app, but instead I'm using native app controlled via CLI.

This is an example how can it be done.

```
ffmpeg –i "input-video-path" -vf "movie=watermark.png [watermark]; [in][watermark] overlay=10:10 [out]" "output-video-path"
```

Coordinates are pointing to 10 pixels from top left corner.

**Comment by panchenkoprog** [comment]
+1 I also need these ability to create videos from one image!
