### ISSUE TITLE
Unable to load FFProbe - WAMP

### ISSUE THREAD

**Issue by abhaysharma** [PHP-FFMpeg/PHP-FFMpeg#89]
I am able to run the ffmpeg and ffprobe through command line but in the browser it gives me "Unable to load FFProbe" error. I have followed steps mentioned in https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/64

**Comment by amontero** [comment]
Same problem here on Windows Server 2008 R2 64b. and Ffmpeg 0f16dfd-win64-static.
I also try this:

            $ffmpeg = \FFMpeg\FFMpeg::create(array(
                'ffmpeg.binaries' => 'C:/Program Files (x86)/Ffmpeg/bin/ffmpeg.exe',
                'fprobe.binaries' => 'C:/Program Files (x86)/Ffmpeg/bin/ffprobe.exe',   
            ));

but doesn't work.

Any idea?

**Comment by 0x1ad2** [comment]
# How I did it
I'm using the following directory for the FFMpeg binaries: **C:\FFmpeg\bin**

* Download the binaries and place them into a **C:\** directory in my case.

* Set your [Windows PATH variable](http://superuser.com/a/284351) **be sure to set both the user and system variable**.

* Open up your CLI (command line interface) by running **cmd.exe** and check if **FFMpeg** could be executed.

* If the command could be executed run the following lines of PHP code to configure the FFMpeg wrapper and use it to create awesome video features for you application.

```php
        $FFMpeg = FFMpeg\FFMpeg::create([
            'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe', // the path to the FFMpeg binary
            'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprobe.exe', // the path to the FFProbe binary
            'timeout'          => 3600, // the timeout for the underlying process
            'ffmpeg.threads'   => 12,   // the number of threads that FFMpeg should use
        ]);
```
*I'm using the PHP 5.4 short array syntax*

**Comment by lingtalfi** [comment]
Thanks massimans, using the ffprobe's full path did it for me (so obvious when you think about it).

**Comment by Purus** [comment]
Note which slash you use. Use "C:/FFmpeg/bin/ffmpeg.exe" and not "C:\FFmpeg\bin\ffmpeg.exe"

Hope it helps someone.

**Comment by Romain** [comment]
Thanks @Purus for this contribution.
Regarding the age of this issue, I'll close it for now.
If anyone has a similar issue, please open a new one.
