### ISSUE TITLE
Encoding Failed

### ISSUE THREAD

**Issue by abhaysharma** [PHP-FFMpeg/PHP-FFMpeg#90]
I am running the basic script provided in the documentation. This is on a linux server. I am using a .mov file for testing. The frame is generated but the encoding fails with the following error.

```
exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-i' 'Algonquin elevators 4.mov' '-f' 'webm' '-vcodec' 'libvpx' '-acodec' 'libvorbis' '-b:v' '1000k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' 'export-webm.webm'' in /var/www/aims/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /var/www/aims/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffmpe...') #1 /var/www/aims/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #2 /var/www/aims/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, Array) #3 /var/www/aims/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php(155): Alchemy\BinaryDriver\AbstractBinary->command(Array, false, Array) #4 /var/www/aims/ffmpeg-test/index.php(37): FFMpeg\Media\Video->save(Object(FFMpeg\Format\Video\WebM), 'export-webm.web...') #5 {main} Next exception 'FFMpeg\Exception\RuntimeException' with message 'Encoding failed' in /var/www/aims/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php:165 Stack trace: #0 /var/www/aims/ffmpeg-test/index.php(37): FFMpeg\Media\Video->save(Object(FFMpeg\Format\Video\WebM), 'export-webm.web...') #1 {main}
```

The ffmpeg is working good through cmd line, also it works  if I run shell_exec

```
shell_exec("ffmpeg -i Algonquin elevators 4.mov output.webm &");

```

**Comment by Grald** [comment]
@sean-madhavan, how did u solve that problem i got same error too. and i downloaded the latest version what the next step? thank you in advance

**Comment by ghotgalkar** [comment]
Install FFMpeg like this

```
brew reinstall ffmpeg --with-faac --with-fdk-aac --with-ffplay --with-freetype --with-frei0r --with-libass --with-libvo-aacenc --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-opus --with-rtmpdump --with-schroedinger --with-speex --with-theora --with-tools
```

Remove the older version first.

**Comment by Grald** [comment]
thanks @ghotgalkar for the comment. How about on linux platform?

**Comment by Grald** [comment]
Hi guys, why i can't transcode video using php-ffmpeg in CENTOS server I tried in terminal and it works perfectly using root then the command but if not root 'encoding failed' occured. any idea what happening?

**Comment by keygenqt** [comment]
thanks @ghotgalkar!!

**Comment by farico** [comment]
Thanks @romainneutron for your commnt! Printing out errors revealed me that $ffmpeg->save(); could not save to target directory (even it was chmodded to 0777). I have changed it to /tmp/anyname and now it works.

**Comment by bakerstreetsystems** [comment]
Thanks @ghotgalkar

**Comment by ghotgalkar** [comment]
@Grald sorry for the super late reply. Not tried on linux. The main issue is that you need the compile flags to make sure you have all the requirements for audio and video encoding.

I found a lot of info on https://trac.ffmpeg.org/wiki/CompilationGuide

and also there is something specific for CentOS on https://trac.ffmpeg.org/wiki/CompilationGuide/Centos

Hopefully this helps.

**Comment by Grald** [comment]
@ghotgalkar it's okay now thanks :)

**Comment by zinzinday** [comment]
```
      use FFMpeg\FFMpeg;
      use FFMpeg\Format\Video\X264;
     ......
        set_time_limit(0);
     .......
        $ffmpeg = FFMpeg::create([
            'ffmpeg.binaries' => '/usr/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/bin/ffprobe',
            'timeout' => 0, // The timeout for the underlying process
            //'ffmpeg.threads' => 12,   // The number of threads that FFMpeg should use
        ]);
         $video = $ffmpeg->open( '/var/www/webroot/ccbank/frontend/web/uploads/vimeo.mp4');
        $watermark = '/var/www/webroot/ccbank/frontend/web/uploads/logo-h100.png';
        $video->filters()->watermark($watermark, [
            'position' => 'relative',
            'right' => 50,
            'top' => 50,
        ]);
        $format = new X264();
        $output =  '/var/www/webroot/ccbank/frontend/web/uploads/watermark1.mp4';
        $video->save($format, $output);
```
Browser error:
![error1](https://cloud.githubusercontent.com/assets/441560/19000317/26893080-876c-11e6-9ad1-66c8b5def90d.png)
Terminal:
 
![error2](https://cloud.githubusercontent.com/assets/441560/19000360/576719ec-876c-11e6-9a2f-804ec7b472d5.png)

How to fix that?

**Comment by Romain** [comment]
@zinzinday Have you managed to solve your issue?
If no, what is your environment? OS, FFMPEG version, etc...

**Comment by Tinywan** [comment]
echo "Starting ffmpeg...\n\n";
    echo shell_exec("ffmpeg -y -i input.avi output.avi </dev/null >/dev/null 2>/var/log/ffmpeg.log &");
    echo "Done.\n";

**Comment by Tinywan** [comment]
` echo "Starting ffmpeg...\n\n";
    echo shell_exec("ffmpeg -y -i input.avi output.avi </dev/null >/dev/null 2>/var/log/ffmpeg.log &");
    echo "Done.\n";`

**Comment by Tinywan** [comment]
`
echo "Starting ffmpeg...\n\n";
echo shell_exec("ffmpeg -y -i input.avi output.avi </dev/null >/dev/null 2>/var/log/ffmpeg.log &");
echo "Done.\n";
`

**Comment by Tinywan** [comment]
`
shell_exec("ffmpeg -y -i input.avi output.avi </dev/null >/dev/null 2>/var/log/ffmpeg.log &");
`

**Comment by Tinywan** [comment]
@Romain OK!

**Comment by shtse8** [comment]
I have the same issue, when adding watermark to images. some of images will throw Encoding error. and the result file size become zero.

**Comment by Romain** [comment]
Hi @shtse8,
This issue is pretty old, and doesn't relate specifically to watermarking.
Could you create a new one pasting the error throwed, your piece of code, and the result of the execution of the command line if you have it, so that we can help you debug your code?
Thanks

**Comment by boz14676** [comment]
> run it manually, it's probably about reading the passfile

Thanks, that's a smart way~
